// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_programs

// OMA-URIs of the ADMX_Programs nodes addressed by this package.
const (
	// the ADMX_Programs root node.
	URIRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_Programs"
	// the NoDefaultPrograms node.
	URINoDefaultPrograms = "./User/Vendor/MSFT/Policy/Config/ADMX_Programs/NoDefaultPrograms"
	// the NoGetPrograms node.
	URINoGetPrograms = "./User/Vendor/MSFT/Policy/Config/ADMX_Programs/NoGetPrograms"
	// the NoInstalledUpdates node.
	URINoInstalledUpdates = "./User/Vendor/MSFT/Policy/Config/ADMX_Programs/NoInstalledUpdates"
	// the NoProgramsAndFeatures node.
	URINoProgramsAndFeatures = "./User/Vendor/MSFT/Policy/Config/ADMX_Programs/NoProgramsAndFeatures"
	// the NoProgramsCPL node.
	URINoProgramsCPL = "./User/Vendor/MSFT/Policy/Config/ADMX_Programs/NoProgramsCPL"
	// the NoWindowsFeatures node.
	URINoWindowsFeatures = "./User/Vendor/MSFT/Policy/Config/ADMX_Programs/NoWindowsFeatures"
	// the NoWindowsMarketplace node.
	URINoWindowsMarketplace = "./User/Vendor/MSFT/Policy/Config/ADMX_Programs/NoWindowsMarketplace"
)
