// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_wpn_user

// OMA-URIs of the ADMX_WPN nodes addressed by this package.
const (
	// the ADMX_WPN root node.
	URIRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN"
	// the NoCallsDuringQuietHours node.
	URINoCallsDuringQuietHours = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoCallsDuringQuietHours"
	// the NoLockScreenToastNotification node.
	URINoLockScreenToastNotification = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoLockScreenToastNotification"
	// the NoQuietHours node.
	URINoQuietHours = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoQuietHours"
	// the NoToastNotification node.
	URINoToastNotification = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoToastNotification"
	// the QuietHoursDailyBeginMinute node.
	URIQuietHoursDailyBeginMinute = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/QuietHoursDailyBeginMinute"
	// the QuietHoursDailyEndMinute node.
	URIQuietHoursDailyEndMinute = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/QuietHoursDailyEndMinute"
)
