// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package authentication

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Authentication exposes LCRUD operations over the Authentication Policy area nodes.
type Authentication struct {
	c client.Client
}

// NewAuthentication returns a Authentication service backed by transport c.
func NewAuthentication(c client.Client) *Authentication {
	return &Authentication{c: c}
}
