// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package networklistmanager

// OMA-URIs of the NetworkListManager nodes addressed by this package.
const (
	// the NetworkListManager root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/NetworkListManager"
	// the AllNetworks_NetworkIcon node.
	URIAllNetworksNetworkIcon = "./Device/Vendor/MSFT/Policy/Config/NetworkListManager/AllNetworks_NetworkIcon"
	// the AllNetworks_NetworkLocation node.
	URIAllNetworksNetworkLocation = "./Device/Vendor/MSFT/Policy/Config/NetworkListManager/AllNetworks_NetworkLocation"
	// the AllNetworks_NetworkName node.
	URIAllNetworksNetworkName = "./Device/Vendor/MSFT/Policy/Config/NetworkListManager/AllNetworks_NetworkName"
	// the AllowedTlsAuthenticationEndpoints node.
	URIAllowedTlsAuthenticationEndpoints = "./Device/Vendor/MSFT/Policy/Config/NetworkListManager/AllowedTlsAuthenticationEndpoints"
	// the ConfiguredTlsAuthenticationNetworkName node.
	URIConfiguredTlsAuthenticationNetworkName = "./Device/Vendor/MSFT/Policy/Config/NetworkListManager/ConfiguredTlsAuthenticationNetworkName"
	// the IdentifyingNetworks_LocationType node.
	URIIdentifyingNetworksLocationType = "./Device/Vendor/MSFT/Policy/Config/NetworkListManager/IdentifyingNetworks_LocationType"
	// the UnidentifiedNetworks_LocationType node.
	URIUnidentifiedNetworksLocationType = "./Device/Vendor/MSFT/Policy/Config/NetworkListManager/UnidentifiedNetworks_LocationType"
	// the UnidentifiedNetworks_UserPermissions node.
	URIUnidentifiedNetworksUserPermissions = "./Device/Vendor/MSFT/Policy/Config/NetworkListManager/UnidentifiedNetworks_UserPermissions"
)
