// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package clouddesktop

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// CloudDesktop exposes LCRUD operations over the CloudDesktop CSP nodes.
type CloudDesktop struct {
	c client.Client
}

// NewCloudDesktop returns a CloudDesktop service backed by transport c.
func NewCloudDesktop(c client.Client) *CloudDesktop {
	return &CloudDesktop{c: c}
}
