// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package clouddesktop

// BootToCloudPCEnhanced allowed values.
const (
	// Not Configured
	BootToCloudPCEnhancedNotConfigured int64 = 0
	// Enable Boot to Cloud Shared PC Mode
	BootToCloudPCEnhancedEnableBootToCloudSharedPC int64 = 1
	// Enable Boot to Cloud Dedicated Mode (Cloud only)
	BootToCloudPCEnhancedEnableBootToCloudDedicatedMode int64 = 2
)
