// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package clouddesktop binds the CloudDesktop configuration service provider
// (./Device/Vendor/MSFT/CloudDesktop).
//
// Generated from the February 2026 DDF v2 release.
package clouddesktop
