// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package email2

// AccountGUIDACCOUNTTYPEValue — allowed values for the ACCOUNTTYPE node.
type AccountGUIDACCOUNTTYPEValue string

const (
	// normal email
	AccountGUIDACCOUNTTYPENormalEmail AccountGUIDACCOUNTTYPEValue = "Email"
	// visual voice mail
	AccountGUIDACCOUNTTYPEVisualVoiceMail AccountGUIDACCOUNTTYPEValue = "VVM"
)

// String returns the AccountGUIDACCOUNTTYPEValue value as a plain string.
func (e AccountGUIDACCOUNTTYPEValue) String() string { return string(e) }

// AccountGUIDAUTHREQUIREDValue — allowed values for the AUTHREQUIRED node.
type AccountGUIDAUTHREQUIREDValue string

const (
	// Server authentication is not required.
	AccountGUIDAUTHREQUIREDServerAuthenticationIsNotRequired AccountGUIDAUTHREQUIREDValue = "0"
	// Server authentication is required.
	AccountGUIDAUTHREQUIREDServerAuthenticationIsRequired AccountGUIDAUTHREQUIREDValue = "1"
)

// String returns the AccountGUIDAUTHREQUIREDValue value as a plain string.
func (e AccountGUIDAUTHREQUIREDValue) String() string { return string(e) }

// AccountGUIDDWNDAYValue — allowed values for the DWNDAY node.
type AccountGUIDDWNDAYValue string

const (
	// Specifies that all email currently on the server should be downloaded.
	AccountGUIDDWNDAYSpecifiesThatAllEmailCurrentlyOn AccountGUIDDWNDAYValue = "-1"
	// Specifies that 7 days’ worth of email should be downloaded.
	AccountGUIDDWNDAYSpecifiesThat7DaysWorthOf AccountGUIDDWNDAYValue = "7"
	// Specifies that 14 days’ worth of email should be downloaded.
	AccountGUIDDWNDAYSpecifiesThat14DaysWorthOf AccountGUIDDWNDAYValue = "14"
	// Specifies that 30 days’ worth of email should be downloaded.
	AccountGUIDDWNDAYSpecifiesThat30DaysWorthOf AccountGUIDDWNDAYValue = "30"
	// Specifies that 90 days’ worth of email should be downloaded.
	AccountGUIDDWNDAYSpecifiesThat90DaysWorthOf AccountGUIDDWNDAYValue = "90"
)

// String returns the AccountGUIDDWNDAYValue value as a plain string.
func (e AccountGUIDDWNDAYValue) String() string { return string(e) }

// AccountGUIDKEEPMAXValue — allowed values for the KEEPMAX node.
type AccountGUIDKEEPMAXValue string

const (
	// No limit is enforced
	AccountGUIDKEEPMAXNoLimitIsEnforced AccountGUIDKEEPMAXValue = "-1"
	// No attachment is downloaded
	AccountGUIDKEEPMAXNoAttachmentIsDownloaded AccountGUIDKEEPMAXValue = "0"
	// 25 KB
	AccountGUIDKEEPMAXN25KB AccountGUIDKEEPMAXValue = "25"
	// 50 KB
	AccountGUIDKEEPMAXN50KB AccountGUIDKEEPMAXValue = "50"
	// 100 KB
	AccountGUIDKEEPMAXN100KB AccountGUIDKEEPMAXValue = "100"
	// 250 KB
	AccountGUIDKEEPMAXN250KB AccountGUIDKEEPMAXValue = "250"
)

// String returns the AccountGUIDKEEPMAXValue value as a plain string.
func (e AccountGUIDKEEPMAXValue) String() string { return string(e) }

// AccountGUIDSERVERDELETEACTIONValue — allowed values for the SERVERDELETEACTION node.
type AccountGUIDSERVERDELETEACTIONValue string

const (
	// delete message on the server
	AccountGUIDSERVERDELETEACTIONDeleteMessageOnTheServer AccountGUIDSERVERDELETEACTIONValue = "1"
	// keep the message on the server (delete to the Trash folder).
	AccountGUIDSERVERDELETEACTIONKeepTheMessageOnTheServer AccountGUIDSERVERDELETEACTIONValue = "2"
)

// String returns the AccountGUIDSERVERDELETEACTIONValue value as a plain string.
func (e AccountGUIDSERVERDELETEACTIONValue) String() string { return string(e) }

// AccountGUIDSMTPALTENABLEDValue — allowed values for the SMTPALTENABLED node.
type AccountGUIDSMTPALTENABLEDValue string

const (
	// The user's alternate SMTP email account is disabled.
	AccountGUIDSMTPALTENABLEDTheUserSAlternateSMTPEmailAccount AccountGUIDSMTPALTENABLEDValue = "0"
	// The user's alternate SMTP email account is enabled.
	AccountGUIDSMTPALTENABLEDTheUserSAlternateSMTPEmailAccount2 AccountGUIDSMTPALTENABLEDValue = "1"
)

// String returns the AccountGUIDSMTPALTENABLEDValue value as a plain string.
func (e AccountGUIDSMTPALTENABLEDValue) String() string { return string(e) }

// AccountGUIDSYNCINGCONTENTTYPESValue — allowed values for the SYNCINGCONTENTTYPES node.
type AccountGUIDSYNCINGCONTENTTYPESValue string

const (
	// No data
	AccountGUIDSYNCINGCONTENTTYPESNoData AccountGUIDSYNCINGCONTENTTYPESValue = "0x0"
	// Contacts
	AccountGUIDSYNCINGCONTENTTYPESContacts AccountGUIDSYNCINGCONTENTTYPESValue = "0x1"
	// Mail
	AccountGUIDSYNCINGCONTENTTYPESMail AccountGUIDSYNCINGCONTENTTYPESValue = "0x2"
	// Appointments
	AccountGUIDSYNCINGCONTENTTYPESAppointments AccountGUIDSYNCINGCONTENTTYPESValue = "0x4"
	// Tasks
	AccountGUIDSYNCINGCONTENTTYPESTasks AccountGUIDSYNCINGCONTENTTYPESValue = "0x8"
	// Notes
	AccountGUIDSYNCINGCONTENTTYPESNotes AccountGUIDSYNCINGCONTENTTYPESValue = "0x10"
	// Feeds
	AccountGUIDSYNCINGCONTENTTYPESFeeds AccountGUIDSYNCINGCONTENTTYPESValue = "0x60"
	// Network Photo
	AccountGUIDSYNCINGCONTENTTYPESNetworkPhoto AccountGUIDSYNCINGCONTENTTYPESValue = "0x180"
	// Group and room
	AccountGUIDSYNCINGCONTENTTYPESGroupAndRoom AccountGUIDSYNCINGCONTENTTYPESValue = "0x200"
	// Chat
	AccountGUIDSYNCINGCONTENTTYPESChat AccountGUIDSYNCINGCONTENTTYPESValue = "0x400"
	// Email Recipient Email
	AccountGUIDSYNCINGCONTENTTYPESEmailRecipientEmail AccountGUIDSYNCINGCONTENTTYPESValue = "0x800"
	// Server Link
	AccountGUIDSYNCINGCONTENTTYPESServerLink AccountGUIDSYNCINGCONTENTTYPESValue = "0x1000"
	// All items
	AccountGUIDSYNCINGCONTENTTYPESAllItems AccountGUIDSYNCINGCONTENTTYPESValue = "0xffffffff"
)

// String returns the AccountGUIDSYNCINGCONTENTTYPESValue value as a plain string.
func (e AccountGUIDSYNCINGCONTENTTYPESValue) String() string { return string(e) }

// AccountGUIDTAGPROPSN8128000BValue — allowed values for the 8128000B node.
type AccountGUIDTAGPROPSN8128000BValue string

const (
	// SSL is not required.
	AccountGUIDTAGPROPSN8128000BSSLIsNotRequired AccountGUIDTAGPROPSN8128000BValue = "0"
	// SSL is required.
	AccountGUIDTAGPROPSN8128000BSSLIsRequired AccountGUIDTAGPROPSN8128000BValue = "1"
)

// String returns the AccountGUIDTAGPROPSN8128000BValue value as a plain string.
func (e AccountGUIDTAGPROPSN8128000BValue) String() string { return string(e) }

// AccountGUIDTAGPROPSN812C000BValue — allowed values for the 812C000B node.
type AccountGUIDTAGPROPSN812C000BValue string

const (
	// SSL is not required.
	AccountGUIDTAGPROPSN812C000BSSLIsNotRequired AccountGUIDTAGPROPSN812C000BValue = "0"
	// SSL is required.
	AccountGUIDTAGPROPSN812C000BSSLIsRequired AccountGUIDTAGPROPSN812C000BValue = "1"
)

// String returns the AccountGUIDTAGPROPSN812C000BValue value as a plain string.
func (e AccountGUIDTAGPROPSN812C000BValue) String() string { return string(e) }
