// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_disknvcache

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXDiskNVCache exposes LCRUD operations over the ADMX_DiskNVCache Policy area nodes.
type ADMXDiskNVCache struct {
	c client.Client
}

// NewADMXDiskNVCache returns a ADMXDiskNVCache service backed by transport c.
func NewADMXDiskNVCache(c client.Client) *ADMXDiskNVCache {
	return &ADMXDiskNVCache{c: c}
}
