// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package education_user

// AllowGraphingCalculator allowed values.
const (
	// Disabled.
	AllowGraphingCalculatorDisabled int64 = 0
	// Enabled.
	AllowGraphingCalculatorEnabled int64 = 1
)

// PreventAddingNewPrinters allowed values.
const (
	// Allow user installation.
	PreventAddingNewPrintersAllowUserInstallation int64 = 0
	// Prevent user installation.
	PreventAddingNewPrintersPreventUserInstallation int64 = 1
)
