// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package cellular

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetLetAppsAccessCellularData reads ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData.
// This policy setting specifies whether Windows apps can access cellular data.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) GetLetAppsAccessCellularData(ctx context.Context) (LetAppsAccessCellularDataValue, error) {
	v, err := s.c.Get(ctx, URILetAppsAccessCellularData)
	if err != nil {
		return 0, err
	}
	n, err := v.Int()
	return LetAppsAccessCellularDataValue(n), err
}

// CreateLetAppsAccessCellularData creates ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData.
// This policy setting specifies whether Windows apps can access cellular data.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) CreateLetAppsAccessCellularData(ctx context.Context, value LetAppsAccessCellularDataValue) error {
	return s.c.Add(ctx, URILetAppsAccessCellularData, client.Int(int64(value)))
}

// UpdateLetAppsAccessCellularData updates ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData.
// This policy setting specifies whether Windows apps can access cellular data.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) UpdateLetAppsAccessCellularData(ctx context.Context, value LetAppsAccessCellularDataValue) error {
	return s.c.Replace(ctx, URILetAppsAccessCellularData, client.Int(int64(value)))
}

// DeleteLetAppsAccessCellularData deletes ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData.
// This policy setting specifies whether Windows apps can access cellular data.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) DeleteLetAppsAccessCellularData(ctx context.Context) error {
	return s.c.Delete(ctx, URILetAppsAccessCellularData)
}

// GetLetAppsAccessCellularDataForceAllowTheseApps reads ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_ForceAllowTheseApps.
// List of semi-colon delimited Package Family Names of Windows Store Apps. Listed apps are allowed
// access to cellular data. This setting overrides the default LetAppsAccessCellularData policy
// setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) GetLetAppsAccessCellularDataForceAllowTheseApps(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URILetAppsAccessCellularDataForceAllowTheseApps)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateLetAppsAccessCellularDataForceAllowTheseApps creates ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_ForceAllowTheseApps.
// List of semi-colon delimited Package Family Names of Windows Store Apps. Listed apps are allowed
// access to cellular data. This setting overrides the default LetAppsAccessCellularData policy
// setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) CreateLetAppsAccessCellularDataForceAllowTheseApps(ctx context.Context, value string) error {
	return s.c.Add(ctx, URILetAppsAccessCellularDataForceAllowTheseApps, client.Chr(value))
}

// UpdateLetAppsAccessCellularDataForceAllowTheseApps updates ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_ForceAllowTheseApps.
// List of semi-colon delimited Package Family Names of Windows Store Apps. Listed apps are allowed
// access to cellular data. This setting overrides the default LetAppsAccessCellularData policy
// setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) UpdateLetAppsAccessCellularDataForceAllowTheseApps(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URILetAppsAccessCellularDataForceAllowTheseApps, client.Chr(value))
}

// DeleteLetAppsAccessCellularDataForceAllowTheseApps deletes ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_ForceAllowTheseApps.
// List of semi-colon delimited Package Family Names of Windows Store Apps. Listed apps are allowed
// access to cellular data. This setting overrides the default LetAppsAccessCellularData policy
// setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) DeleteLetAppsAccessCellularDataForceAllowTheseApps(ctx context.Context) error {
	return s.c.Delete(ctx, URILetAppsAccessCellularDataForceAllowTheseApps)
}

// GetLetAppsAccessCellularDataForceDenyTheseApps reads ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_ForceDenyTheseApps.
// List of semi-colon delimited Package Family Names of Microsoft Store Apps. Listed apps are
// denied access to cellular data. This setting overrides the default LetAppsAccessCellularData
// policy setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) GetLetAppsAccessCellularDataForceDenyTheseApps(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URILetAppsAccessCellularDataForceDenyTheseApps)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateLetAppsAccessCellularDataForceDenyTheseApps creates ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_ForceDenyTheseApps.
// List of semi-colon delimited Package Family Names of Microsoft Store Apps. Listed apps are
// denied access to cellular data. This setting overrides the default LetAppsAccessCellularData
// policy setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) CreateLetAppsAccessCellularDataForceDenyTheseApps(ctx context.Context, value string) error {
	return s.c.Add(ctx, URILetAppsAccessCellularDataForceDenyTheseApps, client.Chr(value))
}

// UpdateLetAppsAccessCellularDataForceDenyTheseApps updates ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_ForceDenyTheseApps.
// List of semi-colon delimited Package Family Names of Microsoft Store Apps. Listed apps are
// denied access to cellular data. This setting overrides the default LetAppsAccessCellularData
// policy setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) UpdateLetAppsAccessCellularDataForceDenyTheseApps(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URILetAppsAccessCellularDataForceDenyTheseApps, client.Chr(value))
}

// DeleteLetAppsAccessCellularDataForceDenyTheseApps deletes ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_ForceDenyTheseApps.
// List of semi-colon delimited Package Family Names of Microsoft Store Apps. Listed apps are
// denied access to cellular data. This setting overrides the default LetAppsAccessCellularData
// policy setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) DeleteLetAppsAccessCellularDataForceDenyTheseApps(ctx context.Context) error {
	return s.c.Delete(ctx, URILetAppsAccessCellularDataForceDenyTheseApps)
}

// GetLetAppsAccessCellularDataUserInControlOfTheseApps reads ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_UserInControlOfTheseApps.
// List of semi-colon delimited Package Family Names of Microsoft Store Apps. The user is able to
// control the cellular data access setting for the listed apps. This setting overrides the default
// LetAppsAccessCellularData policy setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) GetLetAppsAccessCellularDataUserInControlOfTheseApps(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URILetAppsAccessCellularDataUserInControlOfTheseApps)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateLetAppsAccessCellularDataUserInControlOfTheseApps creates ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_UserInControlOfTheseApps.
// List of semi-colon delimited Package Family Names of Microsoft Store Apps. The user is able to
// control the cellular data access setting for the listed apps. This setting overrides the default
// LetAppsAccessCellularData policy setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) CreateLetAppsAccessCellularDataUserInControlOfTheseApps(ctx context.Context, value string) error {
	return s.c.Add(ctx, URILetAppsAccessCellularDataUserInControlOfTheseApps, client.Chr(value))
}

// UpdateLetAppsAccessCellularDataUserInControlOfTheseApps updates ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_UserInControlOfTheseApps.
// List of semi-colon delimited Package Family Names of Microsoft Store Apps. The user is able to
// control the cellular data access setting for the listed apps. This setting overrides the default
// LetAppsAccessCellularData policy setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) UpdateLetAppsAccessCellularDataUserInControlOfTheseApps(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URILetAppsAccessCellularDataUserInControlOfTheseApps, client.Chr(value))
}

// DeleteLetAppsAccessCellularDataUserInControlOfTheseApps deletes ./Device/Vendor/MSFT/Policy/Config/Cellular/LetAppsAccessCellularData_UserInControlOfTheseApps.
// List of semi-colon delimited Package Family Names of Microsoft Store Apps. The user is able to
// control the cellular data access setting for the listed apps. This setting overrides the default
// LetAppsAccessCellularData policy setting for the specified apps.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) DeleteLetAppsAccessCellularDataUserInControlOfTheseApps(ctx context.Context) error {
	return s.c.Delete(ctx, URILetAppsAccessCellularDataUserInControlOfTheseApps)
}

// GetShowAppCellularAccessUI reads ./Device/Vendor/MSFT/Policy/Config/Cellular/ShowAppCellularAccessUI.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) GetShowAppCellularAccessUI(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIShowAppCellularAccessUI)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateShowAppCellularAccessUI creates ./Device/Vendor/MSFT/Policy/Config/Cellular/ShowAppCellularAccessUI.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) CreateShowAppCellularAccessUI(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIShowAppCellularAccessUI, client.Chr(value))
}

// UpdateShowAppCellularAccessUI updates ./Device/Vendor/MSFT/Policy/Config/Cellular/ShowAppCellularAccessUI.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) UpdateShowAppCellularAccessUI(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIShowAppCellularAccessUI, client.Chr(value))
}

// DeleteShowAppCellularAccessUI deletes ./Device/Vendor/MSFT/Policy/Config/Cellular/ShowAppCellularAccessUI.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *Cellular) DeleteShowAppCellularAccessUI(ctx context.Context) error {
	return s.c.Delete(ctx, URIShowAppCellularAccessUI)
}
