// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package windowsai

// AgentConnectorMinimumPolicy allowed values.
const (
	// User in control.
	AgentConnectorMinimumPolicyUserInControl int64 = 0
	// Restricted.
	AgentConnectorMinimumPolicyRestricted int64 = 1
	// Bypass.
	AgentConnectorMinimumPolicyBypass int64 = 2
)

// AllowRecallEnablement allowed values.
const (
	// Recall is not available
	AllowRecallEnablementRecallIsNotAvailable int64 = 0
	// Recall is available
	AllowRecallEnablementRecallIsAvailable int64 = 1
)

// AllowRecallExport allowed values.
const (
	// Deny export of Recall and snapshots information
	AllowRecallExportDenyExportOfRecallAndSnapshots int64 = 0
	// Allow export of Recall and snapshot information
	AllowRecallExportAllowExportOfRecallAndSnapshot int64 = 1
)

// DisableAIDataAnalysis allowed values.
const (
	// Enable Saving Snapshots for Recall.
	DisableAIDataAnalysisEnableSavingSnapshotsForRecall int64 = 0
	// Disable Saving Snapshots for Recall.
	DisableAIDataAnalysisDisableSavingSnapshotsForRecall int64 = 1
)

// DisableAgentConnectors allowed values.
const (
	// User in control.
	DisableAgentConnectorsUserInControl int64 = 0
	// Force Enable.
	DisableAgentConnectorsForceEnable int64 = 1
	// Force Disable.
	DisableAgentConnectorsForceDisable int64 = 2
)

// DisableAgentWorkspaces allowed values.
const (
	// User in control.
	DisableAgentWorkspacesUserInControl int64 = 0
	// Force Enable.
	DisableAgentWorkspacesForceEnable int64 = 1
	// Force Disable.
	DisableAgentWorkspacesForceDisable int64 = 2
)

// DisableClickToDo allowed values.
const (
	// Click to Do is enabled
	DisableClickToDoClickToDoIsEnabled int64 = 0
	// Click to Do is disabled.
	DisableClickToDoClickToDoIsDisabled int64 = 1
)

// DisableCocreator allowed values.
const (
	// Cocreator is enabled.
	DisableCocreatorCocreatorIsEnabled int64 = 0
	// Cocreator is disabled.
	DisableCocreatorCocreatorIsDisabled int64 = 1
)

// DisableGenerativeFill allowed values.
const (
	// Generative fill is enabled.
	DisableGenerativeFillGenerativeFillIsEnabled int64 = 0
	// Generative fill is disabled.
	DisableGenerativeFillGenerativeFillIsDisabled int64 = 1
)

// DisableImageCreator allowed values.
const (
	// Image Creator is enabled.
	DisableImageCreatorImageCreatorIsEnabled int64 = 0
	// Image Creator is disabled.
	DisableImageCreatorImageCreatorIsDisabled int64 = 1
)

// DisableRemoteAgentConnectors allowed values.
const (
	// User in control.
	DisableRemoteAgentConnectorsUserInControl int64 = 0
	// Force Enable.
	DisableRemoteAgentConnectorsForceEnable int64 = 1
	// Force Disable.
	DisableRemoteAgentConnectorsForceDisable int64 = 2
)

// DisableSettingsAgent allowed values.
const (
	// Settings Agentic search experience is enabled
	DisableSettingsAgentSettingsAgenticSearchExperienceIsEnabled int64 = 0
	// Settings Agentic search experience is not enabled
	DisableSettingsAgentSettingsAgenticSearchExperienceIsNot int64 = 1
)

// RemoveMicrosoftCopilotApp allowed values.
const (
	// Removal Disabled.
	RemoveMicrosoftCopilotAppRemovalDisabled int64 = 0
	// Removal Enabled.
	RemoveMicrosoftCopilotAppRemovalEnabled int64 = 1
)

// SetMaximumStorageDurationForRecallSnapshots allowed values.
const (
	// Let the OS define the maximum amount of time the snapshots will be saved
	SetMaximumStorageDurationForRecallSnapshotsLetTheOSDefineTheMaximum int64 = 0
	// 30 days
	SetMaximumStorageDurationForRecallSnapshotsN30Days int64 = 30
	// 60 days
	SetMaximumStorageDurationForRecallSnapshotsN60Days int64 = 60
	// 90 days
	SetMaximumStorageDurationForRecallSnapshotsN90Days int64 = 90
	// 180 days
	SetMaximumStorageDurationForRecallSnapshotsN180Days int64 = 180
)

// SetMaximumStorageSpaceForRecallSnapshots allowed values.
const (
	// Let the OS define the maximum storage amount based on hard drive storage size
	SetMaximumStorageSpaceForRecallSnapshotsLetTheOSDefineTheMaximum int64 = 0
	// 10GB
	SetMaximumStorageSpaceForRecallSnapshotsN10GB int64 = 10240
	// 25GB
	SetMaximumStorageSpaceForRecallSnapshotsN25GB int64 = 25600
	// 50GB
	SetMaximumStorageSpaceForRecallSnapshotsN50GB int64 = 51200
	// 75GB
	SetMaximumStorageSpaceForRecallSnapshotsN75GB int64 = 76800
	// 100GB
	SetMaximumStorageSpaceForRecallSnapshotsN100GB int64 = 102400
	// 150GB
	SetMaximumStorageSpaceForRecallSnapshotsN150GB int64 = 153600
)
