// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_lanmanworkstation

// OMA-URIs of the ADMX_LanmanWorkstation nodes addressed by this package.
const (
	// the ADMX_LanmanWorkstation root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_LanmanWorkstation"
	// the Pol_CipherSuiteOrder node.
	URIPolCipherSuiteOrder = "./Device/Vendor/MSFT/Policy/Config/ADMX_LanmanWorkstation/Pol_CipherSuiteOrder"
	// the Pol_EnableHandleCachingForCAFiles node.
	URIPolEnableHandleCachingForCAFiles = "./Device/Vendor/MSFT/Policy/Config/ADMX_LanmanWorkstation/Pol_EnableHandleCachingForCAFiles"
	// the Pol_EnableOfflineFilesforCAShares node.
	URIPolEnableOfflineFilesforCAShares = "./Device/Vendor/MSFT/Policy/Config/ADMX_LanmanWorkstation/Pol_EnableOfflineFilesforCAShares"
)
