// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_enhancedstorage

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXEnhancedStorage exposes LCRUD operations over the ADMX_EnhancedStorage Policy area nodes.
type ADMXEnhancedStorage struct {
	c client.Client
}

// NewADMXEnhancedStorage returns a ADMXEnhancedStorage service backed by transport c.
func NewADMXEnhancedStorage(c client.Client) *ADMXEnhancedStorage {
	return &ADMXEnhancedStorage{c: c}
}
