// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_powershellexecutionpolicy

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetEnableModuleLogging reads ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableModuleLogging.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) GetEnableModuleLogging(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIEnableModuleLogging)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateEnableModuleLogging creates ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableModuleLogging.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) CreateEnableModuleLogging(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIEnableModuleLogging, client.Chr(value))
}

// UpdateEnableModuleLogging updates ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableModuleLogging.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) UpdateEnableModuleLogging(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIEnableModuleLogging, client.Chr(value))
}

// DeleteEnableModuleLogging deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableModuleLogging.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) DeleteEnableModuleLogging(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableModuleLogging)
}

// GetEnableScripts reads ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableScripts.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) GetEnableScripts(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIEnableScripts)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateEnableScripts creates ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableScripts.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) CreateEnableScripts(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIEnableScripts, client.Chr(value))
}

// UpdateEnableScripts updates ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableScripts.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) UpdateEnableScripts(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIEnableScripts, client.Chr(value))
}

// DeleteEnableScripts deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableScripts.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) DeleteEnableScripts(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableScripts)
}

// GetEnableTranscripting reads ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableTranscripting.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) GetEnableTranscripting(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIEnableTranscripting)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateEnableTranscripting creates ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableTranscripting.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) CreateEnableTranscripting(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIEnableTranscripting, client.Chr(value))
}

// UpdateEnableTranscripting updates ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableTranscripting.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) UpdateEnableTranscripting(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIEnableTranscripting, client.Chr(value))
}

// DeleteEnableTranscripting deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableTranscripting.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) DeleteEnableTranscripting(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableTranscripting)
}

// GetEnableUpdateHelpDefaultSourcePath reads ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableUpdateHelpDefaultSourcePath.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) GetEnableUpdateHelpDefaultSourcePath(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIEnableUpdateHelpDefaultSourcePath)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateEnableUpdateHelpDefaultSourcePath creates ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableUpdateHelpDefaultSourcePath.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) CreateEnableUpdateHelpDefaultSourcePath(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIEnableUpdateHelpDefaultSourcePath, client.Chr(value))
}

// UpdateEnableUpdateHelpDefaultSourcePath updates ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableUpdateHelpDefaultSourcePath.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) UpdateEnableUpdateHelpDefaultSourcePath(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIEnableUpdateHelpDefaultSourcePath, client.Chr(value))
}

// DeleteEnableUpdateHelpDefaultSourcePath deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_PowerShellExecutionPolicy/EnableUpdateHelpDefaultSourcePath.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPowerShellExecutionPolicy) DeleteEnableUpdateHelpDefaultSourcePath(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableUpdateHelpDefaultSourcePath)
}
