// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package stickers

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Stickers exposes LCRUD operations over the Stickers Policy area nodes.
type Stickers struct {
	c client.Client
}

// NewStickers returns a Stickers service backed by transport c.
func NewStickers(c client.Client) *Stickers {
	return &Stickers{c: c}
}
