// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package credentialsui

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetDisablePasswordReveal reads ./Device/Vendor/MSFT/Policy/Config/CredentialsUI/DisablePasswordReveal.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *CredentialsUI) GetDisablePasswordReveal(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIDisablePasswordReveal)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateDisablePasswordReveal creates ./Device/Vendor/MSFT/Policy/Config/CredentialsUI/DisablePasswordReveal.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *CredentialsUI) CreateDisablePasswordReveal(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIDisablePasswordReveal, client.Chr(value))
}

// UpdateDisablePasswordReveal updates ./Device/Vendor/MSFT/Policy/Config/CredentialsUI/DisablePasswordReveal.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *CredentialsUI) UpdateDisablePasswordReveal(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIDisablePasswordReveal, client.Chr(value))
}

// DeleteDisablePasswordReveal deletes ./Device/Vendor/MSFT/Policy/Config/CredentialsUI/DisablePasswordReveal.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *CredentialsUI) DeleteDisablePasswordReveal(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisablePasswordReveal)
}

// GetEnumerateAdministrators reads ./Device/Vendor/MSFT/Policy/Config/CredentialsUI/EnumerateAdministrators.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *CredentialsUI) GetEnumerateAdministrators(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIEnumerateAdministrators)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateEnumerateAdministrators creates ./Device/Vendor/MSFT/Policy/Config/CredentialsUI/EnumerateAdministrators.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *CredentialsUI) CreateEnumerateAdministrators(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIEnumerateAdministrators, client.Chr(value))
}

// UpdateEnumerateAdministrators updates ./Device/Vendor/MSFT/Policy/Config/CredentialsUI/EnumerateAdministrators.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *CredentialsUI) UpdateEnumerateAdministrators(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIEnumerateAdministrators, client.Chr(value))
}

// DeleteEnumerateAdministrators deletes ./Device/Vendor/MSFT/Policy/Config/CredentialsUI/EnumerateAdministrators.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *CredentialsUI) DeleteEnumerateAdministrators(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnumerateAdministrators)
}
