// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package display

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Display exposes LCRUD operations over the Display Policy area nodes.
type Display struct {
	c client.Client
}

// NewDisplay returns a Display service backed by transport c.
func NewDisplay(c client.Client) *Display {
	return &Display{c: c}
}
