// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package display binds the Display Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/Display).
//
// Generated from the February 2026 DDF v2 release.
package display
