// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_appxpackagemanager

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetAllowDeploymentInSpecialProfiles reads ./Device/Vendor/MSFT/Policy/Config/ADMX_AppxPackageManager/AllowDeploymentInSpecialProfiles.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppxPackageManager) GetAllowDeploymentInSpecialProfiles(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIAllowDeploymentInSpecialProfiles)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateAllowDeploymentInSpecialProfiles creates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppxPackageManager/AllowDeploymentInSpecialProfiles.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppxPackageManager) CreateAllowDeploymentInSpecialProfiles(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIAllowDeploymentInSpecialProfiles, client.Chr(value))
}

// UpdateAllowDeploymentInSpecialProfiles updates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppxPackageManager/AllowDeploymentInSpecialProfiles.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppxPackageManager) UpdateAllowDeploymentInSpecialProfiles(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIAllowDeploymentInSpecialProfiles, client.Chr(value))
}

// DeleteAllowDeploymentInSpecialProfiles deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_AppxPackageManager/AllowDeploymentInSpecialProfiles.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppxPackageManager) DeleteAllowDeploymentInSpecialProfiles(ctx context.Context) error {
	return s.c.Delete(ctx, URIAllowDeploymentInSpecialProfiles)
}
