// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_windowsmediaplayer

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXWindowsMediaPlayer exposes LCRUD operations over the ADMX_WindowsMediaPlayer Policy area nodes.
type ADMXWindowsMediaPlayer struct {
	c client.Client
}

// NewADMXWindowsMediaPlayer returns a ADMXWindowsMediaPlayer service backed by transport c.
func NewADMXWindowsMediaPlayer(c client.Client) *ADMXWindowsMediaPlayer {
	return &ADMXWindowsMediaPlayer{c: c}
}
