// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package lockdown binds the LockDown Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/LockDown).
//
// Generated from the February 2026 DDF v2 release.
package lockdown
