// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_mobilepcpresentationsettings

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetPresentationSettingsEnable2 reads ./Device/Vendor/MSFT/Policy/Config/ADMX_MobilePCPresentationSettings/PresentationSettingsEnable_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXMobilePCPresentationSettings) GetPresentationSettingsEnable2(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIPresentationSettingsEnable2)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreatePresentationSettingsEnable2 creates ./Device/Vendor/MSFT/Policy/Config/ADMX_MobilePCPresentationSettings/PresentationSettingsEnable_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXMobilePCPresentationSettings) CreatePresentationSettingsEnable2(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIPresentationSettingsEnable2, client.Chr(value))
}

// UpdatePresentationSettingsEnable2 updates ./Device/Vendor/MSFT/Policy/Config/ADMX_MobilePCPresentationSettings/PresentationSettingsEnable_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXMobilePCPresentationSettings) UpdatePresentationSettingsEnable2(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIPresentationSettingsEnable2, client.Chr(value))
}

// DeletePresentationSettingsEnable2 deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_MobilePCPresentationSettings/PresentationSettingsEnable_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXMobilePCPresentationSettings) DeletePresentationSettingsEnable2(ctx context.Context) error {
	return s.c.Delete(ctx, URIPresentationSettingsEnable2)
}
