// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_devicesetup binds the ADMX_DeviceSetup Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_DeviceSetup).
//
// Generated from the February 2026 DDF v2 release.
package admx_devicesetup
