// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package taskscheduler binds the TaskScheduler Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/TaskScheduler).
//
// Generated from the February 2026 DDF v2 release.
package taskscheduler
