// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package taskscheduler

// OMA-URIs of the TaskScheduler nodes addressed by this package.
const (
	// the TaskScheduler root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/TaskScheduler"
	// the EnableXboxGameSaveTask node.
	URIEnableXboxGameSaveTask = "./Device/Vendor/MSFT/Policy/Config/TaskScheduler/EnableXboxGameSaveTask"
)
