// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package deliveryoptimization

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// DeliveryOptimization exposes LCRUD operations over the DeliveryOptimization Policy area nodes.
type DeliveryOptimization struct {
	c client.Client
}

// NewDeliveryOptimization returns a DeliveryOptimization service backed by transport c.
func NewDeliveryOptimization(c client.Client) *DeliveryOptimization {
	return &DeliveryOptimization{c: c}
}
