// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package secureboot

// ConfigureHighConfidenceOptOut allowed values.
const (
	// Disabled.
	ConfigureHighConfidenceOptOutDisabled int64 = 0
	// (Enabled) Opt out of high confidence buckets that will automatically be applied as part of the
	// LCU
	ConfigureHighConfidenceOptOutEnabledOptOutOfHighConfidence int64 = 1
)

// ConfigureMicrosoftUpdateManagedOptIn allowed values.
const (
	// Disabled
	ConfigureMicrosoftUpdateManagedOptInDisabled int64 = 0
	// Enabled
	ConfigureMicrosoftUpdateManagedOptInEnabled int64 = 1
)

// EnableSecurebootCertificateUpdates allowed values.
const (
	// Disabled
	EnableSecurebootCertificateUpdatesDisabled int64 = 0
	// (Enabled) Initiates the deployment of new secure boot certificates and related updates.
	EnableSecurebootCertificateUpdatesEnabledInitiatesTheDeploymentOfNew int64 = 22852
)
