// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package handwriting

// PanelDefaultModeDocked allowed values.
const (
	// Disabled.
	PanelDefaultModeDockedDisabled int64 = 0
	// Enabled.
	PanelDefaultModeDockedEnabled int64 = 1
)
