// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package handwriting

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Handwriting exposes LCRUD operations over the Handwriting Policy area nodes.
type Handwriting struct {
	c client.Client
}

// NewHandwriting returns a Handwriting service backed by transport c.
func NewHandwriting(c client.Client) *Handwriting {
	return &Handwriting{c: c}
}
