// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_windowsremotemanagement

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXWindowsRemoteManagement exposes LCRUD operations over the ADMX_WindowsRemoteManagement Policy area nodes.
type ADMXWindowsRemoteManagement struct {
	c client.Client
}

// NewADMXWindowsRemoteManagement returns a ADMXWindowsRemoteManagement service backed by transport c.
func NewADMXWindowsRemoteManagement(c client.Client) *ADMXWindowsRemoteManagement {
	return &ADMXWindowsRemoteManagement{c: c}
}
