// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package dmclient_user binds the DMClient configuration service provider
// (./User/Vendor/MSFT/DMClient).
//
// Generated from the February 2026 DDF v2 release.
package dmclient_user
