// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_dfs

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetDFSDiscoverDC reads ./Device/Vendor/MSFT/Policy/Config/ADMX_DFS/DFSDiscoverDC.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDFS) GetDFSDiscoverDC(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIDFSDiscoverDC)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateDFSDiscoverDC creates ./Device/Vendor/MSFT/Policy/Config/ADMX_DFS/DFSDiscoverDC.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDFS) CreateDFSDiscoverDC(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIDFSDiscoverDC, client.Chr(value))
}

// UpdateDFSDiscoverDC updates ./Device/Vendor/MSFT/Policy/Config/ADMX_DFS/DFSDiscoverDC.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDFS) UpdateDFSDiscoverDC(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIDFSDiscoverDC, client.Chr(value))
}

// DeleteDFSDiscoverDC deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_DFS/DFSDiscoverDC.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDFS) DeleteDFSDiscoverDC(ctx context.Context) error {
	return s.c.Delete(ctx, URIDFSDiscoverDC)
}
