// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package lanmanserver

// OMA-URIs of the LanmanServer nodes addressed by this package.
const (
	// the LanmanServer root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/LanmanServer"
	// the AuditClientDoesNotSupportEncryption node.
	URIAuditClientDoesNotSupportEncryption = "./Device/Vendor/MSFT/Policy/Config/LanmanServer/AuditClientDoesNotSupportEncryption"
	// the AuditClientDoesNotSupportSigning node.
	URIAuditClientDoesNotSupportSigning = "./Device/Vendor/MSFT/Policy/Config/LanmanServer/AuditClientDoesNotSupportSigning"
	// the AuditInsecureGuestLogon node.
	URIAuditInsecureGuestLogon = "./Device/Vendor/MSFT/Policy/Config/LanmanServer/AuditInsecureGuestLogon"
	// the AuthRateLimiterDelayInMs node.
	URIAuthRateLimiterDelayInMs = "./Device/Vendor/MSFT/Policy/Config/LanmanServer/AuthRateLimiterDelayInMs"
	// the EnableAuthRateLimiter node.
	URIEnableAuthRateLimiter = "./Device/Vendor/MSFT/Policy/Config/LanmanServer/EnableAuthRateLimiter"
	// the EnableMailslots node.
	URIEnableMailslots = "./Device/Vendor/MSFT/Policy/Config/LanmanServer/EnableMailslots"
	// the MaxSmb2Dialect node.
	URIMaxSmb2Dialect = "./Device/Vendor/MSFT/Policy/Config/LanmanServer/MaxSmb2Dialect"
	// the MinSmb2Dialect node.
	URIMinSmb2Dialect = "./Device/Vendor/MSFT/Policy/Config/LanmanServer/MinSmb2Dialect"
)
