// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package devicemanageability binds the DeviceManageability configuration service provider
// (./Device/Vendor/MSFT/DeviceManageability).
//
// Generated from the February 2026 DDF v2 release.
package devicemanageability
