// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_icm binds the ADMX_ICM Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_ICM).
//
// Generated from the February 2026 DDF v2 release.
package admx_icm
