// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_filerecovery binds the ADMX_FileRecovery Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_FileRecovery).
//
// Generated from the February 2026 DDF v2 release.
package admx_filerecovery
