// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_dwm_user

// OMA-URIs of the ADMX_DWM nodes addressed by this package.
const (
	// the ADMX_DWM root node.
	URIRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_DWM"
	// the DwmDefaultColorizationColor_1 node.
	URIDwmDefaultColorizationColor1 = "./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_1"
	// the DwmDisallowAnimations_1 node.
	URIDwmDisallowAnimations1 = "./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_1"
	// the DwmDisallowColorizationColorChanges_1 node.
	URIDwmDisallowColorizationColorChanges1 = "./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_1"
)
