// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_encryptfilesonmove binds the ADMX_EncryptFilesonMove Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_EncryptFilesonMove).
//
// Generated from the February 2026 DDF v2 release.
package admx_encryptfilesonmove
