// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_dnsclient

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXDnsClient exposes LCRUD operations over the ADMX_DnsClient Policy area nodes.
type ADMXDnsClient struct {
	c client.Client
}

// NewADMXDnsClient returns a ADMXDnsClient service backed by transport c.
func NewADMXDnsClient(c client.Client) *ADMXDnsClient {
	return &ADMXDnsClient{c: c}
}
