// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package kioskbrowser

// OMA-URIs of the KioskBrowser nodes addressed by this package.
const (
	// the KioskBrowser root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser"
	// the BlockedUrlExceptions node.
	URIBlockedUrlExceptions = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrlExceptions"
	// the BlockedUrls node.
	URIBlockedUrls = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrls"
	// the DefaultURL node.
	URIDefaultURL = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/DefaultURL"
	// the EnableEndSessionButton node.
	URIEnableEndSessionButton = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/EnableEndSessionButton"
	// the EnableHomeButton node.
	URIEnableHomeButton = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/EnableHomeButton"
	// the EnableNavigationButtons node.
	URIEnableNavigationButtons = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/EnableNavigationButtons"
	// the RestartOnIdleTime node.
	URIRestartOnIdleTime = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/RestartOnIdleTime"
)
