// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package kioskbrowser

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// KioskBrowser exposes LCRUD operations over the KioskBrowser Policy area nodes.
type KioskBrowser struct {
	c client.Client
}

// NewKioskBrowser returns a KioskBrowser service backed by transport c.
func NewKioskBrowser(c client.Client) *KioskBrowser {
	return &KioskBrowser{c: c}
}
