// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_dwm

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetDwmDefaultColorizationColor2 reads ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) GetDwmDefaultColorizationColor2(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIDwmDefaultColorizationColor2)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateDwmDefaultColorizationColor2 creates ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) CreateDwmDefaultColorizationColor2(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIDwmDefaultColorizationColor2, client.Chr(value))
}

// UpdateDwmDefaultColorizationColor2 updates ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) UpdateDwmDefaultColorizationColor2(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIDwmDefaultColorizationColor2, client.Chr(value))
}

// DeleteDwmDefaultColorizationColor2 deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) DeleteDwmDefaultColorizationColor2(ctx context.Context) error {
	return s.c.Delete(ctx, URIDwmDefaultColorizationColor2)
}

// GetDwmDisallowAnimations2 reads ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) GetDwmDisallowAnimations2(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIDwmDisallowAnimations2)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateDwmDisallowAnimations2 creates ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) CreateDwmDisallowAnimations2(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIDwmDisallowAnimations2, client.Chr(value))
}

// UpdateDwmDisallowAnimations2 updates ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) UpdateDwmDisallowAnimations2(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIDwmDisallowAnimations2, client.Chr(value))
}

// DeleteDwmDisallowAnimations2 deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) DeleteDwmDisallowAnimations2(ctx context.Context) error {
	return s.c.Delete(ctx, URIDwmDisallowAnimations2)
}

// GetDwmDisallowColorizationColorChanges2 reads ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) GetDwmDisallowColorizationColorChanges2(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIDwmDisallowColorizationColorChanges2)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateDwmDisallowColorizationColorChanges2 creates ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) CreateDwmDisallowColorizationColorChanges2(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIDwmDisallowColorizationColorChanges2, client.Chr(value))
}

// UpdateDwmDisallowColorizationColorChanges2 updates ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) UpdateDwmDisallowColorizationColorChanges2(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIDwmDisallowColorizationColorChanges2, client.Chr(value))
}

// DeleteDwmDisallowColorizationColorChanges2 deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXDWM) DeleteDwmDisallowColorizationColorChanges2(ctx context.Context) error {
	return s.c.Delete(ctx, URIDwmDisallowColorizationColorChanges2)
}
