// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_msapolicy

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetMicrosoftAccountDisableUserAuth reads ./Device/Vendor/MSFT/Policy/Config/ADMX_MSAPolicy/MicrosoftAccount_DisableUserAuth.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXMSAPolicy) GetMicrosoftAccountDisableUserAuth(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIMicrosoftAccountDisableUserAuth)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateMicrosoftAccountDisableUserAuth creates ./Device/Vendor/MSFT/Policy/Config/ADMX_MSAPolicy/MicrosoftAccount_DisableUserAuth.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXMSAPolicy) CreateMicrosoftAccountDisableUserAuth(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIMicrosoftAccountDisableUserAuth, client.Chr(value))
}

// UpdateMicrosoftAccountDisableUserAuth updates ./Device/Vendor/MSFT/Policy/Config/ADMX_MSAPolicy/MicrosoftAccount_DisableUserAuth.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXMSAPolicy) UpdateMicrosoftAccountDisableUserAuth(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIMicrosoftAccountDisableUserAuth, client.Chr(value))
}

// DeleteMicrosoftAccountDisableUserAuth deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_MSAPolicy/MicrosoftAccount_DisableUserAuth.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXMSAPolicy) DeleteMicrosoftAccountDisableUserAuth(ctx context.Context) error {
	return s.c.Delete(ctx, URIMicrosoftAccountDisableUserAuth)
}
