// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_sharing

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXSharing exposes LCRUD operations over the ADMX_Sharing Policy area nodes.
type ADMXSharing struct {
	c client.Client
}

// NewADMXSharing returns a ADMXSharing service backed by transport c.
func NewADMXSharing(c client.Client) *ADMXSharing {
	return &ADMXSharing{c: c}
}
