// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package memorydump binds the MemoryDump Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/MemoryDump).
//
// Generated from the February 2026 DDF v2 release.
package memorydump
