// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_hotspotauth

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetHotspotAuthEnable reads ./Device/Vendor/MSFT/Policy/Config/ADMX_hotspotauth/HotspotAuth_Enable.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXHotspotauth) GetHotspotAuthEnable(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIHotspotAuthEnable)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateHotspotAuthEnable creates ./Device/Vendor/MSFT/Policy/Config/ADMX_hotspotauth/HotspotAuth_Enable.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXHotspotauth) CreateHotspotAuthEnable(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIHotspotAuthEnable, client.Chr(value))
}

// UpdateHotspotAuthEnable updates ./Device/Vendor/MSFT/Policy/Config/ADMX_hotspotauth/HotspotAuth_Enable.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXHotspotauth) UpdateHotspotAuthEnable(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIHotspotAuthEnable, client.Chr(value))
}

// DeleteHotspotAuthEnable deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_hotspotauth/HotspotAuth_Enable.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXHotspotauth) DeleteHotspotAuthEnable(ctx context.Context) error {
	return s.c.Delete(ctx, URIHotspotAuthEnable)
}
