// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package wirelessdisplay

// OMA-URIs of the WirelessDisplay nodes addressed by this package.
const (
	// the WirelessDisplay root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay"
	// the AllowMdnsAdvertisement node.
	URIAllowMdnsAdvertisement = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowMdnsAdvertisement"
	// the AllowMdnsDiscovery node.
	URIAllowMdnsDiscovery = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowMdnsDiscovery"
	// the AllowMovementDetectionOnInfrastructure node.
	URIAllowMovementDetectionOnInfrastructure = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowMovementDetectionOnInfrastructure"
	// the AllowPCReceiverToBeTCPServer node.
	URIAllowPCReceiverToBeTCPServer = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowPCReceiverToBeTCPServer"
	// the AllowPCSenderToBeTCPClient node.
	URIAllowPCSenderToBeTCPClient = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowPCSenderToBeTCPClient"
	// the AllowProjectionFromPC node.
	URIAllowProjectionFromPC = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowProjectionFromPC"
	// the AllowProjectionFromPCOverInfrastructure node.
	URIAllowProjectionFromPCOverInfrastructure = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowProjectionFromPCOverInfrastructure"
	// the AllowProjectionToPC node.
	URIAllowProjectionToPC = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowProjectionToPC"
	// the AllowProjectionToPCOverInfrastructure node.
	URIAllowProjectionToPCOverInfrastructure = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowProjectionToPCOverInfrastructure"
	// the AllowUserInputFromWirelessDisplayReceiver node.
	URIAllowUserInputFromWirelessDisplayReceiver = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/AllowUserInputFromWirelessDisplayReceiver"
	// the RequirePinForPairing node.
	URIRequirePinForPairing = "./Device/Vendor/MSFT/Policy/Config/WirelessDisplay/RequirePinForPairing"
)
