// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package wirelessnetworkpreference

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// WirelessNetworkPreference exposes LCRUD operations over the WirelessNetworkPreference CSP nodes.
type WirelessNetworkPreference struct {
	c client.Client
}

// NewWirelessNetworkPreference returns a WirelessNetworkPreference service backed by transport c.
func NewWirelessNetworkPreference(c client.Client) *WirelessNetworkPreference {
	return &WirelessNetworkPreference{c: c}
}
