// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_printing_user

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXPrintingUser exposes LCRUD operations over the ADMX_Printing Policy area nodes.
type ADMXPrintingUser struct {
	c client.Client
}

// NewADMXPrintingUser returns a ADMXPrintingUser service backed by transport c.
func NewADMXPrintingUser(c client.Client) *ADMXPrintingUser {
	return &ADMXPrintingUser{c: c}
}
