// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package speech

// AllowSpeechModelUpdate allowed values.
const (
	// Not allowed.
	AllowSpeechModelUpdateNotAllowed int64 = 0
	// Allowed.
	AllowSpeechModelUpdateAllowed int64 = 1
)
