// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package speech

import (
	"fmt"
)

// AllowSpeechModelUpdateValue — allowed values for the AllowSpeechModelUpdate node.
type AllowSpeechModelUpdateValue int64

const (
	// Not allowed.
	AllowSpeechModelUpdateNotAllowed AllowSpeechModelUpdateValue = 0
	// Allowed.
	AllowSpeechModelUpdateAllowed AllowSpeechModelUpdateValue = 1
)

// String returns the AllowSpeechModelUpdateValue constant's name, or its numeric form
// when the value is not a known constant.
func (e AllowSpeechModelUpdateValue) String() string {
	switch e {
	case AllowSpeechModelUpdateNotAllowed:
		return "AllowSpeechModelUpdateNotAllowed"
	case AllowSpeechModelUpdateAllowed:
		return "AllowSpeechModelUpdateAllowed"
	default:
		return fmt.Sprintf("AllowSpeechModelUpdateValue(%d)", int64(e))
	}
}
