// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package tenantdefinedtelemetry

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// TenantDefinedTelemetry exposes LCRUD operations over the TenantDefinedTelemetry Policy area nodes.
type TenantDefinedTelemetry struct {
	c client.Client
}

// NewTenantDefinedTelemetry returns a TenantDefinedTelemetry service backed by transport c.
func NewTenantDefinedTelemetry(c client.Client) *TenantDefinedTelemetry {
	return &TenantDefinedTelemetry{c: c}
}
