// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package applicationdefaults

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetDefaultAssociationsConfiguration reads ./Device/Vendor/MSFT/Policy/Config/ApplicationDefaults/DefaultAssociationsConfiguration.
// This policy allows an administrator to set default file type and protocol associations. When
// set, default associations will be applied on sign-in to the PC. The association file can be
// created using the DISM tool (dism /online /export-defaultappassociations:appassoc.xml). The file
// can be further edited by adding attributes to control how often associations are applied by the
// policy. The file then needs to be base64 encoded before being added to SyncML. If policy is
// enabled and the client machine is Azure Active Directory joined, the associations assigned in
// SyncML will be processed and default associations will be applied.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *ApplicationDefaults) GetDefaultAssociationsConfiguration(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIDefaultAssociationsConfiguration)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateDefaultAssociationsConfiguration creates ./Device/Vendor/MSFT/Policy/Config/ApplicationDefaults/DefaultAssociationsConfiguration.
// This policy allows an administrator to set default file type and protocol associations. When
// set, default associations will be applied on sign-in to the PC. The association file can be
// created using the DISM tool (dism /online /export-defaultappassociations:appassoc.xml). The file
// can be further edited by adding attributes to control how often associations are applied by the
// policy. The file then needs to be base64 encoded before being added to SyncML. If policy is
// enabled and the client machine is Azure Active Directory joined, the associations assigned in
// SyncML will be processed and default associations will be applied.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *ApplicationDefaults) CreateDefaultAssociationsConfiguration(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIDefaultAssociationsConfiguration, client.Chr(value))
}

// UpdateDefaultAssociationsConfiguration updates ./Device/Vendor/MSFT/Policy/Config/ApplicationDefaults/DefaultAssociationsConfiguration.
// This policy allows an administrator to set default file type and protocol associations. When
// set, default associations will be applied on sign-in to the PC. The association file can be
// created using the DISM tool (dism /online /export-defaultappassociations:appassoc.xml). The file
// can be further edited by adding attributes to control how often associations are applied by the
// policy. The file then needs to be base64 encoded before being added to SyncML. If policy is
// enabled and the client machine is Azure Active Directory joined, the associations assigned in
// SyncML will be processed and default associations will be applied.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *ApplicationDefaults) UpdateDefaultAssociationsConfiguration(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIDefaultAssociationsConfiguration, client.Chr(value))
}

// DeleteDefaultAssociationsConfiguration deletes ./Device/Vendor/MSFT/Policy/Config/ApplicationDefaults/DefaultAssociationsConfiguration.
// This policy allows an administrator to set default file type and protocol associations. When
// set, default associations will be applied on sign-in to the PC. The association file can be
// created using the DISM tool (dism /online /export-defaultappassociations:appassoc.xml). The file
// can be further edited by adding attributes to control how often associations are applied by the
// policy. The file then needs to be base64 encoded before being added to SyncML. If policy is
// enabled and the client machine is Azure Active Directory joined, the associations assigned in
// SyncML will be processed and default associations will be applied.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *ApplicationDefaults) DeleteDefaultAssociationsConfiguration(ctx context.Context) error {
	return s.c.Delete(ctx, URIDefaultAssociationsConfiguration)
}

// GetEnableAppUriHandlers reads ./Device/Vendor/MSFT/Policy/Config/ApplicationDefaults/EnableAppUriHandlers.
// Enables web-to-app linking, which allows apps to be launched with a http(s) URI
//
// Default: 1.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *ApplicationDefaults) GetEnableAppUriHandlers(ctx context.Context) (EnableAppUriHandlersValue, error) {
	v, err := s.c.Get(ctx, URIEnableAppUriHandlers)
	if err != nil {
		return 0, err
	}
	n, err := v.Int()
	return EnableAppUriHandlersValue(n), err
}

// CreateEnableAppUriHandlers creates ./Device/Vendor/MSFT/Policy/Config/ApplicationDefaults/EnableAppUriHandlers.
// Enables web-to-app linking, which allows apps to be launched with a http(s) URI
//
// Default: 1.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *ApplicationDefaults) CreateEnableAppUriHandlers(ctx context.Context, value EnableAppUriHandlersValue) error {
	return s.c.Add(ctx, URIEnableAppUriHandlers, client.Int(int64(value)))
}

// UpdateEnableAppUriHandlers updates ./Device/Vendor/MSFT/Policy/Config/ApplicationDefaults/EnableAppUriHandlers.
// Enables web-to-app linking, which allows apps to be launched with a http(s) URI
//
// Default: 1.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *ApplicationDefaults) UpdateEnableAppUriHandlers(ctx context.Context, value EnableAppUriHandlersValue) error {
	return s.c.Replace(ctx, URIEnableAppUriHandlers, client.Int(int64(value)))
}

// DeleteEnableAppUriHandlers deletes ./Device/Vendor/MSFT/Policy/Config/ApplicationDefaults/EnableAppUriHandlers.
// Enables web-to-app linking, which allows apps to be launched with a http(s) URI
//
// Default: 1.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *ApplicationDefaults) DeleteEnableAppUriHandlers(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableAppUriHandlers)
}
