// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package vpnv2_user binds the VPNv2 configuration service provider
// (./User/Vendor/MSFT/VPNv2).
//
// Generated from the February 2026 DDF v2 release.
package vpnv2_user
