// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_appxruntime

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetAppxRuntimeApplicationContentUriRules reads ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeApplicationContentUriRules.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) GetAppxRuntimeApplicationContentUriRules(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIAppxRuntimeApplicationContentUriRules)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateAppxRuntimeApplicationContentUriRules creates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeApplicationContentUriRules.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) CreateAppxRuntimeApplicationContentUriRules(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIAppxRuntimeApplicationContentUriRules, client.Chr(value))
}

// UpdateAppxRuntimeApplicationContentUriRules updates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeApplicationContentUriRules.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) UpdateAppxRuntimeApplicationContentUriRules(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIAppxRuntimeApplicationContentUriRules, client.Chr(value))
}

// DeleteAppxRuntimeApplicationContentUriRules deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeApplicationContentUriRules.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) DeleteAppxRuntimeApplicationContentUriRules(ctx context.Context) error {
	return s.c.Delete(ctx, URIAppxRuntimeApplicationContentUriRules)
}

// GetAppxRuntimeBlockFileElevation reads ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) GetAppxRuntimeBlockFileElevation(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIAppxRuntimeBlockFileElevation)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateAppxRuntimeBlockFileElevation creates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) CreateAppxRuntimeBlockFileElevation(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIAppxRuntimeBlockFileElevation, client.Chr(value))
}

// UpdateAppxRuntimeBlockFileElevation updates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) UpdateAppxRuntimeBlockFileElevation(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIAppxRuntimeBlockFileElevation, client.Chr(value))
}

// DeleteAppxRuntimeBlockFileElevation deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) DeleteAppxRuntimeBlockFileElevation(ctx context.Context) error {
	return s.c.Delete(ctx, URIAppxRuntimeBlockFileElevation)
}

// GetAppxRuntimeBlockHostedAppAccessWinRT reads ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockHostedAppAccessWinRT.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) GetAppxRuntimeBlockHostedAppAccessWinRT(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIAppxRuntimeBlockHostedAppAccessWinRT)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateAppxRuntimeBlockHostedAppAccessWinRT creates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockHostedAppAccessWinRT.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) CreateAppxRuntimeBlockHostedAppAccessWinRT(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIAppxRuntimeBlockHostedAppAccessWinRT, client.Chr(value))
}

// UpdateAppxRuntimeBlockHostedAppAccessWinRT updates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockHostedAppAccessWinRT.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) UpdateAppxRuntimeBlockHostedAppAccessWinRT(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIAppxRuntimeBlockHostedAppAccessWinRT, client.Chr(value))
}

// DeleteAppxRuntimeBlockHostedAppAccessWinRT deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockHostedAppAccessWinRT.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) DeleteAppxRuntimeBlockHostedAppAccessWinRT(ctx context.Context) error {
	return s.c.Delete(ctx, URIAppxRuntimeBlockHostedAppAccessWinRT)
}

// GetAppxRuntimeBlockProtocolElevation reads ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) GetAppxRuntimeBlockProtocolElevation(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIAppxRuntimeBlockProtocolElevation)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateAppxRuntimeBlockProtocolElevation creates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) CreateAppxRuntimeBlockProtocolElevation(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIAppxRuntimeBlockProtocolElevation, client.Chr(value))
}

// UpdateAppxRuntimeBlockProtocolElevation updates ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) UpdateAppxRuntimeBlockProtocolElevation(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIAppxRuntimeBlockProtocolElevation, client.Chr(value))
}

// DeleteAppxRuntimeBlockProtocolElevation deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXAppXRuntime) DeleteAppxRuntimeBlockProtocolElevation(ctx context.Context) error {
	return s.c.Delete(ctx, URIAppxRuntimeBlockProtocolElevation)
}
