// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_externalboot binds the ADMX_ExternalBoot Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_ExternalBoot).
//
// Generated from the February 2026 DDF v2 release.
package admx_externalboot
