// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package printers binds the Printers Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/Printers).
//
// Generated from the February 2026 DDF v2 release.
package printers
