// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package printers

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Printers exposes LCRUD operations over the Printers Policy area nodes.
type Printers struct {
	c client.Client
}

// NewPrinters returns a Printers service backed by transport c.
func NewPrinters(c client.Client) *Printers {
	return &Printers{c: c}
}
