// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package remotedesktop

// OMA-URIs of the RemoteDesktop nodes addressed by this package.
const (
	// the RemoteDesktop root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/RemoteDesktop"
	// the LoadAadCredKeyFromProfile node.
	URILoadAadCredKeyFromProfile = "./Device/Vendor/MSFT/Policy/Config/RemoteDesktop/LoadAadCredKeyFromProfile"
)
