// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package remoteassistance

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetCustomizeWarningMessages reads ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/CustomizeWarningMessages.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) GetCustomizeWarningMessages(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URICustomizeWarningMessages)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateCustomizeWarningMessages creates ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/CustomizeWarningMessages.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) CreateCustomizeWarningMessages(ctx context.Context, value string) error {
	return s.c.Add(ctx, URICustomizeWarningMessages, client.Chr(value))
}

// UpdateCustomizeWarningMessages updates ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/CustomizeWarningMessages.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) UpdateCustomizeWarningMessages(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URICustomizeWarningMessages, client.Chr(value))
}

// DeleteCustomizeWarningMessages deletes ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/CustomizeWarningMessages.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) DeleteCustomizeWarningMessages(ctx context.Context) error {
	return s.c.Delete(ctx, URICustomizeWarningMessages)
}

// GetSessionLogging reads ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SessionLogging.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) GetSessionLogging(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URISessionLogging)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateSessionLogging creates ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SessionLogging.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) CreateSessionLogging(ctx context.Context, value string) error {
	return s.c.Add(ctx, URISessionLogging, client.Chr(value))
}

// UpdateSessionLogging updates ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SessionLogging.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) UpdateSessionLogging(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URISessionLogging, client.Chr(value))
}

// DeleteSessionLogging deletes ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SessionLogging.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) DeleteSessionLogging(ctx context.Context) error {
	return s.c.Delete(ctx, URISessionLogging)
}

// GetSolicitedRemoteAssistance reads ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SolicitedRemoteAssistance.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) GetSolicitedRemoteAssistance(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URISolicitedRemoteAssistance)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateSolicitedRemoteAssistance creates ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SolicitedRemoteAssistance.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) CreateSolicitedRemoteAssistance(ctx context.Context, value string) error {
	return s.c.Add(ctx, URISolicitedRemoteAssistance, client.Chr(value))
}

// UpdateSolicitedRemoteAssistance updates ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SolicitedRemoteAssistance.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) UpdateSolicitedRemoteAssistance(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URISolicitedRemoteAssistance, client.Chr(value))
}

// DeleteSolicitedRemoteAssistance deletes ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SolicitedRemoteAssistance.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) DeleteSolicitedRemoteAssistance(ctx context.Context) error {
	return s.c.Delete(ctx, URISolicitedRemoteAssistance)
}

// GetUnsolicitedRemoteAssistance reads ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/UnsolicitedRemoteAssistance.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) GetUnsolicitedRemoteAssistance(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIUnsolicitedRemoteAssistance)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateUnsolicitedRemoteAssistance creates ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/UnsolicitedRemoteAssistance.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) CreateUnsolicitedRemoteAssistance(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIUnsolicitedRemoteAssistance, client.Chr(value))
}

// UpdateUnsolicitedRemoteAssistance updates ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/UnsolicitedRemoteAssistance.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) UpdateUnsolicitedRemoteAssistance(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIUnsolicitedRemoteAssistance, client.Chr(value))
}

// DeleteUnsolicitedRemoteAssistance deletes ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/UnsolicitedRemoteAssistance.
//
// Supported from OS build 10.0.15063 (CSP v5.0).
func (s *RemoteAssistance) DeleteUnsolicitedRemoteAssistance(ctx context.Context) error {
	return s.c.Delete(ctx, URIUnsolicitedRemoteAssistance)
}
