// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package desktop

// OMA-URIs of the Desktop nodes addressed by this package.
const (
	// the Desktop root node.
	URIRoot = "./User/Vendor/MSFT/Policy/Config/Desktop"
	// the PreventUserRedirectionOfProfileFolders node.
	URIPreventUserRedirectionOfProfileFolders = "./User/Vendor/MSFT/Policy/Config/Desktop/PreventUserRedirectionOfProfileFolders"
)
