// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_wcm binds the ADMX_WCM Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_WCM).
//
// Generated from the February 2026 DDF v2 release.
package admx_wcm
