// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package experience

// OMA-URIs of the Experience nodes addressed by this package.
const (
	// the Experience root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/Experience"
	// the AllowClipboardHistory node.
	URIAllowClipboardHistory = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowClipboardHistory"
	// the AllowCopyPaste node.
	URIAllowCopyPaste = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowCopyPaste"
	// the AllowCortana node.
	URIAllowCortana = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowCortana"
	// the AllowDeviceDiscovery node.
	URIAllowDeviceDiscovery = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowDeviceDiscovery"
	// the AllowFindMyDevice node.
	URIAllowFindMyDevice = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowFindMyDevice"
	// the AllowManualMDMUnenrollment node.
	URIAllowManualMDMUnenrollment = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowManualMDMUnenrollment"
	// the AllowSIMErrorDialogPromptWhenNoSIM node.
	URIAllowSIMErrorDialogPromptWhenNoSIM = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowSIMErrorDialogPromptWhenNoSIM"
	// the AllowSaveAsOfOfficeFiles node.
	URIAllowSaveAsOfOfficeFiles = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowSaveAsOfOfficeFiles"
	// the AllowScreenCapture node.
	URIAllowScreenCapture = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowScreenCapture"
	// the AllowSharingOfOfficeFiles node.
	URIAllowSharingOfOfficeFiles = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowSharingOfOfficeFiles"
	// the AllowSyncMySettings node.
	URIAllowSyncMySettings = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowSyncMySettings"
	// the AllowTaskSwitcher node.
	URIAllowTaskSwitcher = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowTaskSwitcher"
	// the AllowVoiceRecording node.
	URIAllowVoiceRecording = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowVoiceRecording"
	// the AllowWindowsConsumerFeatures node.
	URIAllowWindowsConsumerFeatures = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowWindowsConsumerFeatures"
	// the AllowWindowsTips node.
	URIAllowWindowsTips = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowWindowsTips"
	// the ConfigureChatIcon node.
	URIConfigureChatIcon = "./Device/Vendor/MSFT/Policy/Config/Experience/ConfigureChatIcon"
	// the DisableCloudOptimizedContent node.
	URIDisableCloudOptimizedContent = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableCloudOptimizedContent"
	// the DisableConsumerAccountStateContent node.
	URIDisableConsumerAccountStateContent = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableConsumerAccountStateContent"
	// the DisableInlineCompose node.
	URIDisableInlineCompose = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableInlineCompose"
	// the DisableShareAppPromotions node.
	URIDisableShareAppPromotions = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableShareAppPromotions"
	// the DisableTextTranslation node.
	URIDisableTextTranslation = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableTextTranslation"
	// the DoNotShowFeedbackNotifications node.
	URIDoNotShowFeedbackNotifications = "./Device/Vendor/MSFT/Policy/Config/Experience/DoNotShowFeedbackNotifications"
	// the DoNotSyncBrowserSettings node.
	URIDoNotSyncBrowserSettings = "./Device/Vendor/MSFT/Policy/Config/Experience/DoNotSyncBrowserSettings"
	// the PreventUsersFromTurningOnBrowserSyncing node.
	URIPreventUsersFromTurningOnBrowserSyncing = "./Device/Vendor/MSFT/Policy/Config/Experience/PreventUsersFromTurningOnBrowserSyncing"
	// the ShowLockOnUserTile node.
	URIShowLockOnUserTile = "./Device/Vendor/MSFT/Policy/Config/Experience/ShowLockOnUserTile"
)
