// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package office_user

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// OfficeUser exposes LCRUD operations over the Office CSP nodes.
type OfficeUser struct {
	c client.Client
}

// NewOfficeUser returns a OfficeUser service backed by transport c.
func NewOfficeUser(c client.Client) *OfficeUser {
	return &OfficeUser{c: c}
}
