// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package taskmanager

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetAllowEndTask reads ./Device/Vendor/MSFT/Policy/Config/TaskManager/AllowEndTask.
// This setting determines whether non-administrators can use Task Manager to end tasks - enabled
// (1) or disabled (0). Default: enabled
//
// Default: 1.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *TaskManager) GetAllowEndTask(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIAllowEndTask)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateAllowEndTask creates ./Device/Vendor/MSFT/Policy/Config/TaskManager/AllowEndTask.
// This setting determines whether non-administrators can use Task Manager to end tasks - enabled
// (1) or disabled (0). Default: enabled
//
// Default: 1.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *TaskManager) CreateAllowEndTask(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIAllowEndTask, client.Int(value))
}

// UpdateAllowEndTask updates ./Device/Vendor/MSFT/Policy/Config/TaskManager/AllowEndTask.
// This setting determines whether non-administrators can use Task Manager to end tasks - enabled
// (1) or disabled (0). Default: enabled
//
// Default: 1.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *TaskManager) UpdateAllowEndTask(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIAllowEndTask, client.Int(value))
}

// DeleteAllowEndTask deletes ./Device/Vendor/MSFT/Policy/Config/TaskManager/AllowEndTask.
// This setting determines whether non-administrators can use Task Manager to end tasks - enabled
// (1) or disabled (0). Default: enabled
//
// Default: 1.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *TaskManager) DeleteAllowEndTask(ctx context.Context) error {
	return s.c.Delete(ctx, URIAllowEndTask)
}
