// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package kerberos

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Kerberos exposes LCRUD operations over the Kerberos Policy area nodes.
type Kerberos struct {
	c client.Client
}

// NewKerberos returns a Kerberos service backed by transport c.
func NewKerberos(c client.Client) *Kerberos {
	return &Kerberos{c: c}
}
