// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_power_user

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXPowerUser exposes LCRUD operations over the ADMX_Power Policy area nodes.
type ADMXPowerUser struct {
	c client.Client
}

// NewADMXPowerUser returns a ADMXPowerUser service backed by transport c.
func NewADMXPowerUser(c client.Client) *ADMXPowerUser {
	return &ADMXPowerUser{c: c}
}
