// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_scripts

// OMA-URIs of the ADMX_Scripts nodes addressed by this package.
const (
	// the ADMX_Scripts root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_Scripts"
	// the Allow_Logon_Script_NetbiosDisabled node.
	URIAllowLogonScriptNetbiosDisabled = "./Device/Vendor/MSFT/Policy/Config/ADMX_Scripts/Allow_Logon_Script_NetbiosDisabled"
	// the MaxGPOScriptWaitPolicy node.
	URIMaxGPOScriptWaitPolicy = "./Device/Vendor/MSFT/Policy/Config/ADMX_Scripts/MaxGPOScriptWaitPolicy"
	// the Run_Computer_PS_Scripts_First node.
	URIRunComputerPSScriptsFirst = "./Device/Vendor/MSFT/Policy/Config/ADMX_Scripts/Run_Computer_PS_Scripts_First"
	// the Run_Logon_Script_Sync_2 node.
	URIRunLogonScriptSync2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_Scripts/Run_Logon_Script_Sync_2"
	// the Run_Shutdown_Script_Visible node.
	URIRunShutdownScriptVisible = "./Device/Vendor/MSFT/Policy/Config/ADMX_Scripts/Run_Shutdown_Script_Visible"
	// the Run_Startup_Script_Sync node.
	URIRunStartupScriptSync = "./Device/Vendor/MSFT/Policy/Config/ADMX_Scripts/Run_Startup_Script_Sync"
	// the Run_Startup_Script_Visible node.
	URIRunStartupScriptVisible = "./Device/Vendor/MSFT/Policy/Config/ADMX_Scripts/Run_Startup_Script_Visible"
	// the Run_User_PS_Scripts_First node.
	URIRunUserPSScriptsFirst = "./Device/Vendor/MSFT/Policy/Config/ADMX_Scripts/Run_User_PS_Scripts_First"
)
