// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package storage binds the Storage Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/Storage).
//
// Generated from the February 2026 DDF v2 release.
package storage
