// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_wdi

// OMA-URIs of the ADMX_WDI nodes addressed by this package.
const (
	// the ADMX_WDI root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_WDI"
	// the WdiDpsScenarioDataSizeLimitPolicy node.
	URIWdiDpsScenarioDataSizeLimitPolicy = "./Device/Vendor/MSFT/Policy/Config/ADMX_WDI/WdiDpsScenarioDataSizeLimitPolicy"
	// the WdiDpsScenarioExecutionPolicy node.
	URIWdiDpsScenarioExecutionPolicy = "./Device/Vendor/MSFT/Policy/Config/ADMX_WDI/WdiDpsScenarioExecutionPolicy"
)
