// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_wininit binds the ADMX_WinInit Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_WinInit).
//
// Generated from the February 2026 DDF v2 release.
package admx_wininit
