// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_logon

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXLogon exposes LCRUD operations over the ADMX_Logon Policy area nodes.
type ADMXLogon struct {
	c client.Client
}

// NewADMXLogon returns a ADMXLogon service backed by transport c.
func NewADMXLogon(c client.Client) *ADMXLogon {
	return &ADMXLogon{c: c}
}
