// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_logon binds the ADMX_Logon Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_Logon).
//
// Generated from the February 2026 DDF v2 release.
package admx_logon
