// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_eventviewer binds the ADMX_EventViewer Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_EventViewer).
//
// Generated from the February 2026 DDF v2 release.
package admx_eventviewer
