// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_grouppolicy

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXGroupPolicy exposes LCRUD operations over the ADMX_GroupPolicy Policy area nodes.
type ADMXGroupPolicy struct {
	c client.Client
}

// NewADMXGroupPolicy returns a ADMXGroupPolicy service backed by transport c.
func NewADMXGroupPolicy(c client.Client) *ADMXGroupPolicy {
	return &ADMXGroupPolicy{c: c}
}
