// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package games

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Games exposes LCRUD operations over the Games Policy area nodes.
type Games struct {
	c client.Client
}

// NewGames returns a Games service backed by transport c.
func NewGames(c client.Client) *Games {
	return &Games{c: c}
}
