// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_removablestorage_user

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXRemovableStorageUser exposes LCRUD operations over the ADMX_RemovableStorage Policy area nodes.
type ADMXRemovableStorageUser struct {
	c client.Client
}

// NewADMXRemovableStorageUser returns a ADMXRemovableStorageUser service backed by transport c.
func NewADMXRemovableStorageUser(c client.Client) *ADMXRemovableStorageUser {
	return &ADMXRemovableStorageUser{c: c}
}
