// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_removablestorage_user binds the ADMX_RemovableStorage Policy CSP area
// (./User/Vendor/MSFT/Policy/Config/ADMX_RemovableStorage).
//
// Generated from the February 2026 DDF v2 release.
package admx_removablestorage_user
