// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_netlogon

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetNetlogonAddressLookupOnPingBehavior reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AddressLookupOnPingBehavior.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonAddressLookupOnPingBehavior(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonAddressLookupOnPingBehavior)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonAddressLookupOnPingBehavior creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AddressLookupOnPingBehavior.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonAddressLookupOnPingBehavior(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonAddressLookupOnPingBehavior, client.Chr(value))
}

// UpdateNetlogonAddressLookupOnPingBehavior updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AddressLookupOnPingBehavior.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonAddressLookupOnPingBehavior(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonAddressLookupOnPingBehavior, client.Chr(value))
}

// DeleteNetlogonAddressLookupOnPingBehavior deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AddressLookupOnPingBehavior.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonAddressLookupOnPingBehavior(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonAddressLookupOnPingBehavior)
}

// GetNetlogonAddressTypeReturned reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AddressTypeReturned.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonAddressTypeReturned(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonAddressTypeReturned)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonAddressTypeReturned creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AddressTypeReturned.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonAddressTypeReturned(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonAddressTypeReturned, client.Chr(value))
}

// UpdateNetlogonAddressTypeReturned updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AddressTypeReturned.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonAddressTypeReturned(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonAddressTypeReturned, client.Chr(value))
}

// DeleteNetlogonAddressTypeReturned deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AddressTypeReturned.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonAddressTypeReturned(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonAddressTypeReturned)
}

// GetNetlogonAllowDnsSuffixSearch reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowDnsSuffixSearch.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonAllowDnsSuffixSearch(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonAllowDnsSuffixSearch)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonAllowDnsSuffixSearch creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowDnsSuffixSearch.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonAllowDnsSuffixSearch(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonAllowDnsSuffixSearch, client.Chr(value))
}

// UpdateNetlogonAllowDnsSuffixSearch updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowDnsSuffixSearch.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonAllowDnsSuffixSearch(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonAllowDnsSuffixSearch, client.Chr(value))
}

// DeleteNetlogonAllowDnsSuffixSearch deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowDnsSuffixSearch.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonAllowDnsSuffixSearch(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonAllowDnsSuffixSearch)
}

// GetNetlogonAllowNT4Crypto reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowNT4Crypto.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonAllowNT4Crypto(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonAllowNT4Crypto)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonAllowNT4Crypto creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowNT4Crypto.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonAllowNT4Crypto(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonAllowNT4Crypto, client.Chr(value))
}

// UpdateNetlogonAllowNT4Crypto updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowNT4Crypto.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonAllowNT4Crypto(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonAllowNT4Crypto, client.Chr(value))
}

// DeleteNetlogonAllowNT4Crypto deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowNT4Crypto.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonAllowNT4Crypto(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonAllowNT4Crypto)
}

// GetNetlogonAllowSingleLabelDnsDomain reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowSingleLabelDnsDomain.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonAllowSingleLabelDnsDomain(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonAllowSingleLabelDnsDomain)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonAllowSingleLabelDnsDomain creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowSingleLabelDnsDomain.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonAllowSingleLabelDnsDomain(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonAllowSingleLabelDnsDomain, client.Chr(value))
}

// UpdateNetlogonAllowSingleLabelDnsDomain updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowSingleLabelDnsDomain.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonAllowSingleLabelDnsDomain(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonAllowSingleLabelDnsDomain, client.Chr(value))
}

// DeleteNetlogonAllowSingleLabelDnsDomain deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AllowSingleLabelDnsDomain.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonAllowSingleLabelDnsDomain(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonAllowSingleLabelDnsDomain)
}

// GetNetlogonAutoSiteCoverage reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AutoSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonAutoSiteCoverage(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonAutoSiteCoverage)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonAutoSiteCoverage creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AutoSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonAutoSiteCoverage(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonAutoSiteCoverage, client.Chr(value))
}

// UpdateNetlogonAutoSiteCoverage updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AutoSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonAutoSiteCoverage(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonAutoSiteCoverage, client.Chr(value))
}

// DeleteNetlogonAutoSiteCoverage deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AutoSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonAutoSiteCoverage(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonAutoSiteCoverage)
}

// GetNetlogonAvoidFallbackNetbiosDiscovery reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AvoidFallbackNetbiosDiscovery.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonAvoidFallbackNetbiosDiscovery(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonAvoidFallbackNetbiosDiscovery)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonAvoidFallbackNetbiosDiscovery creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AvoidFallbackNetbiosDiscovery.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonAvoidFallbackNetbiosDiscovery(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonAvoidFallbackNetbiosDiscovery, client.Chr(value))
}

// UpdateNetlogonAvoidFallbackNetbiosDiscovery updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AvoidFallbackNetbiosDiscovery.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonAvoidFallbackNetbiosDiscovery(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonAvoidFallbackNetbiosDiscovery, client.Chr(value))
}

// DeleteNetlogonAvoidFallbackNetbiosDiscovery deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AvoidFallbackNetbiosDiscovery.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonAvoidFallbackNetbiosDiscovery(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonAvoidFallbackNetbiosDiscovery)
}

// GetNetlogonAvoidPdcOnWan reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AvoidPdcOnWan.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonAvoidPdcOnWan(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonAvoidPdcOnWan)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonAvoidPdcOnWan creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AvoidPdcOnWan.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonAvoidPdcOnWan(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonAvoidPdcOnWan, client.Chr(value))
}

// UpdateNetlogonAvoidPdcOnWan updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AvoidPdcOnWan.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonAvoidPdcOnWan(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonAvoidPdcOnWan, client.Chr(value))
}

// DeleteNetlogonAvoidPdcOnWan deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_AvoidPdcOnWan.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonAvoidPdcOnWan(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonAvoidPdcOnWan)
}

// GetNetlogonBackgroundRetryInitialPeriod reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryInitialPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonBackgroundRetryInitialPeriod(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonBackgroundRetryInitialPeriod)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonBackgroundRetryInitialPeriod creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryInitialPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonBackgroundRetryInitialPeriod(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonBackgroundRetryInitialPeriod, client.Chr(value))
}

// UpdateNetlogonBackgroundRetryInitialPeriod updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryInitialPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonBackgroundRetryInitialPeriod(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonBackgroundRetryInitialPeriod, client.Chr(value))
}

// DeleteNetlogonBackgroundRetryInitialPeriod deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryInitialPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonBackgroundRetryInitialPeriod(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonBackgroundRetryInitialPeriod)
}

// GetNetlogonBackgroundRetryMaximumPeriod reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryMaximumPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonBackgroundRetryMaximumPeriod(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonBackgroundRetryMaximumPeriod)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonBackgroundRetryMaximumPeriod creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryMaximumPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonBackgroundRetryMaximumPeriod(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonBackgroundRetryMaximumPeriod, client.Chr(value))
}

// UpdateNetlogonBackgroundRetryMaximumPeriod updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryMaximumPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonBackgroundRetryMaximumPeriod(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonBackgroundRetryMaximumPeriod, client.Chr(value))
}

// DeleteNetlogonBackgroundRetryMaximumPeriod deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryMaximumPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonBackgroundRetryMaximumPeriod(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonBackgroundRetryMaximumPeriod)
}

// GetNetlogonBackgroundRetryQuitTime reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryQuitTime.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonBackgroundRetryQuitTime(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonBackgroundRetryQuitTime)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonBackgroundRetryQuitTime creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryQuitTime.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonBackgroundRetryQuitTime(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonBackgroundRetryQuitTime, client.Chr(value))
}

// UpdateNetlogonBackgroundRetryQuitTime updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryQuitTime.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonBackgroundRetryQuitTime(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonBackgroundRetryQuitTime, client.Chr(value))
}

// DeleteNetlogonBackgroundRetryQuitTime deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundRetryQuitTime.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonBackgroundRetryQuitTime(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonBackgroundRetryQuitTime)
}

// GetNetlogonBackgroundSuccessfulRefreshPeriod reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundSuccessfulRefreshPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonBackgroundSuccessfulRefreshPeriod(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonBackgroundSuccessfulRefreshPeriod)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonBackgroundSuccessfulRefreshPeriod creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundSuccessfulRefreshPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonBackgroundSuccessfulRefreshPeriod(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonBackgroundSuccessfulRefreshPeriod, client.Chr(value))
}

// UpdateNetlogonBackgroundSuccessfulRefreshPeriod updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundSuccessfulRefreshPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonBackgroundSuccessfulRefreshPeriod(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonBackgroundSuccessfulRefreshPeriod, client.Chr(value))
}

// DeleteNetlogonBackgroundSuccessfulRefreshPeriod deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_BackgroundSuccessfulRefreshPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonBackgroundSuccessfulRefreshPeriod(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonBackgroundSuccessfulRefreshPeriod)
}

// GetNetlogonDebugFlag reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DebugFlag.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonDebugFlag(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonDebugFlag)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonDebugFlag creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DebugFlag.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonDebugFlag(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonDebugFlag, client.Chr(value))
}

// UpdateNetlogonDebugFlag updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DebugFlag.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonDebugFlag(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonDebugFlag, client.Chr(value))
}

// DeleteNetlogonDebugFlag deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DebugFlag.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonDebugFlag(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonDebugFlag)
}

// GetNetlogonDnsAvoidRegisterRecords reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsAvoidRegisterRecords.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonDnsAvoidRegisterRecords(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonDnsAvoidRegisterRecords)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonDnsAvoidRegisterRecords creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsAvoidRegisterRecords.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonDnsAvoidRegisterRecords(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonDnsAvoidRegisterRecords, client.Chr(value))
}

// UpdateNetlogonDnsAvoidRegisterRecords updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsAvoidRegisterRecords.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonDnsAvoidRegisterRecords(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonDnsAvoidRegisterRecords, client.Chr(value))
}

// DeleteNetlogonDnsAvoidRegisterRecords deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsAvoidRegisterRecords.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonDnsAvoidRegisterRecords(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonDnsAvoidRegisterRecords)
}

// GetNetlogonDnsRefreshInterval reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsRefreshInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonDnsRefreshInterval(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonDnsRefreshInterval)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonDnsRefreshInterval creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsRefreshInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonDnsRefreshInterval(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonDnsRefreshInterval, client.Chr(value))
}

// UpdateNetlogonDnsRefreshInterval updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsRefreshInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonDnsRefreshInterval(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonDnsRefreshInterval, client.Chr(value))
}

// DeleteNetlogonDnsRefreshInterval deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsRefreshInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonDnsRefreshInterval(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonDnsRefreshInterval)
}

// GetNetlogonDnsSrvRecordUseLowerCaseHostNames reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsSrvRecordUseLowerCaseHostNames.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonDnsSrvRecordUseLowerCaseHostNames(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonDnsSrvRecordUseLowerCaseHostNames)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonDnsSrvRecordUseLowerCaseHostNames creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsSrvRecordUseLowerCaseHostNames.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonDnsSrvRecordUseLowerCaseHostNames(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonDnsSrvRecordUseLowerCaseHostNames, client.Chr(value))
}

// UpdateNetlogonDnsSrvRecordUseLowerCaseHostNames updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsSrvRecordUseLowerCaseHostNames.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonDnsSrvRecordUseLowerCaseHostNames(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonDnsSrvRecordUseLowerCaseHostNames, client.Chr(value))
}

// DeleteNetlogonDnsSrvRecordUseLowerCaseHostNames deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsSrvRecordUseLowerCaseHostNames.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonDnsSrvRecordUseLowerCaseHostNames(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonDnsSrvRecordUseLowerCaseHostNames)
}

// GetNetlogonDnsTtl reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsTtl.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonDnsTtl(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonDnsTtl)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonDnsTtl creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsTtl.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonDnsTtl(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonDnsTtl, client.Chr(value))
}

// UpdateNetlogonDnsTtl updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsTtl.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonDnsTtl(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonDnsTtl, client.Chr(value))
}

// DeleteNetlogonDnsTtl deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_DnsTtl.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonDnsTtl(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonDnsTtl)
}

// GetNetlogonExpectedDialupDelay reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ExpectedDialupDelay.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonExpectedDialupDelay(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonExpectedDialupDelay)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonExpectedDialupDelay creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ExpectedDialupDelay.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonExpectedDialupDelay(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonExpectedDialupDelay, client.Chr(value))
}

// UpdateNetlogonExpectedDialupDelay updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ExpectedDialupDelay.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonExpectedDialupDelay(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonExpectedDialupDelay, client.Chr(value))
}

// DeleteNetlogonExpectedDialupDelay deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ExpectedDialupDelay.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonExpectedDialupDelay(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonExpectedDialupDelay)
}

// GetNetlogonForceRediscoveryInterval reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ForceRediscoveryInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonForceRediscoveryInterval(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonForceRediscoveryInterval)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonForceRediscoveryInterval creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ForceRediscoveryInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonForceRediscoveryInterval(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonForceRediscoveryInterval, client.Chr(value))
}

// UpdateNetlogonForceRediscoveryInterval updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ForceRediscoveryInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonForceRediscoveryInterval(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonForceRediscoveryInterval, client.Chr(value))
}

// DeleteNetlogonForceRediscoveryInterval deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ForceRediscoveryInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonForceRediscoveryInterval(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonForceRediscoveryInterval)
}

// GetNetlogonGcSiteCoverage reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_GcSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonGcSiteCoverage(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonGcSiteCoverage)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonGcSiteCoverage creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_GcSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonGcSiteCoverage(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonGcSiteCoverage, client.Chr(value))
}

// UpdateNetlogonGcSiteCoverage updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_GcSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonGcSiteCoverage(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonGcSiteCoverage, client.Chr(value))
}

// DeleteNetlogonGcSiteCoverage deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_GcSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonGcSiteCoverage(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonGcSiteCoverage)
}

// GetNetlogonIgnoreIncomingMailslotMessages reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_IgnoreIncomingMailslotMessages.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonIgnoreIncomingMailslotMessages(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonIgnoreIncomingMailslotMessages)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonIgnoreIncomingMailslotMessages creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_IgnoreIncomingMailslotMessages.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonIgnoreIncomingMailslotMessages(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonIgnoreIncomingMailslotMessages, client.Chr(value))
}

// UpdateNetlogonIgnoreIncomingMailslotMessages updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_IgnoreIncomingMailslotMessages.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonIgnoreIncomingMailslotMessages(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonIgnoreIncomingMailslotMessages, client.Chr(value))
}

// DeleteNetlogonIgnoreIncomingMailslotMessages deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_IgnoreIncomingMailslotMessages.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonIgnoreIncomingMailslotMessages(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonIgnoreIncomingMailslotMessages)
}

// GetNetlogonLdapSrvPriority reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_LdapSrvPriority.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonLdapSrvPriority(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonLdapSrvPriority)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonLdapSrvPriority creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_LdapSrvPriority.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonLdapSrvPriority(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonLdapSrvPriority, client.Chr(value))
}

// UpdateNetlogonLdapSrvPriority updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_LdapSrvPriority.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonLdapSrvPriority(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonLdapSrvPriority, client.Chr(value))
}

// DeleteNetlogonLdapSrvPriority deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_LdapSrvPriority.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonLdapSrvPriority(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonLdapSrvPriority)
}

// GetNetlogonLdapSrvWeight reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_LdapSrvWeight.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonLdapSrvWeight(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonLdapSrvWeight)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonLdapSrvWeight creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_LdapSrvWeight.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonLdapSrvWeight(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonLdapSrvWeight, client.Chr(value))
}

// UpdateNetlogonLdapSrvWeight updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_LdapSrvWeight.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonLdapSrvWeight(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonLdapSrvWeight, client.Chr(value))
}

// DeleteNetlogonLdapSrvWeight deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_LdapSrvWeight.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonLdapSrvWeight(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonLdapSrvWeight)
}

// GetNetlogonMaximumLogFileSize reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_MaximumLogFileSize.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonMaximumLogFileSize(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonMaximumLogFileSize)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonMaximumLogFileSize creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_MaximumLogFileSize.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonMaximumLogFileSize(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonMaximumLogFileSize, client.Chr(value))
}

// UpdateNetlogonMaximumLogFileSize updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_MaximumLogFileSize.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonMaximumLogFileSize(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonMaximumLogFileSize, client.Chr(value))
}

// DeleteNetlogonMaximumLogFileSize deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_MaximumLogFileSize.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonMaximumLogFileSize(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonMaximumLogFileSize)
}

// GetNetlogonNdncSiteCoverage reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NdncSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonNdncSiteCoverage(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonNdncSiteCoverage)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonNdncSiteCoverage creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NdncSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonNdncSiteCoverage(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonNdncSiteCoverage, client.Chr(value))
}

// UpdateNetlogonNdncSiteCoverage updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NdncSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonNdncSiteCoverage(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonNdncSiteCoverage, client.Chr(value))
}

// DeleteNetlogonNdncSiteCoverage deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NdncSiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonNdncSiteCoverage(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonNdncSiteCoverage)
}

// GetNetlogonNegativeCachePeriod reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NegativeCachePeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonNegativeCachePeriod(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonNegativeCachePeriod)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonNegativeCachePeriod creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NegativeCachePeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonNegativeCachePeriod(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonNegativeCachePeriod, client.Chr(value))
}

// UpdateNetlogonNegativeCachePeriod updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NegativeCachePeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonNegativeCachePeriod(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonNegativeCachePeriod, client.Chr(value))
}

// DeleteNetlogonNegativeCachePeriod deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NegativeCachePeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonNegativeCachePeriod(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonNegativeCachePeriod)
}

// GetNetlogonNetlogonShareCompatibilityMode reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NetlogonShareCompatibilityMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonNetlogonShareCompatibilityMode(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonNetlogonShareCompatibilityMode)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonNetlogonShareCompatibilityMode creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NetlogonShareCompatibilityMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonNetlogonShareCompatibilityMode(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonNetlogonShareCompatibilityMode, client.Chr(value))
}

// UpdateNetlogonNetlogonShareCompatibilityMode updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NetlogonShareCompatibilityMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonNetlogonShareCompatibilityMode(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonNetlogonShareCompatibilityMode, client.Chr(value))
}

// DeleteNetlogonNetlogonShareCompatibilityMode deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NetlogonShareCompatibilityMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonNetlogonShareCompatibilityMode(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonNetlogonShareCompatibilityMode)
}

// GetNetlogonNonBackgroundSuccessfulRefreshPeriod reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NonBackgroundSuccessfulRefreshPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonNonBackgroundSuccessfulRefreshPeriod(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonNonBackgroundSuccessfulRefreshPeriod)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonNonBackgroundSuccessfulRefreshPeriod creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NonBackgroundSuccessfulRefreshPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonNonBackgroundSuccessfulRefreshPeriod(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonNonBackgroundSuccessfulRefreshPeriod, client.Chr(value))
}

// UpdateNetlogonNonBackgroundSuccessfulRefreshPeriod updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NonBackgroundSuccessfulRefreshPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonNonBackgroundSuccessfulRefreshPeriod(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonNonBackgroundSuccessfulRefreshPeriod, client.Chr(value))
}

// DeleteNetlogonNonBackgroundSuccessfulRefreshPeriod deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_NonBackgroundSuccessfulRefreshPeriod.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonNonBackgroundSuccessfulRefreshPeriod(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonNonBackgroundSuccessfulRefreshPeriod)
}

// GetNetlogonPingUrgencyMode reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_PingUrgencyMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonPingUrgencyMode(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonPingUrgencyMode)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonPingUrgencyMode creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_PingUrgencyMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonPingUrgencyMode(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonPingUrgencyMode, client.Chr(value))
}

// UpdateNetlogonPingUrgencyMode updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_PingUrgencyMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonPingUrgencyMode(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonPingUrgencyMode, client.Chr(value))
}

// DeleteNetlogonPingUrgencyMode deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_PingUrgencyMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonPingUrgencyMode(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonPingUrgencyMode)
}

// GetNetlogonScavengeInterval reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ScavengeInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonScavengeInterval(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonScavengeInterval)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonScavengeInterval creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ScavengeInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonScavengeInterval(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonScavengeInterval, client.Chr(value))
}

// UpdateNetlogonScavengeInterval updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ScavengeInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonScavengeInterval(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonScavengeInterval, client.Chr(value))
}

// DeleteNetlogonScavengeInterval deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_ScavengeInterval.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonScavengeInterval(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonScavengeInterval)
}

// GetNetlogonSiteCoverage reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonSiteCoverage(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonSiteCoverage)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonSiteCoverage creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonSiteCoverage(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonSiteCoverage, client.Chr(value))
}

// UpdateNetlogonSiteCoverage updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonSiteCoverage(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonSiteCoverage, client.Chr(value))
}

// DeleteNetlogonSiteCoverage deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SiteCoverage.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonSiteCoverage(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonSiteCoverage)
}

// GetNetlogonSiteName reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SiteName.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonSiteName(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonSiteName)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonSiteName creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SiteName.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonSiteName(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonSiteName, client.Chr(value))
}

// UpdateNetlogonSiteName updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SiteName.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonSiteName(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonSiteName, client.Chr(value))
}

// DeleteNetlogonSiteName deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SiteName.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonSiteName(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonSiteName)
}

// GetNetlogonSysvolShareCompatibilityMode reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SysvolShareCompatibilityMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonSysvolShareCompatibilityMode(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonSysvolShareCompatibilityMode)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonSysvolShareCompatibilityMode creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SysvolShareCompatibilityMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonSysvolShareCompatibilityMode(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonSysvolShareCompatibilityMode, client.Chr(value))
}

// UpdateNetlogonSysvolShareCompatibilityMode updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SysvolShareCompatibilityMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonSysvolShareCompatibilityMode(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonSysvolShareCompatibilityMode, client.Chr(value))
}

// DeleteNetlogonSysvolShareCompatibilityMode deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_SysvolShareCompatibilityMode.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonSysvolShareCompatibilityMode(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonSysvolShareCompatibilityMode)
}

// GetNetlogonTryNextClosestSite reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_TryNextClosestSite.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonTryNextClosestSite(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonTryNextClosestSite)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonTryNextClosestSite creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_TryNextClosestSite.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonTryNextClosestSite(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonTryNextClosestSite, client.Chr(value))
}

// UpdateNetlogonTryNextClosestSite updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_TryNextClosestSite.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonTryNextClosestSite(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonTryNextClosestSite, client.Chr(value))
}

// DeleteNetlogonTryNextClosestSite deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_TryNextClosestSite.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonTryNextClosestSite(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonTryNextClosestSite)
}

// GetNetlogonUseDynamicDns reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_UseDynamicDns.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) GetNetlogonUseDynamicDns(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URINetlogonUseDynamicDns)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateNetlogonUseDynamicDns creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_UseDynamicDns.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) CreateNetlogonUseDynamicDns(ctx context.Context, value string) error {
	return s.c.Add(ctx, URINetlogonUseDynamicDns, client.Chr(value))
}

// UpdateNetlogonUseDynamicDns updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_UseDynamicDns.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) UpdateNetlogonUseDynamicDns(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URINetlogonUseDynamicDns, client.Chr(value))
}

// DeleteNetlogonUseDynamicDns deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Netlogon/Netlogon_UseDynamicDns.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXNetlogon) DeleteNetlogonUseDynamicDns(ctx context.Context) error {
	return s.c.Delete(ctx, URINetlogonUseDynamicDns)
}
