// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_logon_user

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXLogonUser exposes LCRUD operations over the ADMX_Logon Policy area nodes.
type ADMXLogonUser struct {
	c client.Client
}

// NewADMXLogonUser returns a ADMXLogonUser service backed by transport c.
func NewADMXLogonUser(c client.Client) *ADMXLogonUser {
	return &ADMXLogonUser{c: c}
}
