// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package kioskbrowser_user

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetBlockedUrlExceptions reads ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrlExceptions.
// List of exceptions to the blocked website URLs (with wildcard support). This is used to
// configure URLs kiosk browsers are allowed to navigate to, which are a subset of the blocked
// URLs.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) GetBlockedUrlExceptions(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIBlockedUrlExceptions)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateBlockedUrlExceptions creates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrlExceptions.
// List of exceptions to the blocked website URLs (with wildcard support). This is used to
// configure URLs kiosk browsers are allowed to navigate to, which are a subset of the blocked
// URLs.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) CreateBlockedUrlExceptions(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIBlockedUrlExceptions, client.Chr(value))
}

// UpdateBlockedUrlExceptions updates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrlExceptions.
// List of exceptions to the blocked website URLs (with wildcard support). This is used to
// configure URLs kiosk browsers are allowed to navigate to, which are a subset of the blocked
// URLs.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) UpdateBlockedUrlExceptions(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIBlockedUrlExceptions, client.Chr(value))
}

// DeleteBlockedUrlExceptions deletes ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrlExceptions.
// List of exceptions to the blocked website URLs (with wildcard support). This is used to
// configure URLs kiosk browsers are allowed to navigate to, which are a subset of the blocked
// URLs.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) DeleteBlockedUrlExceptions(ctx context.Context) error {
	return s.c.Delete(ctx, URIBlockedUrlExceptions)
}

// GetBlockedUrls reads ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrls.
// List of blocked website URLs (with wildcard support). This is used to configure blocked URLs
// kiosk browsers can not navigate to.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) GetBlockedUrls(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIBlockedUrls)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateBlockedUrls creates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrls.
// List of blocked website URLs (with wildcard support). This is used to configure blocked URLs
// kiosk browsers can not navigate to.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) CreateBlockedUrls(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIBlockedUrls, client.Chr(value))
}

// UpdateBlockedUrls updates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrls.
// List of blocked website URLs (with wildcard support). This is used to configure blocked URLs
// kiosk browsers can not navigate to.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) UpdateBlockedUrls(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIBlockedUrls, client.Chr(value))
}

// DeleteBlockedUrls deletes ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrls.
// List of blocked website URLs (with wildcard support). This is used to configure blocked URLs
// kiosk browsers can not navigate to.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) DeleteBlockedUrls(ctx context.Context) error {
	return s.c.Delete(ctx, URIBlockedUrls)
}

// GetDefaultURL reads ./User/Vendor/MSFT/Policy/Config/KioskBrowser/DefaultURL.
// Configures the default URL kiosk browsers to navigate on launch and restart.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) GetDefaultURL(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIDefaultURL)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateDefaultURL creates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/DefaultURL.
// Configures the default URL kiosk browsers to navigate on launch and restart.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) CreateDefaultURL(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIDefaultURL, client.Chr(value))
}

// UpdateDefaultURL updates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/DefaultURL.
// Configures the default URL kiosk browsers to navigate on launch and restart.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) UpdateDefaultURL(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIDefaultURL, client.Chr(value))
}

// DeleteDefaultURL deletes ./User/Vendor/MSFT/Policy/Config/KioskBrowser/DefaultURL.
// Configures the default URL kiosk browsers to navigate on launch and restart.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) DeleteDefaultURL(ctx context.Context) error {
	return s.c.Delete(ctx, URIDefaultURL)
}

// GetEnableEndSessionButton reads ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableEndSessionButton.
// Enable/disable kiosk browser's end session button.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) GetEnableEndSessionButton(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIEnableEndSessionButton)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateEnableEndSessionButton creates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableEndSessionButton.
// Enable/disable kiosk browser's end session button.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) CreateEnableEndSessionButton(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIEnableEndSessionButton, client.Int(value))
}

// UpdateEnableEndSessionButton updates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableEndSessionButton.
// Enable/disable kiosk browser's end session button.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) UpdateEnableEndSessionButton(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIEnableEndSessionButton, client.Int(value))
}

// DeleteEnableEndSessionButton deletes ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableEndSessionButton.
// Enable/disable kiosk browser's end session button.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) DeleteEnableEndSessionButton(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableEndSessionButton)
}

// GetEnableHomeButton reads ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableHomeButton.
// Enable/disable kiosk browser's home button.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) GetEnableHomeButton(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIEnableHomeButton)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateEnableHomeButton creates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableHomeButton.
// Enable/disable kiosk browser's home button.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) CreateEnableHomeButton(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIEnableHomeButton, client.Int(value))
}

// UpdateEnableHomeButton updates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableHomeButton.
// Enable/disable kiosk browser's home button.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) UpdateEnableHomeButton(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIEnableHomeButton, client.Int(value))
}

// DeleteEnableHomeButton deletes ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableHomeButton.
// Enable/disable kiosk browser's home button.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) DeleteEnableHomeButton(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableHomeButton)
}

// GetEnableNavigationButtons reads ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableNavigationButtons.
// Enable/disable kiosk browser's navigation buttons (forward/back).
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) GetEnableNavigationButtons(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIEnableNavigationButtons)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateEnableNavigationButtons creates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableNavigationButtons.
// Enable/disable kiosk browser's navigation buttons (forward/back).
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) CreateEnableNavigationButtons(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIEnableNavigationButtons, client.Int(value))
}

// UpdateEnableNavigationButtons updates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableNavigationButtons.
// Enable/disable kiosk browser's navigation buttons (forward/back).
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) UpdateEnableNavigationButtons(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIEnableNavigationButtons, client.Int(value))
}

// DeleteEnableNavigationButtons deletes ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableNavigationButtons.
// Enable/disable kiosk browser's navigation buttons (forward/back).
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) DeleteEnableNavigationButtons(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableNavigationButtons)
}

// GetRestartOnIdleTime reads ./User/Vendor/MSFT/Policy/Config/KioskBrowser/RestartOnIdleTime.
// Amount of time in minutes the session is idle until the kiosk browser restarts in a fresh state.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) GetRestartOnIdleTime(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIRestartOnIdleTime)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateRestartOnIdleTime creates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/RestartOnIdleTime.
// Amount of time in minutes the session is idle until the kiosk browser restarts in a fresh state.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) CreateRestartOnIdleTime(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIRestartOnIdleTime, client.Int(value))
}

// UpdateRestartOnIdleTime updates ./User/Vendor/MSFT/Policy/Config/KioskBrowser/RestartOnIdleTime.
// Amount of time in minutes the session is idle until the kiosk browser restarts in a fresh state.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) UpdateRestartOnIdleTime(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIRestartOnIdleTime, client.Int(value))
}

// DeleteRestartOnIdleTime deletes ./User/Vendor/MSFT/Policy/Config/KioskBrowser/RestartOnIdleTime.
// Amount of time in minutes the session is idle until the kiosk browser restarts in a fresh state.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *KioskBrowserUser) DeleteRestartOnIdleTime(ctx context.Context) error {
	return s.c.Delete(ctx, URIRestartOnIdleTime)
}
