// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package timelanguagesettings_user

// RestrictLanguagePacksAndFeaturesInstall allowed values.
const (
	// Not restricted.
	RestrictLanguagePacksAndFeaturesInstallNotRestricted int64 = 0
	// Restricted.
	RestrictLanguagePacksAndFeaturesInstallRestricted int64 = 1
)
