// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_terminalserver binds the ADMX_TerminalServer Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_TerminalServer).
//
// Generated from the February 2026 DDF v2 release.
package admx_terminalserver
