// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_distributedlinktracking binds the ADMX_DistributedLinkTracking Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_DistributedLinkTracking).
//
// Generated from the February 2026 DDF v2 release.
package admx_distributedlinktracking
