// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_explorer

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetAdminInfoUrl reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Explorer/AdminInfoUrl.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXExplorer) GetAdminInfoUrl(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIAdminInfoUrl)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateAdminInfoUrl creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Explorer/AdminInfoUrl.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXExplorer) CreateAdminInfoUrl(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIAdminInfoUrl, client.Chr(value))
}

// UpdateAdminInfoUrl updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Explorer/AdminInfoUrl.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXExplorer) UpdateAdminInfoUrl(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIAdminInfoUrl, client.Chr(value))
}

// DeleteAdminInfoUrl deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Explorer/AdminInfoUrl.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXExplorer) DeleteAdminInfoUrl(ctx context.Context) error {
	return s.c.Delete(ctx, URIAdminInfoUrl)
}

// GetDisableRoamedProfileInit reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Explorer/DisableRoamedProfileInit.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXExplorer) GetDisableRoamedProfileInit(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIDisableRoamedProfileInit)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateDisableRoamedProfileInit creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Explorer/DisableRoamedProfileInit.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXExplorer) CreateDisableRoamedProfileInit(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIDisableRoamedProfileInit, client.Chr(value))
}

// UpdateDisableRoamedProfileInit updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Explorer/DisableRoamedProfileInit.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXExplorer) UpdateDisableRoamedProfileInit(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIDisableRoamedProfileInit, client.Chr(value))
}

// DeleteDisableRoamedProfileInit deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Explorer/DisableRoamedProfileInit.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXExplorer) DeleteDisableRoamedProfileInit(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableRoamedProfileInit)
}
