// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_explorer binds the ADMX_Explorer Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_Explorer).
//
// Generated from the February 2026 DDF v2 release.
package admx_explorer
