// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package enterprisemodernappmanagement binds the EnterpriseModernAppManagement configuration service provider
// (./Device/Vendor/MSFT/EnterpriseModernAppManagement).
//
// Generated from the February 2026 DDF v2 release.
package enterprisemodernappmanagement
