// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package windowsdefendersecuritycenter

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetCompanyName reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/CompanyName.
// The company name that is displayed to the users. CompanyName is required for both
// EnableCustomizedToasts and EnableInAppCustomization. If you disable or do not configure this
// setting, or do not have EnableCustomizedToasts or EnableInAppCustomization enabled, then devices
// will not display the contact options. Value type is string. Supported operations are Add, Get,
// Replace and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetCompanyName(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URICompanyName)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateCompanyName creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/CompanyName.
// The company name that is displayed to the users. CompanyName is required for both
// EnableCustomizedToasts and EnableInAppCustomization. If you disable or do not configure this
// setting, or do not have EnableCustomizedToasts or EnableInAppCustomization enabled, then devices
// will not display the contact options. Value type is string. Supported operations are Add, Get,
// Replace and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateCompanyName(ctx context.Context, value string) error {
	return s.c.Add(ctx, URICompanyName, client.Chr(value))
}

// UpdateCompanyName updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/CompanyName.
// The company name that is displayed to the users. CompanyName is required for both
// EnableCustomizedToasts and EnableInAppCustomization. If you disable or do not configure this
// setting, or do not have EnableCustomizedToasts or EnableInAppCustomization enabled, then devices
// will not display the contact options. Value type is string. Supported operations are Add, Get,
// Replace and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateCompanyName(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URICompanyName, client.Chr(value))
}

// DeleteCompanyName deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/CompanyName.
// The company name that is displayed to the users. CompanyName is required for both
// EnableCustomizedToasts and EnableInAppCustomization. If you disable or do not configure this
// setting, or do not have EnableCustomizedToasts or EnableInAppCustomization enabled, then devices
// will not display the contact options. Value type is string. Supported operations are Add, Get,
// Replace and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteCompanyName(ctx context.Context) error {
	return s.c.Delete(ctx, URICompanyName)
}

// GetDisableAccountProtectionUI reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableAccountProtectionUI.
// Use this policy setting to specify if to display the Account protection area in Windows Defender
// Security Center. If you disable or do not configure this setting, Windows defender Security
// Center will display this area.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) GetDisableAccountProtectionUI(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableAccountProtectionUI)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableAccountProtectionUI creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableAccountProtectionUI.
// Use this policy setting to specify if to display the Account protection area in Windows Defender
// Security Center. If you disable or do not configure this setting, Windows defender Security
// Center will display this area.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableAccountProtectionUI(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableAccountProtectionUI, client.Int(value))
}

// UpdateDisableAccountProtectionUI updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableAccountProtectionUI.
// Use this policy setting to specify if to display the Account protection area in Windows Defender
// Security Center. If you disable or do not configure this setting, Windows defender Security
// Center will display this area.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableAccountProtectionUI(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableAccountProtectionUI, client.Int(value))
}

// DeleteDisableAccountProtectionUI deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableAccountProtectionUI.
// Use this policy setting to specify if to display the Account protection area in Windows Defender
// Security Center. If you disable or do not configure this setting, Windows defender Security
// Center will display this area.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableAccountProtectionUI(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableAccountProtectionUI)
}

// GetDisableAppBrowserUI reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableAppBrowserUI.
// Use this policy setting if you want to disable the display of the app and browser protection
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetDisableAppBrowserUI(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableAppBrowserUI)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableAppBrowserUI creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableAppBrowserUI.
// Use this policy setting if you want to disable the display of the app and browser protection
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableAppBrowserUI(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableAppBrowserUI, client.Int(value))
}

// UpdateDisableAppBrowserUI updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableAppBrowserUI.
// Use this policy setting if you want to disable the display of the app and browser protection
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableAppBrowserUI(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableAppBrowserUI, client.Int(value))
}

// DeleteDisableAppBrowserUI deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableAppBrowserUI.
// Use this policy setting if you want to disable the display of the app and browser protection
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableAppBrowserUI(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableAppBrowserUI)
}

// GetDisableClearTpmButton reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableClearTpmButton.
// Disable the Clear TPM button in Windows Security. Enabled:The Clear TPM button will be
// unavailable for use. Disabled:The Clear TPM button will be available for use on supported
// systems. Not configured:Same as Disabled. Supported values:0 - Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) GetDisableClearTpmButton(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableClearTpmButton)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableClearTpmButton creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableClearTpmButton.
// Disable the Clear TPM button in Windows Security. Enabled:The Clear TPM button will be
// unavailable for use. Disabled:The Clear TPM button will be available for use on supported
// systems. Not configured:Same as Disabled. Supported values:0 - Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableClearTpmButton(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableClearTpmButton, client.Int(value))
}

// UpdateDisableClearTpmButton updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableClearTpmButton.
// Disable the Clear TPM button in Windows Security. Enabled:The Clear TPM button will be
// unavailable for use. Disabled:The Clear TPM button will be available for use on supported
// systems. Not configured:Same as Disabled. Supported values:0 - Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableClearTpmButton(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableClearTpmButton, client.Int(value))
}

// DeleteDisableClearTpmButton deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableClearTpmButton.
// Disable the Clear TPM button in Windows Security. Enabled:The Clear TPM button will be
// unavailable for use. Disabled:The Clear TPM button will be available for use on supported
// systems. Not configured:Same as Disabled. Supported values:0 - Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableClearTpmButton(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableClearTpmButton)
}

// GetDisableDeviceSecurityUI reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableDeviceSecurityUI.
// Use this policy setting if you want to disable the display of the Device security area in the
// Windows Defender Security Center. If you disable or do not configure this setting, Windows
// defender Security Center will display this area.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) GetDisableDeviceSecurityUI(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableDeviceSecurityUI)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableDeviceSecurityUI creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableDeviceSecurityUI.
// Use this policy setting if you want to disable the display of the Device security area in the
// Windows Defender Security Center. If you disable or do not configure this setting, Windows
// defender Security Center will display this area.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableDeviceSecurityUI(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableDeviceSecurityUI, client.Int(value))
}

// UpdateDisableDeviceSecurityUI updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableDeviceSecurityUI.
// Use this policy setting if you want to disable the display of the Device security area in the
// Windows Defender Security Center. If you disable or do not configure this setting, Windows
// defender Security Center will display this area.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableDeviceSecurityUI(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableDeviceSecurityUI, client.Int(value))
}

// DeleteDisableDeviceSecurityUI deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableDeviceSecurityUI.
// Use this policy setting if you want to disable the display of the Device security area in the
// Windows Defender Security Center. If you disable or do not configure this setting, Windows
// defender Security Center will display this area.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableDeviceSecurityUI(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableDeviceSecurityUI)
}

// GetDisableEnhancedNotifications reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableEnhancedNotifications.
// Use this policy if you want Windows Defender Security Center to only display notifications which
// are considered critical. If you disable or do not configure this setting, Windows Defender
// Security Center will display critical and non-critical notifications to users. NoteIf Suppress
// notification is enabled then users will not see critical or non-critical messages. Value type is
// integer. Supported operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetDisableEnhancedNotifications(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableEnhancedNotifications)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableEnhancedNotifications creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableEnhancedNotifications.
// Use this policy if you want Windows Defender Security Center to only display notifications which
// are considered critical. If you disable or do not configure this setting, Windows Defender
// Security Center will display critical and non-critical notifications to users. NoteIf Suppress
// notification is enabled then users will not see critical or non-critical messages. Value type is
// integer. Supported operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableEnhancedNotifications(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableEnhancedNotifications, client.Int(value))
}

// UpdateDisableEnhancedNotifications updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableEnhancedNotifications.
// Use this policy if you want Windows Defender Security Center to only display notifications which
// are considered critical. If you disable or do not configure this setting, Windows Defender
// Security Center will display critical and non-critical notifications to users. NoteIf Suppress
// notification is enabled then users will not see critical or non-critical messages. Value type is
// integer. Supported operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableEnhancedNotifications(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableEnhancedNotifications, client.Int(value))
}

// DeleteDisableEnhancedNotifications deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableEnhancedNotifications.
// Use this policy if you want Windows Defender Security Center to only display notifications which
// are considered critical. If you disable or do not configure this setting, Windows Defender
// Security Center will display critical and non-critical notifications to users. NoteIf Suppress
// notification is enabled then users will not see critical or non-critical messages. Value type is
// integer. Supported operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableEnhancedNotifications(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableEnhancedNotifications)
}

// GetDisableFamilyUI reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableFamilyUI.
// Use this policy setting if you want to disable the display of the family options area in Windows
// Defender Security Center. If you disable or do not configure this setting, Windows defender
// Security Center will display this area. Value type is integer. Supported operations are Add,
// Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetDisableFamilyUI(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableFamilyUI)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableFamilyUI creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableFamilyUI.
// Use this policy setting if you want to disable the display of the family options area in Windows
// Defender Security Center. If you disable or do not configure this setting, Windows defender
// Security Center will display this area. Value type is integer. Supported operations are Add,
// Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableFamilyUI(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableFamilyUI, client.Int(value))
}

// UpdateDisableFamilyUI updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableFamilyUI.
// Use this policy setting if you want to disable the display of the family options area in Windows
// Defender Security Center. If you disable or do not configure this setting, Windows defender
// Security Center will display this area. Value type is integer. Supported operations are Add,
// Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableFamilyUI(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableFamilyUI, client.Int(value))
}

// DeleteDisableFamilyUI deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableFamilyUI.
// Use this policy setting if you want to disable the display of the family options area in Windows
// Defender Security Center. If you disable or do not configure this setting, Windows defender
// Security Center will display this area. Value type is integer. Supported operations are Add,
// Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableFamilyUI(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableFamilyUI)
}

// GetDisableHealthUI reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableHealthUI.
// Use this policy setting if you want to disable the display of the device performance and health
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetDisableHealthUI(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableHealthUI)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableHealthUI creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableHealthUI.
// Use this policy setting if you want to disable the display of the device performance and health
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableHealthUI(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableHealthUI, client.Int(value))
}

// UpdateDisableHealthUI updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableHealthUI.
// Use this policy setting if you want to disable the display of the device performance and health
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableHealthUI(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableHealthUI, client.Int(value))
}

// DeleteDisableHealthUI deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableHealthUI.
// Use this policy setting if you want to disable the display of the device performance and health
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableHealthUI(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableHealthUI)
}

// GetDisableNetworkUI reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableNetworkUI.
// Use this policy setting if you want to disable the display of the firewall and network
// protection area in Windows Defender Security Center. If you disable or do not configure this
// setting, Windows defender Security Center will display this area. Value type is integer.
// Supported operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetDisableNetworkUI(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableNetworkUI)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableNetworkUI creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableNetworkUI.
// Use this policy setting if you want to disable the display of the firewall and network
// protection area in Windows Defender Security Center. If you disable or do not configure this
// setting, Windows defender Security Center will display this area. Value type is integer.
// Supported operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableNetworkUI(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableNetworkUI, client.Int(value))
}

// UpdateDisableNetworkUI updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableNetworkUI.
// Use this policy setting if you want to disable the display of the firewall and network
// protection area in Windows Defender Security Center. If you disable or do not configure this
// setting, Windows defender Security Center will display this area. Value type is integer.
// Supported operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableNetworkUI(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableNetworkUI, client.Int(value))
}

// DeleteDisableNetworkUI deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableNetworkUI.
// Use this policy setting if you want to disable the display of the firewall and network
// protection area in Windows Defender Security Center. If you disable or do not configure this
// setting, Windows defender Security Center will display this area. Value type is integer.
// Supported operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableNetworkUI(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableNetworkUI)
}

// GetDisableNotifications reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableNotifications.
// Use this policy setting if you want to disable the display of Windows Defender Security Center
// notifications. If you disable or do not configure this setting, Windows Defender Security Center
// notifications will display on devices. Value type is integer. Supported operations are Add, Get,
// Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetDisableNotifications(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableNotifications)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableNotifications creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableNotifications.
// Use this policy setting if you want to disable the display of Windows Defender Security Center
// notifications. If you disable or do not configure this setting, Windows Defender Security Center
// notifications will display on devices. Value type is integer. Supported operations are Add, Get,
// Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableNotifications(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableNotifications, client.Int(value))
}

// UpdateDisableNotifications updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableNotifications.
// Use this policy setting if you want to disable the display of Windows Defender Security Center
// notifications. If you disable or do not configure this setting, Windows Defender Security Center
// notifications will display on devices. Value type is integer. Supported operations are Add, Get,
// Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableNotifications(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableNotifications, client.Int(value))
}

// DeleteDisableNotifications deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableNotifications.
// Use this policy setting if you want to disable the display of Windows Defender Security Center
// notifications. If you disable or do not configure this setting, Windows Defender Security Center
// notifications will display on devices. Value type is integer. Supported operations are Add, Get,
// Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableNotifications(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableNotifications)
}

// GetDisableTpmFirmwareUpdateWarning reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableTpmFirmwareUpdateWarning.
// Hide the recommendation to update TPM Firmware when a vulnerable firmware is detected.
// Enabled:Users will not be shown a recommendation to update their TPM Firmware. Disabled:Users
// will see a recommendation to update their TPM Firmware if Windows Security detects the system
// contains a TPM with vulnerable firmware. Not configured:Same as Disabled. Supported values:0 -
// Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) GetDisableTpmFirmwareUpdateWarning(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableTpmFirmwareUpdateWarning)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableTpmFirmwareUpdateWarning creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableTpmFirmwareUpdateWarning.
// Hide the recommendation to update TPM Firmware when a vulnerable firmware is detected.
// Enabled:Users will not be shown a recommendation to update their TPM Firmware. Disabled:Users
// will see a recommendation to update their TPM Firmware if Windows Security detects the system
// contains a TPM with vulnerable firmware. Not configured:Same as Disabled. Supported values:0 -
// Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableTpmFirmwareUpdateWarning(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableTpmFirmwareUpdateWarning, client.Int(value))
}

// UpdateDisableTpmFirmwareUpdateWarning updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableTpmFirmwareUpdateWarning.
// Hide the recommendation to update TPM Firmware when a vulnerable firmware is detected.
// Enabled:Users will not be shown a recommendation to update their TPM Firmware. Disabled:Users
// will see a recommendation to update their TPM Firmware if Windows Security detects the system
// contains a TPM with vulnerable firmware. Not configured:Same as Disabled. Supported values:0 -
// Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableTpmFirmwareUpdateWarning(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableTpmFirmwareUpdateWarning, client.Int(value))
}

// DeleteDisableTpmFirmwareUpdateWarning deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableTpmFirmwareUpdateWarning.
// Hide the recommendation to update TPM Firmware when a vulnerable firmware is detected.
// Enabled:Users will not be shown a recommendation to update their TPM Firmware. Disabled:Users
// will see a recommendation to update their TPM Firmware if Windows Security detects the system
// contains a TPM with vulnerable firmware. Not configured:Same as Disabled. Supported values:0 -
// Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableTpmFirmwareUpdateWarning(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableTpmFirmwareUpdateWarning)
}

// GetDisableVirusUI reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableVirusUI.
// Use this policy setting if you want to disable the display of the virus and threat protection
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetDisableVirusUI(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisableVirusUI)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisableVirusUI creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableVirusUI.
// Use this policy setting if you want to disable the display of the virus and threat protection
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateDisableVirusUI(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisableVirusUI, client.Int(value))
}

// UpdateDisableVirusUI updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableVirusUI.
// Use this policy setting if you want to disable the display of the virus and threat protection
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisableVirusUI(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisableVirusUI, client.Int(value))
}

// DeleteDisableVirusUI deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisableVirusUI.
// Use this policy setting if you want to disable the display of the virus and threat protection
// area in Windows Defender Security Center. If you disable or do not configure this setting,
// Windows defender Security Center will display this area. Value type is integer. Supported
// operations are Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisableVirusUI(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisableVirusUI)
}

// GetDisallowExploitProtectionOverride reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisallowExploitProtectionOverride.
// Prevent users from making changes to the exploit protection settings area in the Windows
// Defender Security Center. If you disable or do not configure this setting, local users can make
// changes in the exploit protection settings area. Value type is integer. Supported operations are
// Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetDisallowExploitProtectionOverride(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDisallowExploitProtectionOverride)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateDisallowExploitProtectionOverride creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisallowExploitProtectionOverride.
// Prevent users from making changes to the exploit protection settings area in the Windows
// Defender Security Center. If you disable or do not configure this setting, local users can make
// changes in the exploit protection settings area. Value type is integer. Supported operations are
// Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateDisallowExploitProtectionOverride(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIDisallowExploitProtectionOverride, client.Int(value))
}

// UpdateDisallowExploitProtectionOverride updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisallowExploitProtectionOverride.
// Prevent users from making changes to the exploit protection settings area in the Windows
// Defender Security Center. If you disable or do not configure this setting, local users can make
// changes in the exploit protection settings area. Value type is integer. Supported operations are
// Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateDisallowExploitProtectionOverride(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIDisallowExploitProtectionOverride, client.Int(value))
}

// DeleteDisallowExploitProtectionOverride deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/DisallowExploitProtectionOverride.
// Prevent users from making changes to the exploit protection settings area in the Windows
// Defender Security Center. If you disable or do not configure this setting, local users can make
// changes in the exploit protection settings area. Value type is integer. Supported operations are
// Add, Get, Replace and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteDisallowExploitProtectionOverride(ctx context.Context) error {
	return s.c.Delete(ctx, URIDisallowExploitProtectionOverride)
}

// GetEmail reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/Email.
// The email address that is displayed to users. The default mail application is used to initiate
// email actions. If you disable or do not configure this setting, or do not have
// EnableCustomizedToasts or EnableInAppCustomization enabled, then devices will not display
// contact options. Value type is string. Supported operations are Add, Get, Replace and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetEmail(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIEmail)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateEmail creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/Email.
// The email address that is displayed to users. The default mail application is used to initiate
// email actions. If you disable or do not configure this setting, or do not have
// EnableCustomizedToasts or EnableInAppCustomization enabled, then devices will not display
// contact options. Value type is string. Supported operations are Add, Get, Replace and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateEmail(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIEmail, client.Chr(value))
}

// UpdateEmail updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/Email.
// The email address that is displayed to users. The default mail application is used to initiate
// email actions. If you disable or do not configure this setting, or do not have
// EnableCustomizedToasts or EnableInAppCustomization enabled, then devices will not display
// contact options. Value type is string. Supported operations are Add, Get, Replace and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateEmail(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIEmail, client.Chr(value))
}

// DeleteEmail deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/Email.
// The email address that is displayed to users. The default mail application is used to initiate
// email actions. If you disable or do not configure this setting, or do not have
// EnableCustomizedToasts or EnableInAppCustomization enabled, then devices will not display
// contact options. Value type is string. Supported operations are Add, Get, Replace and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteEmail(ctx context.Context) error {
	return s.c.Delete(ctx, URIEmail)
}

// GetEnableCustomizedToasts reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/EnableCustomizedToasts.
// Enable this policy to display your company name and contact options in the notifications. If you
// disable or do not configure this setting, or do not provide CompanyName and a minimum of one
// contact method (Phone using Skype, Email, Help portal URL) Windows Defender Security Center will
// display a default notification text. Value type is integer. Supported operations are Add, Get,
// Replace, and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetEnableCustomizedToasts(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIEnableCustomizedToasts)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateEnableCustomizedToasts creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/EnableCustomizedToasts.
// Enable this policy to display your company name and contact options in the notifications. If you
// disable or do not configure this setting, or do not provide CompanyName and a minimum of one
// contact method (Phone using Skype, Email, Help portal URL) Windows Defender Security Center will
// display a default notification text. Value type is integer. Supported operations are Add, Get,
// Replace, and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateEnableCustomizedToasts(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIEnableCustomizedToasts, client.Int(value))
}

// UpdateEnableCustomizedToasts updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/EnableCustomizedToasts.
// Enable this policy to display your company name and contact options in the notifications. If you
// disable or do not configure this setting, or do not provide CompanyName and a minimum of one
// contact method (Phone using Skype, Email, Help portal URL) Windows Defender Security Center will
// display a default notification text. Value type is integer. Supported operations are Add, Get,
// Replace, and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateEnableCustomizedToasts(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIEnableCustomizedToasts, client.Int(value))
}

// DeleteEnableCustomizedToasts deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/EnableCustomizedToasts.
// Enable this policy to display your company name and contact options in the notifications. If you
// disable or do not configure this setting, or do not provide CompanyName and a minimum of one
// contact method (Phone using Skype, Email, Help portal URL) Windows Defender Security Center will
// display a default notification text. Value type is integer. Supported operations are Add, Get,
// Replace, and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteEnableCustomizedToasts(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableCustomizedToasts)
}

// GetEnableInAppCustomization reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/EnableInAppCustomization.
// Enable this policy to have your company name and contact options displayed in a contact card fly
// out in Windows Defender Security Center. If you disable or do not configure this setting, or do
// not provide CompanyName and a minimum of one contact method (Phone using Skype, Email, Help
// portal URL) Windows Defender Security Center will not display the contact card fly out
// notification. Value type is integer. Supported operations are Add, Get, Replace, and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetEnableInAppCustomization(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIEnableInAppCustomization)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateEnableInAppCustomization creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/EnableInAppCustomization.
// Enable this policy to have your company name and contact options displayed in a contact card fly
// out in Windows Defender Security Center. If you disable or do not configure this setting, or do
// not provide CompanyName and a minimum of one contact method (Phone using Skype, Email, Help
// portal URL) Windows Defender Security Center will not display the contact card fly out
// notification. Value type is integer. Supported operations are Add, Get, Replace, and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateEnableInAppCustomization(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIEnableInAppCustomization, client.Int(value))
}

// UpdateEnableInAppCustomization updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/EnableInAppCustomization.
// Enable this policy to have your company name and contact options displayed in a contact card fly
// out in Windows Defender Security Center. If you disable or do not configure this setting, or do
// not provide CompanyName and a minimum of one contact method (Phone using Skype, Email, Help
// portal URL) Windows Defender Security Center will not display the contact card fly out
// notification. Value type is integer. Supported operations are Add, Get, Replace, and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateEnableInAppCustomization(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIEnableInAppCustomization, client.Int(value))
}

// DeleteEnableInAppCustomization deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/EnableInAppCustomization.
// Enable this policy to have your company name and contact options displayed in a contact card fly
// out in Windows Defender Security Center. If you disable or do not configure this setting, or do
// not provide CompanyName and a minimum of one contact method (Phone using Skype, Email, Help
// portal URL) Windows Defender Security Center will not display the contact card fly out
// notification. Value type is integer. Supported operations are Add, Get, Replace, and Delete.
//
// Default: 0.
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteEnableInAppCustomization(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnableInAppCustomization)
}

// GetHideRansomwareDataRecovery reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideRansomwareDataRecovery.
// Use this policy setting to hide the Ransomware data recovery area in Windows Defender Security
// Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) GetHideRansomwareDataRecovery(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIHideRansomwareDataRecovery)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateHideRansomwareDataRecovery creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideRansomwareDataRecovery.
// Use this policy setting to hide the Ransomware data recovery area in Windows Defender Security
// Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) CreateHideRansomwareDataRecovery(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIHideRansomwareDataRecovery, client.Int(value))
}

// UpdateHideRansomwareDataRecovery updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideRansomwareDataRecovery.
// Use this policy setting to hide the Ransomware data recovery area in Windows Defender Security
// Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) UpdateHideRansomwareDataRecovery(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIHideRansomwareDataRecovery, client.Int(value))
}

// DeleteHideRansomwareDataRecovery deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideRansomwareDataRecovery.
// Use this policy setting to hide the Ransomware data recovery area in Windows Defender Security
// Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) DeleteHideRansomwareDataRecovery(ctx context.Context) error {
	return s.c.Delete(ctx, URIHideRansomwareDataRecovery)
}

// GetHideSecureBoot reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideSecureBoot.
// Use this policy to hide the Secure boot area in the Windows Defender Security Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) GetHideSecureBoot(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIHideSecureBoot)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateHideSecureBoot creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideSecureBoot.
// Use this policy to hide the Secure boot area in the Windows Defender Security Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) CreateHideSecureBoot(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIHideSecureBoot, client.Int(value))
}

// UpdateHideSecureBoot updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideSecureBoot.
// Use this policy to hide the Secure boot area in the Windows Defender Security Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) UpdateHideSecureBoot(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIHideSecureBoot, client.Int(value))
}

// DeleteHideSecureBoot deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideSecureBoot.
// Use this policy to hide the Secure boot area in the Windows Defender Security Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) DeleteHideSecureBoot(ctx context.Context) error {
	return s.c.Delete(ctx, URIHideSecureBoot)
}

// GetHideTPMTroubleshooting reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideTPMTroubleshooting.
// Use this policy to hide the Security processor (TPM) troubleshooting area in the Windows
// Defender Security Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) GetHideTPMTroubleshooting(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIHideTPMTroubleshooting)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateHideTPMTroubleshooting creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideTPMTroubleshooting.
// Use this policy to hide the Security processor (TPM) troubleshooting area in the Windows
// Defender Security Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) CreateHideTPMTroubleshooting(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIHideTPMTroubleshooting, client.Int(value))
}

// UpdateHideTPMTroubleshooting updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideTPMTroubleshooting.
// Use this policy to hide the Security processor (TPM) troubleshooting area in the Windows
// Defender Security Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) UpdateHideTPMTroubleshooting(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIHideTPMTroubleshooting, client.Int(value))
}

// DeleteHideTPMTroubleshooting deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideTPMTroubleshooting.
// Use this policy to hide the Security processor (TPM) troubleshooting area in the Windows
// Defender Security Center.
//
// Default: 0.
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *WindowsDefenderSecurityCenter) DeleteHideTPMTroubleshooting(ctx context.Context) error {
	return s.c.Delete(ctx, URIHideTPMTroubleshooting)
}

// GetHideWindowsSecurityNotificationAreaControl reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideWindowsSecurityNotificationAreaControl.
// This policy setting hides the Windows Security notification area control. The user needs to
// either sign out and sign in or reboot the computer for this setting to take effect.
// Enabled:Windows Security notification area control will be hidden. Disabled:Windows Security
// notification area control will be shown. Not configured:Same as Disabled. Supported values:0 -
// Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) GetHideWindowsSecurityNotificationAreaControl(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIHideWindowsSecurityNotificationAreaControl)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateHideWindowsSecurityNotificationAreaControl creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideWindowsSecurityNotificationAreaControl.
// This policy setting hides the Windows Security notification area control. The user needs to
// either sign out and sign in or reboot the computer for this setting to take effect.
// Enabled:Windows Security notification area control will be hidden. Disabled:Windows Security
// notification area control will be shown. Not configured:Same as Disabled. Supported values:0 -
// Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) CreateHideWindowsSecurityNotificationAreaControl(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIHideWindowsSecurityNotificationAreaControl, client.Int(value))
}

// UpdateHideWindowsSecurityNotificationAreaControl updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideWindowsSecurityNotificationAreaControl.
// This policy setting hides the Windows Security notification area control. The user needs to
// either sign out and sign in or reboot the computer for this setting to take effect.
// Enabled:Windows Security notification area control will be hidden. Disabled:Windows Security
// notification area control will be shown. Not configured:Same as Disabled. Supported values:0 -
// Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) UpdateHideWindowsSecurityNotificationAreaControl(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIHideWindowsSecurityNotificationAreaControl, client.Int(value))
}

// DeleteHideWindowsSecurityNotificationAreaControl deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/HideWindowsSecurityNotificationAreaControl.
// This policy setting hides the Windows Security notification area control. The user needs to
// either sign out and sign in or reboot the computer for this setting to take effect.
// Enabled:Windows Security notification area control will be hidden. Disabled:Windows Security
// notification area control will be shown. Not configured:Same as Disabled. Supported values:0 -
// Disabled (default)1 - Enabled
//
// Default: 0.
// Supported from OS build 10.0.17763 (CSP v8.0).
func (s *WindowsDefenderSecurityCenter) DeleteHideWindowsSecurityNotificationAreaControl(ctx context.Context) error {
	return s.c.Delete(ctx, URIHideWindowsSecurityNotificationAreaControl)
}

// GetPhone reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/Phone.
// The phone number or Skype ID that is displayed to users. Skype is used to initiate the call. If
// you disable or do not configure this setting, or do not have EnableCustomizedToasts or
// EnableInAppCustomization enabled, then devices will not display contact options. Value type is
// string. Supported operations are Add, Get, Replace, and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetPhone(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIPhone)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreatePhone creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/Phone.
// The phone number or Skype ID that is displayed to users. Skype is used to initiate the call. If
// you disable or do not configure this setting, or do not have EnableCustomizedToasts or
// EnableInAppCustomization enabled, then devices will not display contact options. Value type is
// string. Supported operations are Add, Get, Replace, and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreatePhone(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIPhone, client.Chr(value))
}

// UpdatePhone updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/Phone.
// The phone number or Skype ID that is displayed to users. Skype is used to initiate the call. If
// you disable or do not configure this setting, or do not have EnableCustomizedToasts or
// EnableInAppCustomization enabled, then devices will not display contact options. Value type is
// string. Supported operations are Add, Get, Replace, and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdatePhone(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIPhone, client.Chr(value))
}

// DeletePhone deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/Phone.
// The phone number or Skype ID that is displayed to users. Skype is used to initiate the call. If
// you disable or do not configure this setting, or do not have EnableCustomizedToasts or
// EnableInAppCustomization enabled, then devices will not display contact options. Value type is
// string. Supported operations are Add, Get, Replace, and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeletePhone(ctx context.Context) error {
	return s.c.Delete(ctx, URIPhone)
}

// GetURL reads ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/URL.
// The help portal URL this is displayed to users. The default browser is used to initiate this
// action. If you disable or do not configure this setting, or do not have EnableCustomizedToasts
// or EnableInAppCustomization enabled, then the device will not display contact options. Value
// type is Value type is string. Supported operations are Add, Get, Replace, and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) GetURL(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIURL)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateURL creates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/URL.
// The help portal URL this is displayed to users. The default browser is used to initiate this
// action. If you disable or do not configure this setting, or do not have EnableCustomizedToasts
// or EnableInAppCustomization enabled, then the device will not display contact options. Value
// type is Value type is string. Supported operations are Add, Get, Replace, and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) CreateURL(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIURL, client.Chr(value))
}

// UpdateURL updates ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/URL.
// The help portal URL this is displayed to users. The default browser is used to initiate this
// action. If you disable or do not configure this setting, or do not have EnableCustomizedToasts
// or EnableInAppCustomization enabled, then the device will not display contact options. Value
// type is Value type is string. Supported operations are Add, Get, Replace, and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) UpdateURL(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIURL, client.Chr(value))
}

// DeleteURL deletes ./Device/Vendor/MSFT/Policy/Config/WindowsDefenderSecurityCenter/URL.
// The help portal URL this is displayed to users. The default browser is used to initiate this
// action. If you disable or do not configure this setting, or do not have EnableCustomizedToasts
// or EnableInAppCustomization enabled, then the device will not display contact options. Value
// type is Value type is string. Supported operations are Add, Get, Replace, and Delete.
//
// Supported from OS build 10.0.16299 (CSP v6.0).
func (s *WindowsDefenderSecurityCenter) DeleteURL(ctx context.Context) error {
	return s.c.Delete(ctx, URIURL)
}
