// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package rootcatrustedcertificates_user

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// RootCATrustedCertificatesUser exposes LCRUD operations over the RootCATrustedCertificates CSP nodes.
type RootCATrustedCertificatesUser struct {
	c client.Client
}

// NewRootCATrustedCertificatesUser returns a RootCATrustedCertificatesUser service backed by transport c.
func NewRootCATrustedCertificatesUser(c client.Client) *RootCATrustedCertificatesUser {
	return &RootCATrustedCertificatesUser{c: c}
}
