// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package clouddesktop binds the CloudDesktop Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/CloudDesktop).
//
// Generated from the February 2026 DDF v2 release.
package clouddesktop
