// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package display_user

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetConfigureMultipleDisplayMode reads ./User/Vendor/MSFT/Policy/Config/Display/ConfigureMultipleDisplayMode.
// Set the default display arrangement as clone, extend, internalOnly, externalOnly or default
// Windows Settings.
//
// Default: 0.
// Supported from OS build 99.9.99999 (CSP v9.9).
func (s *DisplayUser) GetConfigureMultipleDisplayMode(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIConfigureMultipleDisplayMode)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateConfigureMultipleDisplayMode creates ./User/Vendor/MSFT/Policy/Config/Display/ConfigureMultipleDisplayMode.
// Set the default display arrangement as clone, extend, internalOnly, externalOnly or default
// Windows Settings.
//
// Default: 0.
// Supported from OS build 99.9.99999 (CSP v9.9).
func (s *DisplayUser) CreateConfigureMultipleDisplayMode(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIConfigureMultipleDisplayMode, client.Int(value))
}

// UpdateConfigureMultipleDisplayMode updates ./User/Vendor/MSFT/Policy/Config/Display/ConfigureMultipleDisplayMode.
// Set the default display arrangement as clone, extend, internalOnly, externalOnly or default
// Windows Settings.
//
// Default: 0.
// Supported from OS build 99.9.99999 (CSP v9.9).
func (s *DisplayUser) UpdateConfigureMultipleDisplayMode(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIConfigureMultipleDisplayMode, client.Int(value))
}

// DeleteConfigureMultipleDisplayMode deletes ./User/Vendor/MSFT/Policy/Config/Display/ConfigureMultipleDisplayMode.
// Set the default display arrangement as clone, extend, internalOnly, externalOnly or default
// Windows Settings.
//
// Default: 0.
// Supported from OS build 99.9.99999 (CSP v9.9).
func (s *DisplayUser) DeleteConfigureMultipleDisplayMode(ctx context.Context) error {
	return s.c.Delete(ctx, URIConfigureMultipleDisplayMode)
}

// GetEnablePerProcessDpi reads ./User/Vendor/MSFT/Policy/Config/Display/EnablePerProcessDpi.
// Enable or disable Per-Process System DPI for all applications.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *DisplayUser) GetEnablePerProcessDpi(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIEnablePerProcessDpi)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateEnablePerProcessDpi creates ./User/Vendor/MSFT/Policy/Config/Display/EnablePerProcessDpi.
// Enable or disable Per-Process System DPI for all applications.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *DisplayUser) CreateEnablePerProcessDpi(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URIEnablePerProcessDpi, client.Int(value))
}

// UpdateEnablePerProcessDpi updates ./User/Vendor/MSFT/Policy/Config/Display/EnablePerProcessDpi.
// Enable or disable Per-Process System DPI for all applications.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *DisplayUser) UpdateEnablePerProcessDpi(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URIEnablePerProcessDpi, client.Int(value))
}

// DeleteEnablePerProcessDpi deletes ./User/Vendor/MSFT/Policy/Config/Display/EnablePerProcessDpi.
// Enable or disable Per-Process System DPI for all applications.
//
// Supported from OS build 10.0.17134 (CSP v7.0).
func (s *DisplayUser) DeleteEnablePerProcessDpi(ctx context.Context) error {
	return s.c.Delete(ctx, URIEnablePerProcessDpi)
}

// GetSetClonePreferredResolutionSource reads ./User/Vendor/MSFT/Policy/Config/Display/SetClonePreferredResolutionSource.
// Set the cloned monitor preferred resolution source as internal or external monitor or set to
// default.
//
// Default: 0.
// Supported from OS build 99.9.99999 (CSP v9.9).
func (s *DisplayUser) GetSetClonePreferredResolutionSource(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URISetClonePreferredResolutionSource)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// CreateSetClonePreferredResolutionSource creates ./User/Vendor/MSFT/Policy/Config/Display/SetClonePreferredResolutionSource.
// Set the cloned monitor preferred resolution source as internal or external monitor or set to
// default.
//
// Default: 0.
// Supported from OS build 99.9.99999 (CSP v9.9).
func (s *DisplayUser) CreateSetClonePreferredResolutionSource(ctx context.Context, value int64) error {
	return s.c.Add(ctx, URISetClonePreferredResolutionSource, client.Int(value))
}

// UpdateSetClonePreferredResolutionSource updates ./User/Vendor/MSFT/Policy/Config/Display/SetClonePreferredResolutionSource.
// Set the cloned monitor preferred resolution source as internal or external monitor or set to
// default.
//
// Default: 0.
// Supported from OS build 99.9.99999 (CSP v9.9).
func (s *DisplayUser) UpdateSetClonePreferredResolutionSource(ctx context.Context, value int64) error {
	return s.c.Replace(ctx, URISetClonePreferredResolutionSource, client.Int(value))
}

// DeleteSetClonePreferredResolutionSource deletes ./User/Vendor/MSFT/Policy/Config/Display/SetClonePreferredResolutionSource.
// Set the cloned monitor preferred resolution source as internal or external monitor or set to
// default.
//
// Default: 0.
// Supported from OS build 99.9.99999 (CSP v9.9).
func (s *DisplayUser) DeleteSetClonePreferredResolutionSource(ctx context.Context) error {
	return s.c.Delete(ctx, URISetClonePreferredResolutionSource)
}
