// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package accounts

// AllowAddingNonMicrosoftAccountsManually allowed values.
const (
	// Not allowed.
	AllowAddingNonMicrosoftAccountsManuallyNotAllowed int64 = 0
	// Allowed.
	AllowAddingNonMicrosoftAccountsManuallyAllowed int64 = 1
)

// AllowMicrosoftAccountConnection allowed values.
const (
	// Not allowed.
	AllowMicrosoftAccountConnectionNotAllowed int64 = 0
	// Allowed.
	AllowMicrosoftAccountConnectionAllowed int64 = 1
)

// AllowMicrosoftAccountSignInAssistant allowed values.
const (
	// Disabled.
	AllowMicrosoftAccountSignInAssistantDisabled int64 = 0
	// Manual start.
	AllowMicrosoftAccountSignInAssistantManualStart int64 = 1
)

// RestrictToEnterpriseDeviceAuthenticationOnly allowed values.
const (
	// Allow both device and user authentication. Do not block user authentication.
	RestrictToEnterpriseDeviceAuthenticationOnlyAllowBothDeviceAndUserAuthentication int64 = 0
	// Only allow device authentication. Block user authentication.
	RestrictToEnterpriseDeviceAuthenticationOnlyOnlyAllowDeviceAuthentication int64 = 1
)
