// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_auditsettings binds the ADMX_AuditSettings Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_AuditSettings).
//
// Generated from the February 2026 DDF v2 release.
package admx_auditsettings
