// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_windowsconnectnow

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXWindowsConnectNow exposes LCRUD operations over the ADMX_WindowsConnectNow Policy area nodes.
type ADMXWindowsConnectNow struct {
	c client.Client
}

// NewADMXWindowsConnectNow returns a ADMXWindowsConnectNow service backed by transport c.
func NewADMXWindowsConnectNow(c client.Client) *ADMXWindowsConnectNow {
	return &ADMXWindowsConnectNow{c: c}
}
