// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package start

// AllowPinnedFolderDocuments allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderDocumentsTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderDocumentsTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderDocumentsThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// AllowPinnedFolderDownloads allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderDownloadsTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderDownloadsTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderDownloadsThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// AllowPinnedFolderFileExplorer allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderFileExplorerTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderFileExplorerTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderFileExplorerThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// AllowPinnedFolderHomeGroup allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderHomeGroupTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderHomeGroupTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderHomeGroupThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// AllowPinnedFolderMusic allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderMusicTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderMusicTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderMusicThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// AllowPinnedFolderNetwork allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderNetworkTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderNetworkTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderNetworkThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// AllowPinnedFolderPersonalFolder allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderPersonalFolderTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderPersonalFolderTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderPersonalFolderThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// AllowPinnedFolderPictures allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderPicturesTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderPicturesTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderPicturesThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// AllowPinnedFolderSettings allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderSettingsTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderSettingsTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderSettingsThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// AllowPinnedFolderVideos allowed values.
const (
	// The shortcut is hidden and disables the setting in the Settings app.
	AllowPinnedFolderVideosTheShortcutIsHiddenAndDisables int64 = 0
	// The shortcut is visible and disables the setting in the Settings app.
	AllowPinnedFolderVideosTheShortcutIsVisibleAndDisables int64 = 1
	// There is no enforced configuration and the setting can be changed by the user.
	AllowPinnedFolderVideosThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// ConfigureTaskbarSmallButtonBehavior allowed values.
const (
	// Always: The taskbar always uses small buttons. The setting will be grayed out in the Settings UI
	// and the user can not change the setting value.
	ConfigureTaskbarSmallButtonBehaviorAlways int64 = 0
	// When taskbar is full: The taskbar dynamically switches between small buttons and standard sized
	// buttons based on available space. The setting will be grayed out in the Settings UI and the user
	// can not change the setting value.
	ConfigureTaskbarSmallButtonBehaviorWhenTaskbarIsFull int64 = 1
	// Never: The taskbar never uses small buttons. Only standard sized buttons will be used. The
	// setting will be grayed out in the Settings UI and the user can not change the setting value.
	ConfigureTaskbarSmallButtonBehaviorNever int64 = 2
	// There is no enforced configuration and the setting can be changed by the user.
	ConfigureTaskbarSmallButtonBehaviorThereIsNoEnforcedConfigurationAnd int64 = 65535
)

// DisableContextMenus allowed values.
const (
	// Do not disable.
	DisableContextMenusDoNotDisable int64 = 0
	// Disable.
	DisableContextMenusDisable int64 = 1
)

// DisableEditingQuickSettings allowed values.
const (
	// Enable editing Quick Settings.
	DisableEditingQuickSettingsEnableEditingQuickSettings int64 = 0
	// Disable editing Quick Settings.
	DisableEditingQuickSettingsDisableEditingQuickSettings int64 = 1
)

// ForceStartSize allowed values.
const (
	// Do not force size of Start.
	ForceStartSizeDoNotForceSizeOfStart int64 = 0
	// Force non-fullscreen size of Start.
	ForceStartSizeForceNonFullscreenSizeOfStart int64 = 1
	// Force a fullscreen size of Start.
	ForceStartSizeForceAFullscreenSizeOfStart int64 = 2
)

// HideAppList allowed values.
const (
	// None.
	HideAppListNone int64 = 0
	// Hide all apps list.
	HideAppListHideAllAppsList int64 = 1
	// Hide all apps list, and Disable "Show app list in Start menu" in Settings app.
	HideAppListHideAllAppsListAndDisable int64 = 2
	// Hide all apps list, remove all apps button, and Disable "Show app list in Start menu" in
	// Settings app.
	HideAppListHideAllAppsListRemoveAll int64 = 3
)

// HideCategoryView allowed values.
const (
	// Category view shown.
	HideCategoryViewCategoryViewShown int64 = 0
	// Category view hidden.
	HideCategoryViewCategoryViewHidden int64 = 1
)

// HideChangeAccountSettings allowed values.
const (
	// Do not hide.
	HideChangeAccountSettingsDoNotHide int64 = 0
	// Hide.
	HideChangeAccountSettingsHide int64 = 1
)

// HideFrequentlyUsedApps allowed values.
const (
	// Do not hide.
	HideFrequentlyUsedAppsDoNotHide int64 = 0
	// Hide.
	HideFrequentlyUsedAppsHide int64 = 1
)

// HideHibernate allowed values.
const (
	// Do not hide.
	HideHibernateDoNotHide int64 = 0
	// Hide.
	HideHibernateHide int64 = 1
)

// HideLock allowed values.
const (
	// Do not hide.
	HideLockDoNotHide int64 = 0
	// Hide.
	HideLockHide int64 = 1
)

// HidePowerButton allowed values.
const (
	// Do not hide.
	HidePowerButtonDoNotHide int64 = 0
	// Hide.
	HidePowerButtonHide int64 = 1
)

// HideRecentJumplists allowed values.
const (
	// Do not hide.
	HideRecentJumplistsDoNotHide int64 = 0
	// Hide.
	HideRecentJumplistsHide int64 = 1
)

// HideRecentlyAddedApps allowed values.
const (
	// Do not hide.
	HideRecentlyAddedAppsDoNotHide int64 = 0
	// Hide.
	HideRecentlyAddedAppsHide int64 = 1
)

// HideRecommendedPersonalizedSites allowed values.
const (
	// Personalized Website Recommendations shown.
	HideRecommendedPersonalizedSitesPersonalizedWebsiteRecommendationsShown int64 = 0
	// Personalized Website Recommendations hidden.
	HideRecommendedPersonalizedSitesPersonalizedWebsiteRecommendationsHidden int64 = 1
)

// HideRecommendedSection allowed values.
const (
	// Recommended section shown.
	HideRecommendedSectionRecommendedSectionShown int64 = 0
	// Recommended section hidden.
	HideRecommendedSectionRecommendedSectionHidden int64 = 1
)

// HideRestart allowed values.
const (
	// Do not hide.
	HideRestartDoNotHide int64 = 0
	// Hide.
	HideRestartHide int64 = 1
)

// HideShutDown allowed values.
const (
	// Do not hide.
	HideShutDownDoNotHide int64 = 0
	// Hide.
	HideShutDownHide int64 = 1
)

// HideSignOut allowed values.
const (
	// Do not hide.
	HideSignOutDoNotHide int64 = 0
	// Hide.
	HideSignOutHide int64 = 1
)

// HideSleep allowed values.
const (
	// Do not hide.
	HideSleepDoNotHide int64 = 0
	// Hide.
	HideSleepHide int64 = 1
)

// HideSwitchAccount allowed values.
const (
	// Do not hide.
	HideSwitchAccountDoNotHide int64 = 0
	// Hide.
	HideSwitchAccountHide int64 = 1
)

// HideTaskViewButton allowed values.
const (
	// TaskView button shown.
	HideTaskViewButtonTaskViewButtonShown int64 = 0
	// TaskView button hidden.
	HideTaskViewButtonTaskViewButtonHidden int64 = 1
)

// HideUserTile allowed values.
const (
	// Do not hide.
	HideUserTileDoNotHide int64 = 0
	// Hide.
	HideUserTileHide int64 = 1
)

// NoPinningToTaskbar allowed values.
const (
	// Pinning enabled.
	NoPinningToTaskbarPinningEnabled int64 = 0
	// Pinning disabled.
	NoPinningToTaskbarPinningDisabled int64 = 1
)

// ShowOrHideMostUsedApps allowed values.
const (
	// Do not enforce visibility of list of most used apps in Start; user can control via Settings app
	// (default behavior equivalent to not configuring this policy).
	ShowOrHideMostUsedAppsDoNotEnforceVisibilityOfList int64 = 0
	// Force showing of list of most used apps in Start; corresponding toggle in Setting app is
	// disabled.
	ShowOrHideMostUsedAppsForceShowingOfListOfMost int64 = 1
	// Force hiding of list of most used apps in Start; corresponding toggle in Setting app is
	// disabled.
	ShowOrHideMostUsedAppsForceHidingOfListOfMost int64 = 2
)

// SimplifyQuickSettings allowed values.
const (
	// Load regular Quick Settings layout.
	SimplifyQuickSettingsLoadRegularQuickSettingsLayout int64 = 0
	// Load simplified Quick Settings layout.
	SimplifyQuickSettingsLoadSimplifiedQuickSettingsLayout int64 = 1
)
