// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_msi_user binds the ADMX_MSI Policy CSP area
// (./User/Vendor/MSFT/Policy/Config/ADMX_MSI).
//
// Generated from the February 2026 DDF v2 release.
package admx_msi_user
