// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_workfoldersclient

// OMA-URIs of the ADMX_WorkFoldersClient nodes addressed by this package.
const (
	// the ADMX_WorkFoldersClient root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_WorkFoldersClient"
	// the Pol_MachineEnableWorkFolders node.
	URIPolMachineEnableWorkFolders = "./Device/Vendor/MSFT/Policy/Config/ADMX_WorkFoldersClient/Pol_MachineEnableWorkFolders"
)
