// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package personalization

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetCompanyLogoStatus reads ./Vendor/MSFT/Personalization/CompanyLogoStatus.
// This represents the status of the Company Logo. 1 - Successfully downloaded or copied. 2 -
// Download/Copy in progress. 3 - Download/Copy failed. 4 - Unknown file type. 5 - Unsupported Url
// scheme. 6 - Max retry failed. This setting is currently available for boot to cloud shared pc
// mode only.
//
// Supported from OS build 10.0.22621.3374 (CSP v2.0).
func (s *Personalization) GetCompanyLogoStatus(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URICompanyLogoStatus)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// GetCompanyLogoUrl reads ./Vendor/MSFT/Personalization/CompanyLogoUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the
// Company Logo or a file Url to a local image on the file system that needs to be used as the
// Company Logo. This setting is currently available for boot to cloud shared pc mode only.
//
// Supported from OS build 10.0.22621.3374 (CSP v2.0).
func (s *Personalization) GetCompanyLogoUrl(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URICompanyLogoUrl)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateCompanyLogoUrl creates ./Vendor/MSFT/Personalization/CompanyLogoUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the
// Company Logo or a file Url to a local image on the file system that needs to be used as the
// Company Logo. This setting is currently available for boot to cloud shared pc mode only.
//
// Supported from OS build 10.0.22621.3374 (CSP v2.0).
func (s *Personalization) CreateCompanyLogoUrl(ctx context.Context, value string) error {
	return s.c.Add(ctx, URICompanyLogoUrl, client.Chr(value))
}

// UpdateCompanyLogoUrl updates ./Vendor/MSFT/Personalization/CompanyLogoUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the
// Company Logo or a file Url to a local image on the file system that needs to be used as the
// Company Logo. This setting is currently available for boot to cloud shared pc mode only.
//
// Supported from OS build 10.0.22621.3374 (CSP v2.0).
func (s *Personalization) UpdateCompanyLogoUrl(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URICompanyLogoUrl, client.Chr(value))
}

// DeleteCompanyLogoUrl deletes ./Vendor/MSFT/Personalization/CompanyLogoUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the
// Company Logo or a file Url to a local image on the file system that needs to be used as the
// Company Logo. This setting is currently available for boot to cloud shared pc mode only.
//
// Supported from OS build 10.0.22621.3374 (CSP v2.0).
func (s *Personalization) DeleteCompanyLogoUrl(ctx context.Context) error {
	return s.c.Delete(ctx, URICompanyLogoUrl)
}

// GetCompanyName reads ./Vendor/MSFT/Personalization/CompanyName.
// This represents the name of the company. It can be at most 30 characters long. This setting is
// currently available only for boot to cloud shared pc mode to display the company name on sign-in
// screen.
//
// Supported from OS build 10.0.22621.3374 (CSP v2.0).
func (s *Personalization) GetCompanyName(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URICompanyName)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateCompanyName creates ./Vendor/MSFT/Personalization/CompanyName.
// This represents the name of the company. It can be at most 30 characters long. This setting is
// currently available only for boot to cloud shared pc mode to display the company name on sign-in
// screen.
//
// Supported from OS build 10.0.22621.3374 (CSP v2.0).
func (s *Personalization) CreateCompanyName(ctx context.Context, value string) error {
	return s.c.Add(ctx, URICompanyName, client.Chr(value))
}

// UpdateCompanyName updates ./Vendor/MSFT/Personalization/CompanyName.
// This represents the name of the company. It can be at most 30 characters long. This setting is
// currently available only for boot to cloud shared pc mode to display the company name on sign-in
// screen.
//
// Supported from OS build 10.0.22621.3374 (CSP v2.0).
func (s *Personalization) UpdateCompanyName(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URICompanyName, client.Chr(value))
}

// DeleteCompanyName deletes ./Vendor/MSFT/Personalization/CompanyName.
// This represents the name of the company. It can be at most 30 characters long. This setting is
// currently available only for boot to cloud shared pc mode to display the company name on sign-in
// screen.
//
// Supported from OS build 10.0.22621.3374 (CSP v2.0).
func (s *Personalization) DeleteCompanyName(ctx context.Context) error {
	return s.c.Delete(ctx, URICompanyName)
}

// GetDesktopImageStatus reads ./Vendor/MSFT/Personalization/DesktopImageStatus.
// This represents the status of the DesktopImage. 1 - Successfully downloaded or copied. 2 -
// Download/Copy in progress. 3 - Download/Copy failed. 4 - Unknown file type. 5 - Unsupported Url
// scheme. 6 - Max retry failed.
func (s *Personalization) GetDesktopImageStatus(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URIDesktopImageStatus)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// GetDesktopImageUrl reads ./Vendor/MSFT/Personalization/DesktopImageUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the
// Desktop Image or a file Url to a local image on the file system that needs to be used as the
// Desktop Image.
func (s *Personalization) GetDesktopImageUrl(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIDesktopImageUrl)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateDesktopImageUrl creates ./Vendor/MSFT/Personalization/DesktopImageUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the
// Desktop Image or a file Url to a local image on the file system that needs to be used as the
// Desktop Image.
func (s *Personalization) CreateDesktopImageUrl(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIDesktopImageUrl, client.Chr(value))
}

// UpdateDesktopImageUrl updates ./Vendor/MSFT/Personalization/DesktopImageUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the
// Desktop Image or a file Url to a local image on the file system that needs to be used as the
// Desktop Image.
func (s *Personalization) UpdateDesktopImageUrl(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIDesktopImageUrl, client.Chr(value))
}

// DeleteDesktopImageUrl deletes ./Vendor/MSFT/Personalization/DesktopImageUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the
// Desktop Image or a file Url to a local image on the file system that needs to be used as the
// Desktop Image.
func (s *Personalization) DeleteDesktopImageUrl(ctx context.Context) error {
	return s.c.Delete(ctx, URIDesktopImageUrl)
}

// GetLockScreenImageStatus reads ./Vendor/MSFT/Personalization/LockScreenImageStatus.
// This represents the status of the LockScreenImage. 1 - Successfully downloaded or copied. 2 -
// Download/Copy in progress. 3 - Download/Copy failed. 4 - Unknown file type. 5 - Unsupported Url
// scheme. 6 - Max retry failed.
func (s *Personalization) GetLockScreenImageStatus(ctx context.Context) (int64, error) {
	v, err := s.c.Get(ctx, URILockScreenImageStatus)
	if err != nil {
		return 0, err
	}
	return v.Int()
}

// GetLockScreenImageUrl reads ./Vendor/MSFT/Personalization/LockScreenImageUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the Lock
// Screen Image or a file Url to a local image on the file system that needs to be used as the Lock
// Screen Image.
func (s *Personalization) GetLockScreenImageUrl(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URILockScreenImageUrl)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateLockScreenImageUrl creates ./Vendor/MSFT/Personalization/LockScreenImageUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the Lock
// Screen Image or a file Url to a local image on the file system that needs to be used as the Lock
// Screen Image.
func (s *Personalization) CreateLockScreenImageUrl(ctx context.Context, value string) error {
	return s.c.Add(ctx, URILockScreenImageUrl, client.Chr(value))
}

// UpdateLockScreenImageUrl updates ./Vendor/MSFT/Personalization/LockScreenImageUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the Lock
// Screen Image or a file Url to a local image on the file system that needs to be used as the Lock
// Screen Image.
func (s *Personalization) UpdateLockScreenImageUrl(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URILockScreenImageUrl, client.Chr(value))
}

// DeleteLockScreenImageUrl deletes ./Vendor/MSFT/Personalization/LockScreenImageUrl.
// A http or https Url to a jpg, jpeg or png image that needs to be downloaded and used as the Lock
// Screen Image or a file Url to a local image on the file system that needs to be used as the Lock
// Screen Image.
func (s *Personalization) DeleteLockScreenImageUrl(ctx context.Context) error {
	return s.c.Delete(ctx, URILockScreenImageUrl)
}
