// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package errorreporting binds the ErrorReporting Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ErrorReporting).
//
// Generated from the February 2026 DDF v2 release.
package errorreporting
