// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_networkconnections_user

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXNetworkConnectionsUser exposes LCRUD operations over the ADMX_NetworkConnections Policy area nodes.
type ADMXNetworkConnectionsUser struct {
	c client.Client
}

// NewADMXNetworkConnectionsUser returns a ADMXNetworkConnectionsUser service backed by transport c.
func NewADMXNetworkConnectionsUser(c client.Client) *ADMXNetworkConnectionsUser {
	return &ADMXNetworkConnectionsUser{c: c}
}
