// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_msdt

// OMA-URIs of the ADMX_MSDT nodes addressed by this package.
const (
	// the ADMX_MSDT root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSDT"
	// the MsdtSupportProvider node.
	URIMsdtSupportProvider = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSDT/MsdtSupportProvider"
	// the MsdtToolDownloadPolicy node.
	URIMsdtToolDownloadPolicy = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSDT/MsdtToolDownloadPolicy"
	// the WdiScenarioExecutionPolicy node.
	URIWdiScenarioExecutionPolicy = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSDT/WdiScenarioExecutionPolicy"
)
