// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package search

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Search exposes LCRUD operations over the Search Policy area nodes.
type Search struct {
	c client.Client
}

// NewSearch returns a Search service backed by transport c.
func NewSearch(c client.Client) *Search {
	return &Search{c: c}
}
