// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_securitycenter

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetSecurityCenterSecurityCenterInDomain reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Securitycenter/SecurityCenter_SecurityCenterInDomain.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXSecuritycenter) GetSecurityCenterSecurityCenterInDomain(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URISecurityCenterSecurityCenterInDomain)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateSecurityCenterSecurityCenterInDomain creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Securitycenter/SecurityCenter_SecurityCenterInDomain.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXSecuritycenter) CreateSecurityCenterSecurityCenterInDomain(ctx context.Context, value string) error {
	return s.c.Add(ctx, URISecurityCenterSecurityCenterInDomain, client.Chr(value))
}

// UpdateSecurityCenterSecurityCenterInDomain updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Securitycenter/SecurityCenter_SecurityCenterInDomain.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXSecuritycenter) UpdateSecurityCenterSecurityCenterInDomain(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URISecurityCenterSecurityCenterInDomain, client.Chr(value))
}

// DeleteSecurityCenterSecurityCenterInDomain deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Securitycenter/SecurityCenter_SecurityCenterInDomain.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXSecuritycenter) DeleteSecurityCenterSecurityCenterInDomain(ctx context.Context) error {
	return s.c.Delete(ctx, URISecurityCenterSecurityCenterInDomain)
}
