// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package reboot

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Reboot exposes LCRUD operations over the Reboot CSP nodes.
type Reboot struct {
	c client.Client
}

// NewReboot returns a Reboot service backed by transport c.
func NewReboot(c client.Client) *Reboot {
	return &Reboot{c: c}
}
