// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package browser_user

// OMA-URIs of the Browser nodes addressed by this package.
const (
	// the Browser root node.
	URIRoot = "./User/Vendor/MSFT/Policy/Config/Browser"
	// the AllowAddressBarDropdown node.
	URIAllowAddressBarDropdown = "./User/Vendor/MSFT/Policy/Config/Browser/AllowAddressBarDropdown"
	// the AllowAutofill node.
	URIAllowAutofill = "./User/Vendor/MSFT/Policy/Config/Browser/AllowAutofill"
	// the AllowBrowser node.
	URIAllowBrowser = "./User/Vendor/MSFT/Policy/Config/Browser/AllowBrowser"
	// the AllowConfigurationUpdateForBooksLibrary node.
	URIAllowConfigurationUpdateForBooksLibrary = "./User/Vendor/MSFT/Policy/Config/Browser/AllowConfigurationUpdateForBooksLibrary"
	// the AllowCookies node.
	URIAllowCookies = "./User/Vendor/MSFT/Policy/Config/Browser/AllowCookies"
	// the AllowDeveloperTools node.
	URIAllowDeveloperTools = "./User/Vendor/MSFT/Policy/Config/Browser/AllowDeveloperTools"
	// the AllowDoNotTrack node.
	URIAllowDoNotTrack = "./User/Vendor/MSFT/Policy/Config/Browser/AllowDoNotTrack"
	// the AllowExtensions node.
	URIAllowExtensions = "./User/Vendor/MSFT/Policy/Config/Browser/AllowExtensions"
	// the AllowFlash node.
	URIAllowFlash = "./User/Vendor/MSFT/Policy/Config/Browser/AllowFlash"
	// the AllowFlashClickToRun node.
	URIAllowFlashClickToRun = "./User/Vendor/MSFT/Policy/Config/Browser/AllowFlashClickToRun"
	// the AllowFullScreenMode node.
	URIAllowFullScreenMode = "./User/Vendor/MSFT/Policy/Config/Browser/AllowFullScreenMode"
	// the AllowInPrivate node.
	URIAllowInPrivate = "./User/Vendor/MSFT/Policy/Config/Browser/AllowInPrivate"
	// the AllowMicrosoftCompatibilityList node.
	URIAllowMicrosoftCompatibilityList = "./User/Vendor/MSFT/Policy/Config/Browser/AllowMicrosoftCompatibilityList"
	// the AllowPasswordManager node.
	URIAllowPasswordManager = "./User/Vendor/MSFT/Policy/Config/Browser/AllowPasswordManager"
	// the AllowPopups node.
	URIAllowPopups = "./User/Vendor/MSFT/Policy/Config/Browser/AllowPopups"
	// the AllowPrelaunch node.
	URIAllowPrelaunch = "./User/Vendor/MSFT/Policy/Config/Browser/AllowPrelaunch"
	// the AllowPrinting node.
	URIAllowPrinting = "./User/Vendor/MSFT/Policy/Config/Browser/AllowPrinting"
	// the AllowSavingHistory node.
	URIAllowSavingHistory = "./User/Vendor/MSFT/Policy/Config/Browser/AllowSavingHistory"
	// the AllowSearchEngineCustomization node.
	URIAllowSearchEngineCustomization = "./User/Vendor/MSFT/Policy/Config/Browser/AllowSearchEngineCustomization"
	// the AllowSearchSuggestionsinAddressBar node.
	URIAllowSearchSuggestionsinAddressBar = "./User/Vendor/MSFT/Policy/Config/Browser/AllowSearchSuggestionsinAddressBar"
	// the AllowSideloadingOfExtensions node.
	URIAllowSideloadingOfExtensions = "./User/Vendor/MSFT/Policy/Config/Browser/AllowSideloadingOfExtensions"
	// the AllowSmartScreen node.
	URIAllowSmartScreen = "./User/Vendor/MSFT/Policy/Config/Browser/AllowSmartScreen"
	// the AllowTabPreloading node.
	URIAllowTabPreloading = "./User/Vendor/MSFT/Policy/Config/Browser/AllowTabPreloading"
	// the AllowWebContentOnNewTabPage node.
	URIAllowWebContentOnNewTabPage = "./User/Vendor/MSFT/Policy/Config/Browser/AllowWebContentOnNewTabPage"
	// the AlwaysEnableBooksLibrary node.
	URIAlwaysEnableBooksLibrary = "./User/Vendor/MSFT/Policy/Config/Browser/AlwaysEnableBooksLibrary"
	// the ClearBrowsingDataOnExit node.
	URIClearBrowsingDataOnExit = "./User/Vendor/MSFT/Policy/Config/Browser/ClearBrowsingDataOnExit"
	// the ConfigureAdditionalSearchEngines node.
	URIConfigureAdditionalSearchEngines = "./User/Vendor/MSFT/Policy/Config/Browser/ConfigureAdditionalSearchEngines"
	// the ConfigureFavoritesBar node.
	URIConfigureFavoritesBar = "./User/Vendor/MSFT/Policy/Config/Browser/ConfigureFavoritesBar"
	// the ConfigureHomeButton node.
	URIConfigureHomeButton = "./User/Vendor/MSFT/Policy/Config/Browser/ConfigureHomeButton"
	// the ConfigureKioskMode node.
	URIConfigureKioskMode = "./User/Vendor/MSFT/Policy/Config/Browser/ConfigureKioskMode"
	// the ConfigureKioskResetAfterIdleTimeout node.
	URIConfigureKioskResetAfterIdleTimeout = "./User/Vendor/MSFT/Policy/Config/Browser/ConfigureKioskResetAfterIdleTimeout"
	// the ConfigureOpenMicrosoftEdgeWith node.
	URIConfigureOpenMicrosoftEdgeWith = "./User/Vendor/MSFT/Policy/Config/Browser/ConfigureOpenMicrosoftEdgeWith"
	// the ConfigureTelemetryForMicrosoft365Analytics node.
	URIConfigureTelemetryForMicrosoft365Analytics = "./User/Vendor/MSFT/Policy/Config/Browser/ConfigureTelemetryForMicrosoft365Analytics"
	// the DisableLockdownOfStartPages node.
	URIDisableLockdownOfStartPages = "./User/Vendor/MSFT/Policy/Config/Browser/DisableLockdownOfStartPages"
	// the EnableExtendedBooksTelemetry node.
	URIEnableExtendedBooksTelemetry = "./User/Vendor/MSFT/Policy/Config/Browser/EnableExtendedBooksTelemetry"
	// the EnterpriseModeSiteList node.
	URIEnterpriseModeSiteList = "./User/Vendor/MSFT/Policy/Config/Browser/EnterpriseModeSiteList"
	// the EnterpriseSiteListServiceUrl node.
	URIEnterpriseSiteListServiceUrl = "./User/Vendor/MSFT/Policy/Config/Browser/EnterpriseSiteListServiceUrl"
	// the FirstRunURL node.
	URIFirstRunURL = "./User/Vendor/MSFT/Policy/Config/Browser/FirstRunURL"
	// the HomePages node.
	URIHomePages = "./User/Vendor/MSFT/Policy/Config/Browser/HomePages"
	// the LockdownFavorites node.
	URILockdownFavorites = "./User/Vendor/MSFT/Policy/Config/Browser/LockdownFavorites"
	// the PreventAccessToAboutFlagsInMicrosoftEdge node.
	URIPreventAccessToAboutFlagsInMicrosoftEdge = "./User/Vendor/MSFT/Policy/Config/Browser/PreventAccessToAboutFlagsInMicrosoftEdge"
	// the PreventCertErrorOverrides node.
	URIPreventCertErrorOverrides = "./User/Vendor/MSFT/Policy/Config/Browser/PreventCertErrorOverrides"
	// the PreventFirstRunPage node.
	URIPreventFirstRunPage = "./User/Vendor/MSFT/Policy/Config/Browser/PreventFirstRunPage"
	// the PreventLiveTileDataCollection node.
	URIPreventLiveTileDataCollection = "./User/Vendor/MSFT/Policy/Config/Browser/PreventLiveTileDataCollection"
	// the PreventSmartScreenPromptOverride node.
	URIPreventSmartScreenPromptOverride = "./User/Vendor/MSFT/Policy/Config/Browser/PreventSmartScreenPromptOverride"
	// the PreventSmartScreenPromptOverrideForFiles node.
	URIPreventSmartScreenPromptOverrideForFiles = "./User/Vendor/MSFT/Policy/Config/Browser/PreventSmartScreenPromptOverrideForFiles"
	// the PreventTurningOffRequiredExtensions node.
	URIPreventTurningOffRequiredExtensions = "./User/Vendor/MSFT/Policy/Config/Browser/PreventTurningOffRequiredExtensions"
	// the PreventUsingLocalHostIPAddressForWebRTC node.
	URIPreventUsingLocalHostIPAddressForWebRTC = "./User/Vendor/MSFT/Policy/Config/Browser/PreventUsingLocalHostIPAddressForWebRTC"
	// the ProvisionFavorites node.
	URIProvisionFavorites = "./User/Vendor/MSFT/Policy/Config/Browser/ProvisionFavorites"
	// the SendIntranetTraffictoInternetExplorer node.
	URISendIntranetTraffictoInternetExplorer = "./User/Vendor/MSFT/Policy/Config/Browser/SendIntranetTraffictoInternetExplorer"
	// the SetDefaultSearchEngine node.
	URISetDefaultSearchEngine = "./User/Vendor/MSFT/Policy/Config/Browser/SetDefaultSearchEngine"
	// the SetHomeButtonURL node.
	URISetHomeButtonURL = "./User/Vendor/MSFT/Policy/Config/Browser/SetHomeButtonURL"
	// the SetNewTabPageURL node.
	URISetNewTabPageURL = "./User/Vendor/MSFT/Policy/Config/Browser/SetNewTabPageURL"
	// the ShowMessageWhenOpeningSitesInInternetExplorer node.
	URIShowMessageWhenOpeningSitesInInternetExplorer = "./User/Vendor/MSFT/Policy/Config/Browser/ShowMessageWhenOpeningSitesInInternetExplorer"
	// the SyncFavoritesBetweenIEAndMicrosoftEdge node.
	URISyncFavoritesBetweenIEAndMicrosoftEdge = "./User/Vendor/MSFT/Policy/Config/Browser/SyncFavoritesBetweenIEAndMicrosoftEdge"
	// the UnlockHomeButton node.
	URIUnlockHomeButton = "./User/Vendor/MSFT/Policy/Config/Browser/UnlockHomeButton"
	// the UseSharedFolderForBooks node.
	URIUseSharedFolderForBooks = "./User/Vendor/MSFT/Policy/Config/Browser/UseSharedFolderForBooks"
)
