// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package browser_user binds the Browser Policy CSP area
// (./User/Vendor/MSFT/Policy/Config/Browser).
//
// Generated from the February 2026 DDF v2 release.
package browser_user
