// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package activesync

// AccountsAccountGUIDOptionsContentTypesContentTypeGUIDEnabledValue — allowed values for the Enabled node.
type AccountsAccountGUIDOptionsContentTypesContentTypeGUIDEnabledValue string

const (
	// Sync for email, contacts, calendar, or tasks is disabled.
	AccountsAccountGUIDOptionsContentTypesContentTypeGUIDEnabledSyncForEmailContactsCalendarOr AccountsAccountGUIDOptionsContentTypesContentTypeGUIDEnabledValue = "0"
	// Sync is enabled.
	AccountsAccountGUIDOptionsContentTypesContentTypeGUIDEnabledSyncIsEnabled AccountsAccountGUIDOptionsContentTypesContentTypeGUIDEnabledValue = "1"
)

// String returns the AccountsAccountGUIDOptionsContentTypesContentTypeGUIDEnabledValue value as a plain string.
func (e AccountsAccountGUIDOptionsContentTypesContentTypeGUIDEnabledValue) String() string {
	return string(e)
}

// AccountsAccountGUIDOptionsLoggingValue — allowed values for the Logging node.
type AccountsAccountGUIDOptionsLoggingValue string

const (
	// Logging is off.
	AccountsAccountGUIDOptionsLoggingLoggingIsOff AccountsAccountGUIDOptionsLoggingValue = "0"
	// Basic logging is enabled.
	AccountsAccountGUIDOptionsLoggingBasicLoggingIsEnabled AccountsAccountGUIDOptionsLoggingValue = "1"
	// Advanced logging is enabled.
	AccountsAccountGUIDOptionsLoggingAdvancedLoggingIsEnabled AccountsAccountGUIDOptionsLoggingValue = "2"
)

// String returns the AccountsAccountGUIDOptionsLoggingValue value as a plain string.
func (e AccountsAccountGUIDOptionsLoggingValue) String() string { return string(e) }

// AccountsAccountGUIDOptionsMailAgeFilterValue — allowed values for the MailAgeFilter node.
type AccountsAccountGUIDOptionsMailAgeFilterValue string

const (
	// No age filter is used, and all email items are synced to the device.
	AccountsAccountGUIDOptionsMailAgeFilterNoAgeFilterIsUsedAnd AccountsAccountGUIDOptionsMailAgeFilterValue = "0"
	// Only email up to one day old is synced to the device
	AccountsAccountGUIDOptionsMailAgeFilterOnlyEmailUpToOneDay AccountsAccountGUIDOptionsMailAgeFilterValue = "1"
	// Only email up to three days old is synced to the device.
	AccountsAccountGUIDOptionsMailAgeFilterOnlyEmailUpToThreeDays AccountsAccountGUIDOptionsMailAgeFilterValue = "2"
	// Email up to a week old is synced to the device.
	AccountsAccountGUIDOptionsMailAgeFilterEmailUpToAWeekOld AccountsAccountGUIDOptionsMailAgeFilterValue = "3"
	// Email up to two weeks old is synced to the device.
	AccountsAccountGUIDOptionsMailAgeFilterEmailUpToTwoWeeksOld AccountsAccountGUIDOptionsMailAgeFilterValue = "4"
	// Email up to a month old is synced to the device.
	AccountsAccountGUIDOptionsMailAgeFilterEmailUpToAMonthOld AccountsAccountGUIDOptionsMailAgeFilterValue = "5"
	// Email up to three months old is synced to the device.
	AccountsAccountGUIDOptionsMailAgeFilterEmailUpToThreeMonthsOld AccountsAccountGUIDOptionsMailAgeFilterValue = "6"
)

// String returns the AccountsAccountGUIDOptionsMailAgeFilterValue value as a plain string.
func (e AccountsAccountGUIDOptionsMailAgeFilterValue) String() string { return string(e) }

// AccountsAccountGUIDOptionsMailBodyTypeValue — allowed values for the MailBodyType node.
type AccountsAccountGUIDOptionsMailBodyTypeValue string

const (
	// none
	AccountsAccountGUIDOptionsMailBodyTypeNone AccountsAccountGUIDOptionsMailBodyTypeValue = "0"
	// text
	AccountsAccountGUIDOptionsMailBodyTypeText AccountsAccountGUIDOptionsMailBodyTypeValue = "1"
	// HTML
	AccountsAccountGUIDOptionsMailBodyTypeHTML AccountsAccountGUIDOptionsMailBodyTypeValue = "2"
	// RTF
	AccountsAccountGUIDOptionsMailBodyTypeRTF AccountsAccountGUIDOptionsMailBodyTypeValue = "3"
	// MIME
	AccountsAccountGUIDOptionsMailBodyTypeMIME AccountsAccountGUIDOptionsMailBodyTypeValue = "4"
)

// String returns the AccountsAccountGUIDOptionsMailBodyTypeValue value as a plain string.
func (e AccountsAccountGUIDOptionsMailBodyTypeValue) String() string { return string(e) }

// AccountsAccountGUIDOptionsUseSSLValue — allowed values for the UseSSL node.
type AccountsAccountGUIDOptionsUseSSLValue string

const (
	// SSL is not used.
	AccountsAccountGUIDOptionsUseSSLSSLIsNotUsed AccountsAccountGUIDOptionsUseSSLValue = "0"
	// SSL is used.
	AccountsAccountGUIDOptionsUseSSLSSLIsUsed AccountsAccountGUIDOptionsUseSSLValue = "1"
)

// String returns the AccountsAccountGUIDOptionsUseSSLValue value as a plain string.
func (e AccountsAccountGUIDOptionsUseSSLValue) String() string { return string(e) }

// AccountsAccountGUIDPoliciesMailBodyTypeValue — allowed values for the MailBodyType node.
type AccountsAccountGUIDPoliciesMailBodyTypeValue string

const (
	// HTML
	AccountsAccountGUIDPoliciesMailBodyTypeHTML AccountsAccountGUIDPoliciesMailBodyTypeValue = "HTML"
	// plain
	AccountsAccountGUIDPoliciesMailBodyTypePlain AccountsAccountGUIDPoliciesMailBodyTypeValue = "plain"
)

// String returns the AccountsAccountGUIDPoliciesMailBodyTypeValue value as a plain string.
func (e AccountsAccountGUIDPoliciesMailBodyTypeValue) String() string { return string(e) }
