// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_tpm

// OMA-URIs of the ADMX_TPM nodes addressed by this package.
const (
	// the ADMX_TPM root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM"
	// the BlockedCommandsList_Name node.
	URIBlockedCommandsListName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/BlockedCommandsList_Name"
	// the ClearTPMIfNotReady_Name node.
	URIClearTPMIfNotReadyName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/ClearTPMIfNotReady_Name"
	// the IgnoreDefaultList_Name node.
	URIIgnoreDefaultListName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/IgnoreDefaultList_Name"
	// the IgnoreLocalList_Name node.
	URIIgnoreLocalListName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/IgnoreLocalList_Name"
	// the OSManagedAuth_Name node.
	URIOSManagedAuthName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/OSManagedAuth_Name"
	// the OptIntoDSHA_Name node.
	URIOptIntoDSHAName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/OptIntoDSHA_Name"
	// the StandardUserAuthorizationFailureDuration_Name node.
	URIStandardUserAuthorizationFailureDurationName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureDuration_Name"
	// the StandardUserAuthorizationFailureIndividualThreshold_Name node.
	URIStandardUserAuthorizationFailureIndividualThresholdName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureIndividualThreshold_Name"
	// the StandardUserAuthorizationFailureTotalThreshold_Name node.
	URIStandardUserAuthorizationFailureTotalThresholdName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureTotalThreshold_Name"
	// the UseLegacyDAP_Name node.
	URIUseLegacyDAPName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/UseLegacyDAP_Name"
)
