// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_soundrec

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetSoundrecDiableApplicationTitleText2 reads ./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXSoundRec) GetSoundrecDiableApplicationTitleText2(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URISoundrecDiableApplicationTitleText2)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateSoundrecDiableApplicationTitleText2 creates ./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXSoundRec) CreateSoundrecDiableApplicationTitleText2(ctx context.Context, value string) error {
	return s.c.Add(ctx, URISoundrecDiableApplicationTitleText2, client.Chr(value))
}

// UpdateSoundrecDiableApplicationTitleText2 updates ./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXSoundRec) UpdateSoundrecDiableApplicationTitleText2(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URISoundrecDiableApplicationTitleText2, client.Chr(value))
}

// DeleteSoundrecDiableApplicationTitleText2 deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXSoundRec) DeleteSoundrecDiableApplicationTitleText2(ctx context.Context) error {
	return s.c.Delete(ctx, URISoundrecDiableApplicationTitleText2)
}
