// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package appvirtualization binds the AppVirtualization Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/AppVirtualization).
//
// Generated from the February 2026 DDF v2 release.
package appvirtualization
