// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package windowslogon

// EnableFirstLogonAnimation allowed values.
const (
	// Disabled.
	EnableFirstLogonAnimationDisabled int64 = 0
	// Enabled.
	EnableFirstLogonAnimationEnabled int64 = 1
)

// HideFastUserSwitching allowed values.
const (
	// Disabled (visible).
	HideFastUserSwitchingDisabled int64 = 0
	// Enabled (hidden).
	HideFastUserSwitchingEnabled int64 = 1
)

// OverrideShellProgram allowed values.
const (
	// Not Configured
	OverrideShellProgramNotConfigured int64 = 0
	// Apply Lightweight shell
	OverrideShellProgramApplyLightweightShell int64 = 1
)
