// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_radar binds the ADMX_Radar Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_Radar).
//
// Generated from the February 2026 DDF v2 release.
package admx_radar
