// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package secureassessment

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetAllowScreenMonitoring reads ./Vendor/MSFT/SecureAssessment/AllowScreenMonitoring.
// Indicates if screen monitoring is allowed by the app.
//
// Default: 0.
func (s *SecureAssessment) GetAllowScreenMonitoring(ctx context.Context) (AllowScreenMonitoringValue, error) {
	v, err := s.c.Get(ctx, URIAllowScreenMonitoring)
	if err != nil {
		return 0, err
	}
	n, err := v.Int()
	return AllowScreenMonitoringValue(n), err
}

// UpdateAllowScreenMonitoring updates ./Vendor/MSFT/SecureAssessment/AllowScreenMonitoring.
// Indicates if screen monitoring is allowed by the app.
//
// Default: 0.
func (s *SecureAssessment) UpdateAllowScreenMonitoring(ctx context.Context, value AllowScreenMonitoringValue) error {
	return s.c.Replace(ctx, URIAllowScreenMonitoring, client.Int(int64(value)))
}

// GetAllowTextSuggestions reads ./Vendor/MSFT/SecureAssessment/AllowTextSuggestions.
// Indicates if keyboard text suggestions are allowed by the app.
//
// Default: 0.
func (s *SecureAssessment) GetAllowTextSuggestions(ctx context.Context) (AllowTextSuggestionsValue, error) {
	v, err := s.c.Get(ctx, URIAllowTextSuggestions)
	if err != nil {
		return 0, err
	}
	n, err := v.Int()
	return AllowTextSuggestionsValue(n), err
}

// UpdateAllowTextSuggestions updates ./Vendor/MSFT/SecureAssessment/AllowTextSuggestions.
// Indicates if keyboard text suggestions are allowed by the app.
//
// Default: 0.
func (s *SecureAssessment) UpdateAllowTextSuggestions(ctx context.Context, value AllowTextSuggestionsValue) error {
	return s.c.Replace(ctx, URIAllowTextSuggestions, client.Int(int64(value)))
}

// GetAssessments reads ./Vendor/MSFT/SecureAssessment/Assessments.
// Enables support for multiple assessments and for assessment grouping. The structure is specified
// by an XML.
//
// Supported from OS build 10.0.22621.521.
func (s *SecureAssessment) GetAssessments(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIAssessments)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateAssessments creates ./Vendor/MSFT/SecureAssessment/Assessments.
// Enables support for multiple assessments and for assessment grouping. The structure is specified
// by an XML.
//
// Supported from OS build 10.0.22621.521.
func (s *SecureAssessment) CreateAssessments(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIAssessments, client.Chr(value))
}

// UpdateAssessments updates ./Vendor/MSFT/SecureAssessment/Assessments.
// Enables support for multiple assessments and for assessment grouping. The structure is specified
// by an XML.
//
// Supported from OS build 10.0.22621.521.
func (s *SecureAssessment) UpdateAssessments(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIAssessments, client.Chr(value))
}

// DeleteAssessments deletes ./Vendor/MSFT/SecureAssessment/Assessments.
// Enables support for multiple assessments and for assessment grouping. The structure is specified
// by an XML.
//
// Supported from OS build 10.0.22621.521.
func (s *SecureAssessment) DeleteAssessments(ctx context.Context) error {
	return s.c.Delete(ctx, URIAssessments)
}

// GetLaunchURI reads ./Vendor/MSFT/SecureAssessment/LaunchURI.
// Link to an assessment that's automatically loaded when the Secure Assessment Browser is
// launched.
func (s *SecureAssessment) GetLaunchURI(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URILaunchURI)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateLaunchURI creates ./Vendor/MSFT/SecureAssessment/LaunchURI.
// Link to an assessment that's automatically loaded when the Secure Assessment Browser is
// launched.
func (s *SecureAssessment) CreateLaunchURI(ctx context.Context, value string) error {
	return s.c.Add(ctx, URILaunchURI, client.Chr(value))
}

// UpdateLaunchURI updates ./Vendor/MSFT/SecureAssessment/LaunchURI.
// Link to an assessment that's automatically loaded when the Secure Assessment Browser is
// launched.
func (s *SecureAssessment) UpdateLaunchURI(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URILaunchURI, client.Chr(value))
}

// DeleteLaunchURI deletes ./Vendor/MSFT/SecureAssessment/LaunchURI.
// Link to an assessment that's automatically loaded when the Secure Assessment Browser is
// launched.
func (s *SecureAssessment) DeleteLaunchURI(ctx context.Context) error {
	return s.c.Delete(ctx, URILaunchURI)
}

// GetRequirePrinting reads ./Vendor/MSFT/SecureAssessment/RequirePrinting.
// Indicates if printing is required by the app.
//
// Default: 1.
func (s *SecureAssessment) GetRequirePrinting(ctx context.Context) (RequirePrintingValue, error) {
	v, err := s.c.Get(ctx, URIRequirePrinting)
	if err != nil {
		return 0, err
	}
	n, err := v.Int()
	return RequirePrintingValue(n), err
}

// UpdateRequirePrinting updates ./Vendor/MSFT/SecureAssessment/RequirePrinting.
// Indicates if printing is required by the app.
//
// Default: 1.
func (s *SecureAssessment) UpdateRequirePrinting(ctx context.Context, value RequirePrintingValue) error {
	return s.c.Replace(ctx, URIRequirePrinting, client.Int(int64(value)))
}

// GetTesterAccount reads ./Vendor/MSFT/SecureAssessment/TesterAccount.
// The user name of the test taking account. To specify a domain account, use domain\user. To
// specify an AAD account, use username@tenant.com. To specify a local account, use the username.
func (s *SecureAssessment) GetTesterAccount(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URITesterAccount)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateTesterAccount creates ./Vendor/MSFT/SecureAssessment/TesterAccount.
// The user name of the test taking account. To specify a domain account, use domain\user. To
// specify an AAD account, use username@tenant.com. To specify a local account, use the username.
func (s *SecureAssessment) CreateTesterAccount(ctx context.Context, value string) error {
	return s.c.Add(ctx, URITesterAccount, client.Chr(value))
}

// UpdateTesterAccount updates ./Vendor/MSFT/SecureAssessment/TesterAccount.
// The user name of the test taking account. To specify a domain account, use domain\user. To
// specify an AAD account, use username@tenant.com. To specify a local account, use the username.
func (s *SecureAssessment) UpdateTesterAccount(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URITesterAccount, client.Chr(value))
}

// DeleteTesterAccount deletes ./Vendor/MSFT/SecureAssessment/TesterAccount.
// The user name of the test taking account. To specify a domain account, use domain\user. To
// specify an AAD account, use username@tenant.com. To specify a local account, use the username.
func (s *SecureAssessment) DeleteTesterAccount(ctx context.Context) error {
	return s.c.Delete(ctx, URITesterAccount)
}
