// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package applicationmanagement

// OMA-URIs of the ApplicationManagement nodes addressed by this package.
const (
	// the ApplicationManagement root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement"
	// the AllowAllTrustedApps node.
	URIAllowAllTrustedApps = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/AllowAllTrustedApps"
	// the AllowAppStoreAutoUpdate node.
	URIAllowAppStoreAutoUpdate = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/AllowAppStoreAutoUpdate"
	// the AllowAutomaticAppArchiving node.
	URIAllowAutomaticAppArchiving = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/AllowAutomaticAppArchiving"
	// the AllowDeveloperUnlock node.
	URIAllowDeveloperUnlock = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/AllowDeveloperUnlock"
	// the AllowGameDVR node.
	URIAllowGameDVR = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/AllowGameDVR"
	// the AllowSharedUserAppData node.
	URIAllowSharedUserAppData = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/AllowSharedUserAppData"
	// the AllowStore node.
	URIAllowStore = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/AllowStore"
	// the AllowedNonAdminPackageFamilyNameRules node.
	URIAllowedNonAdminPackageFamilyNameRules = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/AllowedNonAdminPackageFamilyNameRules"
	// the ApplicationRestrictions node.
	URIApplicationRestrictions = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/ApplicationRestrictions"
	// the BlockNonAdminUserInstall node.
	URIBlockNonAdminUserInstall = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/BlockNonAdminUserInstall"
	// the ConfigureMSIXAuthenticationAuthorizedDomains node.
	URIConfigureMSIXAuthenticationAuthorizedDomains = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/ConfigureMSIXAuthenticationAuthorizedDomains"
	// the DisableStoreOriginatedApps node.
	URIDisableStoreOriginatedApps = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/DisableStoreOriginatedApps"
	// the EnableMsixAllowedZones node.
	URIEnableMsixAllowedZones = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/EnableMsixAllowedZones"
	// the EnableMsixSmartScreenCheck node.
	URIEnableMsixSmartScreenCheck = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/EnableMsixSmartScreenCheck"
	// the LaunchAppAfterLogOn node.
	URILaunchAppAfterLogOn = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/LaunchAppAfterLogOn"
	// the MSIAllowUserControlOverInstall node.
	URIMSIAllowUserControlOverInstall = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/MSIAllowUserControlOverInstall"
	// the MSIAlwaysInstallWithElevatedPrivileges node.
	URIMSIAlwaysInstallWithElevatedPrivileges = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/MSIAlwaysInstallWithElevatedPrivileges"
	// the RemoveDefaultMicrosoftStorePackages node.
	URIRemoveDefaultMicrosoftStorePackages = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/RemoveDefaultMicrosoftStorePackages"
	// the RequirePrivateStoreOnly node.
	URIRequirePrivateStoreOnly = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/RequirePrivateStoreOnly"
	// the RestrictAppDataToSystemVolume node.
	URIRestrictAppDataToSystemVolume = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/RestrictAppDataToSystemVolume"
	// the RestrictAppToSystemVolume node.
	URIRestrictAppToSystemVolume = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/RestrictAppToSystemVolume"
	// the ScheduleForceRestartForUpdateFailures node.
	URIScheduleForceRestartForUpdateFailures = "./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/ScheduleForceRestartForUpdateFailures"
)
