// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package troubleshooting

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// Troubleshooting exposes LCRUD operations over the Troubleshooting Policy area nodes.
type Troubleshooting struct {
	c client.Client
}

// NewTroubleshooting returns a Troubleshooting service backed by transport c.
func NewTroubleshooting(c client.Client) *Troubleshooting {
	return &Troubleshooting{c: c}
}
