// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_datacollection

// OMA-URIs of the ADMX_DataCollection nodes addressed by this package.
const (
	// the ADMX_DataCollection root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_DataCollection"
	// the CommercialIdPolicy node.
	URICommercialIdPolicy = "./Device/Vendor/MSFT/Policy/Config/ADMX_DataCollection/CommercialIdPolicy"
)
