// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_reliability

// OMA-URIs of the ADMX_Reliability nodes addressed by this package.
const (
	// the ADMX_Reliability root node.
	URIRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability"
	// the EE_EnablePersistentTimeStamp node.
	URIEEEnablePersistentTimeStamp = "./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/EE_EnablePersistentTimeStamp"
	// the PCH_ReportShutdownEvents node.
	URIPCHReportShutdownEvents = "./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/PCH_ReportShutdownEvents"
	// the ShutdownEventTrackerStateFile node.
	URIShutdownEventTrackerStateFile = "./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownEventTrackerStateFile"
	// the ShutdownReason node.
	URIShutdownReason = "./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownReason"
)
