// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_reliability

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetEEEnablePersistentTimeStamp reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/EE_EnablePersistentTimeStamp.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) GetEEEnablePersistentTimeStamp(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIEEEnablePersistentTimeStamp)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateEEEnablePersistentTimeStamp creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/EE_EnablePersistentTimeStamp.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) CreateEEEnablePersistentTimeStamp(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIEEEnablePersistentTimeStamp, client.Chr(value))
}

// UpdateEEEnablePersistentTimeStamp updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/EE_EnablePersistentTimeStamp.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) UpdateEEEnablePersistentTimeStamp(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIEEEnablePersistentTimeStamp, client.Chr(value))
}

// DeleteEEEnablePersistentTimeStamp deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/EE_EnablePersistentTimeStamp.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) DeleteEEEnablePersistentTimeStamp(ctx context.Context) error {
	return s.c.Delete(ctx, URIEEEnablePersistentTimeStamp)
}

// GetPCHReportShutdownEvents reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/PCH_ReportShutdownEvents.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) GetPCHReportShutdownEvents(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIPCHReportShutdownEvents)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreatePCHReportShutdownEvents creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/PCH_ReportShutdownEvents.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) CreatePCHReportShutdownEvents(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIPCHReportShutdownEvents, client.Chr(value))
}

// UpdatePCHReportShutdownEvents updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/PCH_ReportShutdownEvents.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) UpdatePCHReportShutdownEvents(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIPCHReportShutdownEvents, client.Chr(value))
}

// DeletePCHReportShutdownEvents deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/PCH_ReportShutdownEvents.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) DeletePCHReportShutdownEvents(ctx context.Context) error {
	return s.c.Delete(ctx, URIPCHReportShutdownEvents)
}

// GetShutdownEventTrackerStateFile reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownEventTrackerStateFile.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) GetShutdownEventTrackerStateFile(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIShutdownEventTrackerStateFile)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateShutdownEventTrackerStateFile creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownEventTrackerStateFile.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) CreateShutdownEventTrackerStateFile(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIShutdownEventTrackerStateFile, client.Chr(value))
}

// UpdateShutdownEventTrackerStateFile updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownEventTrackerStateFile.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) UpdateShutdownEventTrackerStateFile(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIShutdownEventTrackerStateFile, client.Chr(value))
}

// DeleteShutdownEventTrackerStateFile deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownEventTrackerStateFile.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) DeleteShutdownEventTrackerStateFile(ctx context.Context) error {
	return s.c.Delete(ctx, URIShutdownEventTrackerStateFile)
}

// GetShutdownReason reads ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownReason.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) GetShutdownReason(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIShutdownReason)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateShutdownReason creates ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownReason.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) CreateShutdownReason(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIShutdownReason, client.Chr(value))
}

// UpdateShutdownReason updates ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownReason.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) UpdateShutdownReason(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIShutdownReason, client.Chr(value))
}

// DeleteShutdownReason deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_Reliability/ShutdownReason.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXReliability) DeleteShutdownReason(ctx context.Context) error {
	return s.c.Delete(ctx, URIShutdownReason)
}
