// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package camera

// AllowCamera allowed values.
const (
	// Not allowed.
	AllowCameraNotAllowed int64 = 0
	// Allowed.
	AllowCameraAllowed int64 = 1
)
