// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_controlpaneldisplay_user

// OMA-URIs of the ADMX_ControlPanelDisplay nodes addressed by this package.
const (
	// the ADMX_ControlPanelDisplay root node.
	URIRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay"
	// the CPL_Display_Disable node.
	URICPLDisplayDisable = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Display_Disable"
	// the CPL_Display_HideSettings node.
	URICPLDisplayHideSettings = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Display_HideSettings"
	// the CPL_Personalization_DisableColorSchemeChoice node.
	URICPLPersonalizationDisableColorSchemeChoice = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_DisableColorSchemeChoice"
	// the CPL_Personalization_DisableThemeChange node.
	URICPLPersonalizationDisableThemeChange = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_DisableThemeChange"
	// the CPL_Personalization_DisableVisualStyle node.
	URICPLPersonalizationDisableVisualStyle = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_DisableVisualStyle"
	// the CPL_Personalization_EnableScreenSaver node.
	URICPLPersonalizationEnableScreenSaver = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_EnableScreenSaver"
	// the CPL_Personalization_LockFontSize node.
	URICPLPersonalizationLockFontSize = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_LockFontSize"
	// the CPL_Personalization_NoColorAppearanceUI node.
	URICPLPersonalizationNoColorAppearanceUI = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_NoColorAppearanceUI"
	// the CPL_Personalization_NoDesktopBackgroundUI node.
	URICPLPersonalizationNoDesktopBackgroundUI = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_NoDesktopBackgroundUI"
	// the CPL_Personalization_NoDesktopIconsUI node.
	URICPLPersonalizationNoDesktopIconsUI = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_NoDesktopIconsUI"
	// the CPL_Personalization_NoMousePointersUI node.
	URICPLPersonalizationNoMousePointersUI = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_NoMousePointersUI"
	// the CPL_Personalization_NoScreenSaverUI node.
	URICPLPersonalizationNoScreenSaverUI = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_NoScreenSaverUI"
	// the CPL_Personalization_NoSoundSchemeUI node.
	URICPLPersonalizationNoSoundSchemeUI = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_NoSoundSchemeUI"
	// the CPL_Personalization_ScreenSaverIsSecure node.
	URICPLPersonalizationScreenSaverIsSecure = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_ScreenSaverIsSecure"
	// the CPL_Personalization_ScreenSaverTimeOut node.
	URICPLPersonalizationScreenSaverTimeOut = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_ScreenSaverTimeOut"
	// the CPL_Personalization_SetScreenSaver node.
	URICPLPersonalizationSetScreenSaver = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_SetScreenSaver"
	// the CPL_Personalization_SetTheme node.
	URICPLPersonalizationSetTheme = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_SetTheme"
	// the CPL_Personalization_SetVisualStyle node.
	URICPLPersonalizationSetVisualStyle = "./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay/CPL_Personalization_SetVisualStyle"
)
