// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_controlpaneldisplay_user binds the ADMX_ControlPanelDisplay Policy CSP area
// (./User/Vendor/MSFT/Policy/Config/ADMX_ControlPanelDisplay).
//
// Generated from the February 2026 DDF v2 release.
package admx_controlpaneldisplay_user
