// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_pentraining

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetPenTrainingOff2 reads ./Device/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPenTraining) GetPenTrainingOff2(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIPenTrainingOff2)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreatePenTrainingOff2 creates ./Device/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPenTraining) CreatePenTrainingOff2(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIPenTrainingOff2, client.Chr(value))
}

// UpdatePenTrainingOff2 updates ./Device/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPenTraining) UpdatePenTrainingOff2(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIPenTrainingOff2, client.Chr(value))
}

// DeletePenTrainingOff2 deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_2.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXPenTraining) DeletePenTrainingOff2(ctx context.Context) error {
	return s.c.Delete(ctx, URIPenTrainingOff2)
}
