// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

// Package admx_lanmanserver binds the ADMX_LanmanServer Policy CSP area
// (./Device/Vendor/MSFT/Policy/Config/ADMX_LanmanServer).
//
// Generated from the February 2026 DDF v2 release.
package admx_lanmanserver
