// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package languagepackmanagement

// OMA-URIs of the LanguagePackManagement nodes addressed by this package.
const (
	// the LanguagePackManagement root node.
	URIRoot = "./Device/Vendor/MSFT/LanguagePackManagement"
	// the Install node.
	URIInstall = "./Device/Vendor/MSFT/LanguagePackManagement/Install"
	// the InstalledLanguages node.
	URIInstalledLanguages = "./Device/Vendor/MSFT/LanguagePackManagement/InstalledLanguages"
	// the LanguageSettings/SystemPreferredUILanguages node.
	URILanguageSettingsSystemPreferredUILanguages = "./Device/Vendor/MSFT/LanguagePackManagement/LanguageSettings/SystemPreferredUILanguages"
)

// URIInstallLanguageID returns the OMA-URI for the Install/{languageID} node.
func URIInstallLanguageID(languageID string) string {
	return "./Device/Vendor/MSFT/LanguagePackManagement/Install/" + languageID
}

// URIInstallLanguageIDCopyToDeviceInternationalSettings returns the OMA-URI for the Install/{languageID}/CopyToDeviceInternationalSettings node.
func URIInstallLanguageIDCopyToDeviceInternationalSettings(languageID string) string {
	return "./Device/Vendor/MSFT/LanguagePackManagement/Install/" + languageID + "/CopyToDeviceInternationalSettings"
}

// URIInstallLanguageIDEnableLanguageFeatureInstallations returns the OMA-URI for the Install/{languageID}/EnableLanguageFeatureInstallations node.
func URIInstallLanguageIDEnableLanguageFeatureInstallations(languageID string) string {
	return "./Device/Vendor/MSFT/LanguagePackManagement/Install/" + languageID + "/EnableLanguageFeatureInstallations"
}

// URIInstallLanguageIDErrorCode returns the OMA-URI for the Install/{languageID}/ErrorCode node.
func URIInstallLanguageIDErrorCode(languageID string) string {
	return "./Device/Vendor/MSFT/LanguagePackManagement/Install/" + languageID + "/ErrorCode"
}

// URIInstallLanguageIDStartInstallation returns the OMA-URI for the Install/{languageID}/StartInstallation node.
func URIInstallLanguageIDStartInstallation(languageID string) string {
	return "./Device/Vendor/MSFT/LanguagePackManagement/Install/" + languageID + "/StartInstallation"
}

// URIInstallLanguageIDStatus returns the OMA-URI for the Install/{languageID}/Status node.
func URIInstallLanguageIDStatus(languageID string) string {
	return "./Device/Vendor/MSFT/LanguagePackManagement/Install/" + languageID + "/Status"
}

// URIInstalledLanguagesLanguageID returns the OMA-URI for the InstalledLanguages/{languageID} node.
func URIInstalledLanguagesLanguageID(languageID string) string {
	return "./Device/Vendor/MSFT/LanguagePackManagement/InstalledLanguages/" + languageID
}

// URIInstalledLanguagesLanguageIDLanguageFeatures returns the OMA-URI for the InstalledLanguages/{languageID}/LanguageFeatures node.
func URIInstalledLanguagesLanguageIDLanguageFeatures(languageID string) string {
	return "./Device/Vendor/MSFT/LanguagePackManagement/InstalledLanguages/" + languageID + "/LanguageFeatures"
}

// URIInstalledLanguagesLanguageIDProviders returns the OMA-URI for the InstalledLanguages/{languageID}/Providers node.
func URIInstalledLanguagesLanguageIDProviders(languageID string) string {
	return "./Device/Vendor/MSFT/LanguagePackManagement/InstalledLanguages/" + languageID + "/Providers"
}
