// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_helpandsupport

import (
	"context"

	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// GetActiveHelp reads ./Device/Vendor/MSFT/Policy/Config/ADMX_HelpAndSupport/ActiveHelp.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXHelpAndSupport) GetActiveHelp(ctx context.Context) (string, error) {
	v, err := s.c.Get(ctx, URIActiveHelp)
	if err != nil {
		return "", err
	}
	return v.Str(), nil
}

// CreateActiveHelp creates ./Device/Vendor/MSFT/Policy/Config/ADMX_HelpAndSupport/ActiveHelp.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXHelpAndSupport) CreateActiveHelp(ctx context.Context, value string) error {
	return s.c.Add(ctx, URIActiveHelp, client.Chr(value))
}

// UpdateActiveHelp updates ./Device/Vendor/MSFT/Policy/Config/ADMX_HelpAndSupport/ActiveHelp.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXHelpAndSupport) UpdateActiveHelp(ctx context.Context, value string) error {
	return s.c.Replace(ctx, URIActiveHelp, client.Chr(value))
}

// DeleteActiveHelp deletes ./Device/Vendor/MSFT/Policy/Config/ADMX_HelpAndSupport/ActiveHelp.
//
// Supported from OS build 10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202 (CSP v10.0).
func (s *ADMXHelpAndSupport) DeleteActiveHelp(ctx context.Context) error {
	return s.c.Delete(ctx, URIActiveHelp)
}
