// Code generated by go-sdk-windowscsp-codegen. DO NOT EDIT.

package admx_wincal

import (
	"github.com/deploymenttheory/go-sdk-windowscsp/windowscsp/client"
)

// ADMXWinCal exposes LCRUD operations over the ADMX_WinCal Policy area nodes.
type ADMXWinCal struct {
	c client.Client
}

// NewADMXWinCal returns a ADMXWinCal service backed by transport c.
func NewADMXWinCal(c client.Client) *ADMXWinCal {
	return &ADMXWinCal{c: c}
}
